(html (@ (lang (%data lang)))
  (head
    (meta (@ (name "author") (content "Simon Kongshøj")))
    (meta (@ (name "generator") (content "Plutonium")))
    (meta (@ (name "viewport") (content "width=device-width, initial-scale=1")))
    (meta (@ (property "og:image") (content "http://datarama.dk/img/og.png")))
    (meta (@ (property "og:image:width") (content "1200")))
    (meta (@ (property "og:image:height") (content "630")))
    (%data meta)
    (link (@ (rel "stylesheet") (type "text/css") (href "css/style.css")))
    (link (@ (rel "icon") (type "image/png") (href "favicon-16x16.png") (sizes "16x16")))
    (link (@ (rel "icon") (type "image/png") (href "favicon-32x32.png") (sizes "32x32")))
    (link (@ (rel "icon") (type "image/png") (href "favicon-96x96.png") (sizes "96x96")))
    (title (%data header-title)))
  (body
    (div (@ (id "topmatter"))
         (a (@ (href "index.html"))
            (img (@ (id "sitetitle") (alt "DATARAMA") (src "img/datarama.svg") (width "380")))))
    (div (@ (id "main") (class (%data pageclass)))
      (div (@ (id "sidebar"))
           (div 
                (%data image)
                (%data sidebar)
                (div (@ (class "sidebar-module-outer"))
                     (div (@ (class "sidebar-module"))
                       (%data date)
                       (%data author)
                       (%data rating)))
                (div (@ (class "sidebar-module-outer"))
                     (div (@ (class "sidebar-module"))
                          (%data related)))))
      (div (@ (id "content"))
        (%data title)
        (%data subtitle)
        (%data content)
        (div (@ (id "breaker")) &nbsp\;)))
    (div (@ (id "bottommatter"))
         (a (@ (href "mailto:skongshoj@gmail.com"))
            "Written by Simon Kongshøj") 
         " · "
         (a (@ (href "Content%20License.html"))
            "CC-BY-4.0")
         " · "
         (a (@ (href "Plutonium.html"))
            "Powered by Plutonium"))))
