%author Paul McAuley
%date 2014-04-20
%rating 2
%endnote I hereby propose the use of "Prometheus" as a measuring unit of stupidity in sci-fi; this book weighs in at about 24 milliPrometheus.

This is the first Paul McAuley book I read that isn't from the *Quiet War*
universe.  Unfortunately, it's also a mediocre and forgettable read.

It's not a *bad* book, per se - there was no [[Ringworld]]esque
wall-banger moments, no bloated florid prose, no infuriatingly nonsensical plot
contrivances, no poorly-veiled sexism, racism or homophobia. Its problem is
that there was also very little truly *interesting* about it.

It takes place on an alien planet, which might hold an answer to a
galaxy-spanning mystery: Who is the alien species known only as "the enemy"?
Humans (who live in a highly militarized society dominated by the Earth nation
of Greater Brazil, following the Age of Waste - concepts that ended up getting
recycled in *The Quiet War* and work much better there) have had contact with a
hostile sentient race, and have discovered a planet which might be *designed*
by the enemy, and might hold secrets useful to defeating them. A telepath (who
also happens to be an astronomer) is dispatched there to help the scientific
research into the nature of the planet and its subsentient inhabitants. Of
course, things - as in all good science fiction stories - don't go according to
plan.

I liked the explanations of the biology on the alien planet on which it is set
(with one caveat, see below), and I liked the periodic
sentience-to-subsentience-and-back-again lifecycle of the alien civilization
that it focuses on. The human interaction between the characters is lifeless.

The characters are dull. They're not ridiculous stereotypes;  they're
believable people, but incredibly boring ones. The protagonist, Dorthy Yoshida,
is annoying, selfish, sullen and entirely unsympathetic - and given that she
can read minds and comes from a troubled background, this actually makes a lot
of sense.

Speaking of mind-reading, I generally don't like psionic abilities in science
fiction. They come across as thinly-veiled magic. I've rarely seen them done
well, and they're not done well here either. Sometimes, the characters do some
appallingly stupid things. For example, at one point, four scientists on a
survey mission (on a planet with hostile fauna) go to sleep all at the same
time, without setting up any kind of defenses.  Predictably, this leads to
fatalities. This is not the only example of the plot being moved forward by
people doing dumb things. Some of them reach almost *Prometheus*-like levels of
stupid.

I found that having the planet populated by modified organisms from different
worlds (including some Earth creatures from about a million years ago) made
little sense. If all the aliens wanted was an entirely stable ecosystem around
a red dwarf star, then why make it a de-junked diversity zoo, rather than using
life from such environments exclusively?

Dull, dull, dull. Closer to bad than to good, not recommended. This is highly
unfortunate, because I know how good Paul McAuley *can* be.

In McAuley's defense, this was his debut novel. It seems to me that many of its
flaws appear to be because he hadn't quite found his voice yet.
