%date 2014-03-26
%author Stephen Hawking
%rating 5

Another book on loan from [my preciousss](http://kvantemagi.wordpress.com/).

Although I've always had a fascination for physics (and many other hard
sciences), I must admit that certain parts of modern physics - such as quantum
mechanics and some of the implications of general relativity - seem rather
esoteric to me. Although I do hold a science degree, I'm not a physicist - just
an interested layman. Stephen Hawking's *A Brief History of Time* masterfully
managed to explain quite a lot of what I had struggled to understand. 

I obviously cannot say that I now "get" modern physics - that would be a disingenuous
claim, and as Richard Feynman once quipped: *If you think you understand
quantum mechanics, you don't understand quantum mechanics*. But certain of the
aspects of this world that I had trouble understanding (such as the role of 
observation in quantum phenomena - a concept that always seemed bizarrely 
"magical" to me) are explained well enough that I had a number of "aha" moments
as things clicked into place.

From a pop science education viewpoint, I thought it was a brilliant technique
to start the book with a brief history lesson, explaining the development of
cosmological science from Eratosthenes to Einstein. This gives a relatable and
easy-to-follow progression from the intuitive to the formally mathematical - 
much like the progression of science itself. 

One slight annoyance: Hawking has a rather idiosyncratic way of expressing
large numbers. Rather than "billion", he will use "thousand million" - and
while I realize that this is probably an attempt to disambiguate between
long-scale and short-scale numbers, but I couldn't help but find constructs
like "thousand million million" bizarre and jarring - and I'm from a country
that uses long scale (unlike the English-speaking world), so I reckon he's
doing it for my benefit. Similarly, constructs like "a centimeter divided by 1
with 1 with thirty-three zeros after it" just annoyed me. We have perfectly
good numerals and a nice notation for exponentiation to express these things
with!

I also dislike Hawking's tendency to use language laden with religious
symbolism. While certainly poetic, it also makes him a generous target of 
creationist quote miners. He probably wouldn't like that, given that his
[disbelief in a personal
god](http://www.theguardian.com/science/2011/may/15/stephen-hawking-interview-there-is-no-heaven)
is on public record.

Despite these two minor gripes, I think this is a truly excellent book, one
of the best pop science books I've read in a *long* time. The writing quality
is on par with Carl Sagan and Richard Dawkins. 

Very highly recommended.
