%date 2014-10-08
%author John H. Zammito
%category [[Book Reviews]], [[Notebook]]
%rating 3

When I was reading the treatment of science in *[One-Dimensional
Man](one_dimensional_man.html)*, there were two things consistently on my mind.
First and foremost was the fact that I really, *really* miss my late
stepfather. I inherited the book from him, it was full of his margin notes
(his handwriting, like mine, probably qualifies as strong cryptography), and
it had obviously been read *many* times. I would have loved to discuss it with
him. Second, what Marcuse was describing when he launched his attack on
science and technological rationality was, to me, almost completely
*unrecognizable* as anything of the sort, bearing not even a resemblance to
anything actual scientists or technologists were doing. It reminded me of
later postmodernist antiscience of the type [hilariously satirized by Alan
Sokal](http://www.physics.nyu.edu/sokal/weinberg.html), which made me think of
*another* book inherited from my stepfather: John Zammito's *A Nice
Derangement of Epistemes*.

The book (of which nearly a third is devoted to end notes) is primarily
written as a historical account of postpositivist science studies, starting
with the 1950s works of Willard Quine through Thomas Kuhn's incommensurability
theory to the full radical constructivism of Bruno Latour, Sandra Harding
et.al. in the 2000s --- and the hilarity of the so-called *Science Wars*, 
when actual scientists finally started fighting back.

As is implied by the title, this is *not* an impartial account, nor does it
try to be one. Zammito's primary purpose is to show that philosophy of
language does not make a very good platform for studying the practice of
science, and that the radical constructivism espoused by postmodernist
philosophers is not only literally incoherent, but also that it does not even
follow from their own philosophical progenitors. In fact, this leads to a 
*derangement of epistemes*, a sad state of affairs in which empirical inquiry
becomes impossible. This applies to *science studies* rather than to science
itself, because - as Zammito rightly points out - scientists themselves have
generally brushed most of this off as bizarre hyperbolic excesses from 
humanities (case in point: It took *20 years* of postmodernist science 
criticism before scientists even responded).

There's a narrative structure that works quite well: As the post-positivist
science studies movement (eg. Quine and Kuhn) mutates into radical
postmodernist relativism (eg. Latour), and the involved philosophers grow 
progressively more pretentious and bizarre, Zammito's treatment grows
progressively more damning and, well, *funny*. It's quite obvious that Latour
(and his allies) are cast as the villain in this story, and Zammito minces no
words about this. Alan Sokal's aforementioned hoax provides a fitting climax
to the story.

It's a good book about a fascinating subject, and its primary problem is not
the author's fault: Much space is (rightly) devoted to quotes by the involved
philosophers, and most of them write with the trademark [barely coherent
impenetrability](http://www.elsewhere.org/journal/pomo/) of
postmodernism. Parts were thus *very* heavy, difficult and *boring* reading.

I still recommend it, though, if you're interested in science studies studies
(that is... appropriately meta). At some point, I should probably get Alan
Sokal's *Fashionable Nonsense*.
