%date 2014-12-14
%author James S.A. Corey
%rating 3
%category [[Book Reviews]], [[Notebook]]
%endnote It needs an Evil Empire, though, and perhaps an AI Overlord or two.

*Abaddon's Gate* is the third installment in Corey's *Expanse* series,
following after *[[Leviathan Wakes]]* and *[[Caliban's War]]*. I should review
those two at some point.

A brief recap: We follow a little motley crew of space mercenaries on
a stolen military spacecraft, who uncovered a corporate plot to
exploit a strange, ancient alien organism which apparently turns human
beings --- and most everything else --- into grey goo. The solar
system is locked in a state of cold war, with the major players being
Earth, Mars and the outer planets. Our heroes, who have thrown their
lot in with the outer planets, include: 

* *James Holden*, our captain and All-American Square-Jawed Hero. A bit
  of an insufferable ass, I take great delight in when certain crew
  members manage to deflate him a little.
* *Naomi Nagata*, engineer and Omnicompetent Badass Warrior Woman. Has
  multiple university degrees and a flight officer certificate, and
  obviously Won't Take No Guff from any man. She also happens to be
  dating Holden.
* *Alex Kamal*, pot-bellied balding space pilot who doesn't like weapons
  and prefers to talk his way out of nasty situations.
* *Amos Burton*, quiet and gigantic spaceship mechanic with a dark past
  and a penchant for strong alcohol and violent solutions to complex
  problems.

In other words, our main characters are essentially the *Firefly* crew with a
few details mashed around. This is fitting, because for better or worse, the
tone of the *Expanse* books are more like that of a TV series or a big-budget
explosion orgy than literary science fiction.  In fact, it has the feel of the
kind of eclectic science fiction RPG settings I might have run as a
16-year-old: Square-jawed heroes and omnicompetent badass warrior women!
Dastardly villains with simple motivations! Evil megacorporations!  Heroic
self-sacrifice! Explosions! Noir hardboiled detective mystery! Eldritch
horrors from beyond time and space! 

It is, however, highly entertaining. Much like the science fiction RPG
settings I'd run as a 16-year-old. Just don't expect a cerebral tale of 
future speculation.

In this particular installment, our heroes find themselves on the 
other side of a giant alien faster-than-light transfer portal,
constructed by the alien protomolecule that formed the basis of the
first two stories. The story alternates between two main threads: One
is about exploration and discovery; the other about intrigue and 
conflict. Unfortunately, it has no real conclusion. Compared to the
two preceding books, it therefore felt rather less satisfying, seeming
mostly to be filler intended to introduce the next book (which I think
will be about humanity using the ancient alien portals to spread from
the solar system to distant star systems).

Decent light reading.
