%notitle
%nodate
%image img/simon.jpg
%sidebar extra-info 

Hello.  My name is Simon Kongshøj, and I'm a medium-sized carbon-based
lifeform classified as a kind of primate. I have bipedal locomotion, an
endothermic metabolic system, a pair of fully opposable thumbs and a large
forebrain, all of which I enjoy very much. 

Through a series of fortunate events, my ancestors mastered the use of
tools and complex technology, which keeps me occupied through the
days. I used to make a living making computer programs, but through
another series of fortunate events, I'm now getting paid for [making
computer programmers](http://www.ucn.dk/).

I live on a large chunk of rock orbiting a thermonuclear fireball in a
nondescript backwater of the Milky Way galaxy. I share my rock with [my
girlfriend](http://kvantemagi.wordpress.com), and we enjoy causing all
sorts of delightful chemical reactions in each others' brains.  I consider
her the loveliest of all primates, and love her to bits and carbon-based
pieces. 

There's also about 7 billion other primates living on our rock, so it gets
a bit noisy and crowded sometimes. The view's absolutely fantastic, though.

Assorted Useless Personal Information
=====================================
* I do most of my writing with [Vim, mightiest of text editors](http://www.vim.org).
* My language of choice is [Lisp, the language of the gods](https://en.wikipedia.org/wiki/Lisp_(programming_language)).
* I despise the plant kingdom, and have [dedicated my body to its annihilation](http://en.wikipedia.org/wiki/Vegetarianism).
* Everything I ever needed to know, I learned from [H²G²](http://en.wikipedia.org/wiki/The_Hitchhiker's_Guide_to_the_Galaxy) and [SICP](http://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs).
* I share [my taste in music](http://www.independent.co.uk/news/science/death-metal-music-attracts-sharks-documentary-crew-finds-out-10381295.html) with a 450-million-year-lineage of murder machines.
* I remain convinced that [religion is God's way of telling us he doesn't exist](http://en.wikipedia.org/wiki/Atheism).
* I don't like [things that make me stupid](http://noisey.vice.com/blog/i-guess-im-straight-edge).
* ...this is also why I detest and avoid the [Java](http://docs.spring.io/spring/docs/2.5.x/api/org/springframework/aop/framework/AbstractSingletonProxyFactoryBean.html) programming language.
* I wasted my entire youth playing [Elite](http://en.wikipedia.org/wiki/Elite_(video_game)) and [Star Control II](http://en.wikipedia.org/wiki/Star_Control_II).
* I have a pet lizard, Igor the [blue-tongue skink](http://bluetongueskinks.net/).
* When not at the computer, I often hang out in [a dark alley far from reality](http://www.1000fryd.dk).
