%nodate

My name is Simon Kongshøj, and I'm a large cluster of complex
self-replicating carbon-based molecules, collectively classified as a
primate. I have bipedal locomotion, an endothermic metabolic system, a pair
of fully opposable thumbs and a large forebrain, all of which I enjoy very
much. 

I spend most of my time converting oxygen to carbon dioxide. Through a series
of fortunate events, my ancestors mastered complex tools, allowing me
to take on a variety of interesting side activities. I especially enjoy
reading, playing bass and programming computers. I used to get
paid for making computer programs, but I've managed to end up getting paid for
[making computer programmers](http://www.ucn.dk/) instead.

I live on a large rock orbiting a gigantic thermonuclear fireball. I share my
rock with [my girlfriend](http://www.candaut.wordpress.com), another cluster of
complex self-replicating carbon-based molecules. We enjoy death metal, weird old
sci-fi serials, and causing an assortment of delightful chemical reactions in
each others' brains. I consider her the loveliest of all primates, and love her
to bits and carbon-based pieces. 

There's also about 7 billion other primates living here, so it gets a bit
noisy and crowded at times. The view's utterly fantastic, though.

Random Useless Facts About Me
=============================
* I despise the plant kingdom, and have [dedicated my body to its annihilation](http://en.wikipedia.org/wiki/Vegetarianism).
* I use [Vim](http://www.vim.org/), mightiest of text editors.
* I remain convinced that [religion is God's way of telling us he doesn't exist](http://en.wikipedia.org/wiki/Atheism).
* My brain has [somewhat odd wiring](http://en.wikipedia.org/wiki/Asperger_syndrome).
* Everything I ever needed to know, I learned from [H²G²](http://en.wikipedia.org/wiki/The_Hitchhiker's_Guide_to_the_Galaxy) and [SICP](http://en.wikipedia.org/wiki/Structure_and_Interpretation_of_Computer_Programs).
* I wasted my entire youth playing [Elite](http://en.wikipedia.org/wiki/Elite_(video_game)) and [Star Control II](http://en.wikipedia.org/wiki/Star_Control_II).
* You probably wouldn't like [the music I listen to](http://en.wikipedia.org/wiki/Death_metal).
* When not at the computer, I can usually be found at [1000Fryd](http://1000fryd.dk/).
