%title Against Elections
%author David van Reybrouck
%rating 4
%date 2015-07-25
%meta This book may or may not be part of a sinister plot by the exotic-polyhedral-RPG-dice-industrial complex.

When the Greek Syriza government finally capitulated to the demands
of the troika in the summer of 2015, former finance minister Yanis
Varoufakis stated that the entire procedure was a coup that had
finally and effectively [ended Greek democracy](http://yanisvaroufakis.eu/2015/07/14/on-the-euro-summits-statement-on-greece-first-thoughts/), using banks to accomplish what the former military junta tried 
to do with tanks.  Some of the reactions to his statement was that
he was being overly dramatic, since obviously nobody were going to
prevent the Greeks from holding elections. This is true, but it
hides an assumption: That elections and democracy are synonymous.
Belgian author David van Reybrouck's *Against Elections* (currently
available in Dutch, Norwegian and Danish) makes the case that not
only are elections and democracy not synonymous, they're 
*opposed* concepts.

In *[[So Long, and Thanks for All the Fish]]*, there's this rather
wonderful passage:

> "On its world, the people are people. The leaders are lizards. The
> people hate the lizards and the lizards rule the people".
>
> "Odd", said Arthur, "I thought you said it was a democracy."
>
> "I did," said Ford. "It is."
> 
> "So," said Arthur, hoping he wasn't sounding ridiculously obtuse,
> "why don't people get rid of the lizards?" 
>
> "It honestly doesn't
> occur to them," said Ford. "They've all got the vote, so they all
> pretty much assume that the government they've voted in more or
> less approximates to the government they want."
> 
> "You mean they actually vote for the lizards?"
>
> "Oh yes," said Ford with a shrug, "of course."
>
> "But," said Arthur, going for the big one again, "why?"
>
> "Because if they didn't," said Ford, "the wrong
> lizard might get in. 

This largely reflects the situation in most of the modern Western
world: People vote for politicians that they mostly despise and
consider
[corrupt](http://www.transparency.org/research/cpi/overview),
untrustworthy, self-serving careerists utterly detached from the
lives of normal people. Many countries (including my home country,
Denmark) have sprouted what is effectively an aristocratic political
class, complete with all the usual trappings of aristocracy:
Closely-guarded special privileges, a sense of separation from the
commoners, family dynasties and all. Van Reybrouck's central point
is that this is not only an entirely predictable consequence of the
electoral system, but a *deliberate* one: Modern parliamentary
systems were consciously designed by their founders to produce
elected aristocracies (that, at least, have more legitimacy than
self-appointed ones) rather than true democracies.  Reybrouck gives
rich references for this history --- as far back as *Aristotle* (who
was *against* democracy), who considered elections *necessarily*
aristocratic and anti-democratic. Montesquieu was of the same
opinion.

Reybrouck regards this situation as a sickness of democratic
society, leading to a crisis of both legitimacy and effectivity.
He describes four diagnoses: 

1. It's the politicians' fault.
2. It's democracy's fault.
3. It's representative democracy's fault.
4. It's electoral representative democracy's fault.

The first is the *populist* diagnosis, and we see it applied
everywhere in Europe --- right-wing populist parties continue to 
win landslide victories across the continent. The proposed cure is
to get rid of all the career politicians and elect a Man of the
People (who, as it usually turns out, actually represents a
caricature of the people, with predictably disastrous results). The
second is the *technocratic* diagnosis, which has recently been
applied in Italy and Greece, where unelected governments of experts
had brief reigns. The third is the diagnosis of *direct democracy*,
as practiced by antiparliamentarian groups such as the Occupy
movement. The fourth is the diagnosis of *demarchy* (also sometimes
called lottocracy, participatory democracy or deliberative
democracy), which is what Van Reybrouck himself supports. At its
core, the idea is to replace elections (possibly only
partially) with sortition: Rather than elect representatives,
randomly select them for strictly time-limited periods.

An almost immediate response from a proponent of elections (or just
someone who's very used to thinking about democratic politics in
terms of elections) is that this seems like a terribly irresponsible
idea, that would lead to all sorts of incompetents taking office.
However, that criticism applies equally well to *any* representative
democracy, including an electoral one: Think of your least favourite
politician, and then consider that *this idiot was actually elected*.
Another criticism is that something as arbitrary as 
*winning a lottery* isn't indicative of either political skill or 
even having the people's best interests at heart --- but,
once again, neither is winning a highly ritualized, professional
mass-media popularity contest that rewards its participants for
making ridiculous promises they can't possibly keep. In an electoral
representative democracy, expertise typically isn't elected either,
it's *hired*, in the form of government department officials.

A demarchist system neatly solves some of the problems inherent in 
electoral ones: Given a working mechanism of random selection and an
inclusive definition of citizenship, it is inherently fair and 
egalitarian. It will statistically produce *fair* representation
(with a far larger degree of power to ordinary people, who are
nominally the basis of any democracy). If many successive demarchist
people's assemblies were to consist of disproportionate numbers of
rich, middle-aged, straight white men with the same university 
degrees hailing from the same major city, that'd be a sign that
either you're dealing with a massive demographic crisis, or somebody
has successfully managed to hack `/dev/urandom`. Over time, the
representative assemblies would be *truly* representative of the
people. There might still be a place for something like political
parties in a demarchy, but rather than compete for votes, they'd
have to compete for mindshare instead (and making empty promises ---
the favoured tactic of many an electoral politician --- would be
utterly ineffective), and they wouldn't command the kind of loyalty
they do in an electoral system, and representatives would be more
likely to have fruitful discussions as opposed to engaging in the
entirely predictable party-based trench warfare common to modern
parliaments. In a system based on sortition, significant economic
benefits to the representatives actually even seem *fair* compared
to similar benefits in one based on election: The representatives
are being asked to effectively put their personal lives and economic
activities on hold; compensating them well not only seems
reasonable, but also ensures that nonwealthy people from remote
regions *can* participate.

There are some major problems with the scheme too, of course, and I
think Van Reybrouck tends to gloss over them. It's possible (in
fact, over large enough timespans, practically *inevitable*) that
random selection would sometimes result in disastrous
misrepresentation, installing people into power whose views are
unrepresentative of the people (although, once again, I immediately
think about how the Danish population is consistently roughly
divided 50-50 on EU-related questions, but our elected
representatives are *massively*, disproportionately pro-EU). The
biggest problem, in my opinion, is the lack of feedback: Since
nobody ever has to try to get re-elected, there'd be no built-in
mechanism for people to nonviolently punish a bad representative
(short of filing a lawsuit of some kind).

Van Reybrouck proposes a kind of hybrid; a bicameral system with one
chamber chosen by election and one chosen by sortition --- which, 
historically, is much like the model practiced in ancient Athens, 
which used a combination of randomly selected lawmakers and court
officials, with elected experts (such as military strategists), with
relatively rapid rotation. Furthermore, rather than having a single, 
monolithic parliament-style assembly, he suggests a scheme in which
smaller domain-specific councils are continually formed to do some
political work and dissolved upon completion.

It's a book and a subject I need to think more about. I agree with
Van Reybrouck's criticism and I think his idea seems sensible, but
he presents it as something of a silver bullet, and it's usually a
good idea to be *very* skeptical of those.

**NOTE:** [Here](http://www.policy-network.net/pno_detail.aspx?ID=4760&title=Against-elections)'s a collection of excerpts translated to
English.
