%cdesc Dead tree eulogies
%nodate
%nodropcaps

Warning: Spoilers ahead.

Fiction
=======
* Anderson, Poul: [[Tau Zero]]
* Banks, Iain M.: [[Consider Phlebas]]
* Banks, Iain M.: [[The Player of Games]]
* Banks, Iain M.: [[Use of Weapons]]
* Banks, Iain M.: [[Excession]]
* Baxter, Stephen: [[Proxima]]
* Baxter, Stephen: [[Vacuum Diagrams]]
* Bester, Alfred: [[The Stars My Destination]]
* Blish, James: [[Cities in Flight]]
* Brin, David: [[Sundiver]]
* Brin, David: [[Startide Rising]]
* Brin, David: [[The Uplift War]]
* Brin, David: [[Existence]]
* Brin, David & Benford, Gregory: [[Heart of the Comet]]
* Brown, Eric: [[Helix]]
* Calvino, Italo: [[The Complete Cosmicomics]]
* Corey, James S.A.: [[Abaddon's Gate]]
* Doxiadis, Apostolos: [[Uncle Petros and Goldbach's Conjecture]]
* Egan, Greg: [[Diaspora]]
* Ellison, Harlan: [[I Have No Mouth And I Must Scream]]
* Herbert, Frank: [[Hellstrom's Hive]]
* Lem, Stanislaw: [[The Cyberiad]]
* Lowell, Nathan: [[Quarter Share]]
* Lowell, Nathan: [[Half Share]]
* McAuley, Paul: [[400 Billion Stars]]
* McAuley, Paul: [[Evening's Empires]]
* McDevitt, Jack: [[Engines of God]]
* McDevitt, Jack: [[Eternity Road]]
* Niven, Larry: [[Ringworld]]
* Reynolds, Alastair: [[Galactic North]]
* Robinson, Frank M.: [[The Dark Beyond the Stars]]
* Robinson, Kim Stanley: [[Shaman]]
* Smith, Cordwainer: [[The Rediscovery of Man]]
* Williams, Sean: [[Saturn Returns]]

Nonfiction
==========
* Allen, John R.: [[Anatomy of Lisp]]
* Appel, Andrew: [[Compiling with Continuations]]
* Arendt, Hannah: [[The Human Condition]]
* Diamond, Jared: [[Guns, Germs & Steel]]
* Dyens, Ollivier: [[Metal and Flesh]]
* Feynman, Richard: [[The Character of Physical Law]]
* Gordon, David George: [[The Secret World of Slugs & Snails]]
* Graham, Paul: [[On Lisp]]
* Greenblatt, Stephen: [[The Swerve]]
* Hawking, Stephen: [[A Brief History of Time]]
* Held, Lewis: [[How the Snake Lost its Legs]]
* Holland, John: [[Emergence]]
* Illich, Ivan: [[Tools for Conviviality]]
* Levy, Steven: [[Hackers, Heroes of the Information Revolution]]
* Marcuse, Herbert: [[One-Dimensional Man]]
* Paulos, John Allen: [[Once Upon a Number]]
* Schmidt, Stanley: [[Islands in the Sky]]
* Van Reybrouck, David: [[Against Elections]]
* Warren, Hank: [[Hacker's Delight]]
* Watts, Alan: [[Tao, The Watercourse Way]]
* Williams, Sam: [[Free as in Freedom]]
* Zammito, John H.: [[A Nice Derangement of Epistemes]]

___

If you'd like, you can have a look at my
[[Tsundoku Pile]].
