%date 2014-06-14
%author James Blish
%category [[Book Reviews]], [[Notebook]]
%rating 3

*Cities in Flight* is an omnibus volume of the four stories James Blish wrote
in this particular future history: *They Shall have Stars*, *A Life for the
Stars*, *Earthman, Come Home* and *A Clash of Cymbals / The Triumph of Time*.
Central to all four is two technological breakthroughs: The development of
effective antiagathics (effectively turning human beings clinically immortal),
and the *Spindizzy drive*, an antigravity mechanism and faster-than-light
propulsion system that can effectively turn any large object into a functional
spaceship. It is these two technologies that act as the foundation for the
eponymous flying cities: Entire cities have been fitted with spindizzies and
had their citizens turned immortal, and these then travel the spaceways looking
for odd jobs to do. The four stories follow the story of human spaceflight from
simple intra-system rocket travel to the final end of the universe, with the
main focus being on the star-flying exploits of the spindizzy-fitted New York.

The greatest strength of the cycle is the complexity and consistency
of the future history itself, for which Blish has taken inspiration
from [Oswald Spengler](http://en.wikipedia.org/wiki/Oswald_Spengler)'s
cyclic theory of history. In Spengler's view, a given cultural setting goes
through a sequence of distinct phases: The early, untamed culture with novel
spiritual, scientific and interpersonal insights, gradually ossifying into a
highly-organized, safe and stagnant civilization, and finally declining and
dying, supplanted by a new culture in its wild youth. In Blish's future history
(which was conceived in the height of the McCarthyist witch hunts), Western
civilization degenerates into a totalitarian police state in an attempt to
defend itself against the Soviet Union, but then gets effectively conquered
*by* the Soviet Union. Who could have thought that those guys were better at
running a totalitarian police state, right? This leads to the oppressively
stagnant Bureaucratic State - which, in *its* ruins, produces the culture of
the eponymous flying cities. The rise of the Okie culture (the flying cities)
is not even the last part of the historical cycle; many empires rise and fall
in *Cities in Flight*, and it's easily its incredibly rich history that makes
for the best reading in the series.

Its main weakness is the very uneven writing and the rather jumbled narrative -
as well as the rather weak characterization (and some mildly annoying 1950s
tropes). For instance, in the three main books (the first being essentially a
prequel, set *much* earlier), there is only one named female character. The
male lead falls in love with her for apparently no other reason than the fact
that she happens to be the only named female character. 

The four stories themselves are four very different stories, so they get their
own mini-reviews.

They Shall Have Stars
=====================
Set in 2018 (as imagined in the 1950s), this is essentially a very long
exposition dump that sets the stage for the rest of the series.  It deals with
the invention of the anti-agathic drugs and the Spindizzy drive, seen from the
perspectives of a military space pilot and a (Jupiter-based) construction
worker - the latter, in my opinion, being the most compelling character in the
story. Although the story itself was uncompelling and quite obviously dated
(apart from the Soviet Union still being active in 2018, it also features an
extinct civilization of Martians), it wasn't *bad* in the sense of, say,
[Ringworld](ringworld.html) or [Sundiver](sundiver.html), just ...  well,
*boring*.

By the way, this is - for better and worse - probably the most *dry* exposition
dump I have ever read. It even contained the mathematical formulae for
explaining the Spindizzy drives.

A Life For The Stars
====================
This one was probably the most cohesive of the bunch, and is essentially the
coming-of-age story of a young farmboy who gets press-ganged into service in
the city of Scranton-in-Flight, and who manages to migrate to the altogether
more pleasant city of New York and attain citizenship (and, thus, immortality).
It was actually a quite decent light read (I read it over the course of two bus
trips), but no literary masterpiece. Quite entertaining, though.

Earthman, Come Home
===================
Frequently considered the "main" story of the cycle, I unfortunately
found it easily the weakest. It reads like a hastily cobbled-together
jumble of peripherally-related short stories - which, I later found
out, that it actually *is*. It doesn't really tell a *story*, per se,
it's more a string of anecdotes that all happen to involve the same
characters. The events *connecting* the mini-stories seem quite
forced, and the lead character, mayor Amalfi, has entirely
incomprehensible motivations for doing most of the things he does
(except, of course, if he has the power of pre-intuiting what will
move along the plot). Entirely forgettable.

The Triumph of Time
===================
The final book in the cycle felt *very* rushed, and quite a lot of interesting
material is introduced and never really used (such as the nonhuman culture
named "The Web of Hercules", which ends up feeling under-exposed more than
mysterious). It deals with the end of the universe, which also happens to be
the beginning event of the *next* universe, and how some of the denizens of New
York attempt to claim control over how the next universe will develop.

The final verdict: Ho-hum. Not bad, per se, but also not great. I don't
understand why some regard it as a masterpiece.

As a rather useless aside: The *Ghostbusters* character Egon Spengler is, in
fact, named after Oswald Spengler.
