%nodate 
%date 2015-07-14

Datarama is unapologetically Web 1.0: The pages are all static HTML,
there are [[Datarama Ad Policy|no ads]], 
[[On Social Media Widgets|no social media integration]] widgets and 
[[No Comments|no commenting system]]. This is deliberate.

It's basically my public notebook, or "static wiki" if you will. Pages
get revised if and when I'm not happy with them, although I try to avoid
renaming URLs whenever possible --- doing so contributes directly to
link rot, and hence to the sum misery of the Universe. I write the pages
using [Vim](http://www.vim.org/), using the excellent
[Vimwiki](http://www.vim.org/scripts/script.php?script_id=2226) plugin
to link and navigate my source pages. Internal links are bidirectional,
so that each page has a "Related Pages" sidebar section with all pages
that link to it. The HTML is generated using [[Plutonium]], a
Scheme-based custom static HTML generator I wrote for the purpose. 

The entire source (including Markdown-formatted Plutonium files, 
CSS, fonts, SXML templates and image originals) used to generate the
site is 
[available on GitHub](https://github.com/datarama-dk/datarama.dk).

Visual Design & Typography
==========================
All the graphics and layout was done by me. I must hasten to note that
I'm not a graphic designer, nor do I play one on TV.

I based the current design on the basic idea of a mad scientist's lab
notes. The idea first came from the works of artist 
[Justin Amrhein](http://www.justinamrhein.com/), combined with my 
lifelong love of Golden Age science fiction and its latter-day
offspring, diesel- and atompunk -- this is also the origin of the
*Datarama* site title^[The title might also pay tribute to my favourite animated show.] and the logo. I've come to enjoy this design, and I
find that it reflects my personality and my preferred tone well --- in
fact, I ended up making a Linux desktop theme based on it.  The graph
paper in the background uses a base-8 system: I remain convinced that in
a sane world, we'd be counting in octal rather than decimal.

I use three fonts here: Body text is set in [[Epicure]], a slightly
modified version of [Linux Libertine](http://www.linuxlibertine.org/),
sidebar headings are set in
[Voltaire](http://www.fontsquirrel.com/fonts/voltaire), and code is set
in [Inconsolata
Hellenic](https://github.com/cosmix/Inconsolata-Hellenic) (I sometimes
use Greek letters in some of my more mathematically oriented code). All
are heavily subsetted to keep bandwidth demand low, and they were chosen
specifically to fit well with the retro-modernist visual theme.

The logo is an SVG image made in [Inkscape](https://inkscape.org/), and
the background paper textures are JPGs made in [GIMP](http://gimp.org/).

Web Standards
=============
Everybody loves W3C standards! All these pages should be valid
[HTML5](https://html5.validator.nu/?doc=http://datarama.dk) and
[CSS3](https://jigsaw.w3.org/css-validator/validator?uri=datarama.dk&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en).
If you find something that doesn't validate, or that looks wonky in 
your browser, please [let me know](mailto:skongshoj@gmail.com).

Copyright & Licensing
=====================
Unless otherwise noted, text and media files on `datarama.dk` is
licensed under a [[Content License|Creative Commons license]].
Computer programs are mostly 
under [[Software License|another license]], 
and the fonts (which weren't made by me) are all under the [SIL Open
Font License](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL).
