%date 2014-01-15
%author Iain M. Banks
%rating 3
%endnote Perhaps it needed a little more gravitas?
%category [[Book Reviews]], [[Notebook]]

*Consider Phlebas* is the first book in Iain M. Banks' masterful series about
the Culture, a high-tech, anarchist, gender egalitarian, sexually liberated,
queer-positive, inclusive, transhumanist, hedonistic post-scarcity utopia where
everybody has everything they want, ranging from designer living arrangements
to on-demand genetic and surgical modification. Oh, and it's all run by Minds;
artificial intelligences with intellectual prowess *far* above anything mere
meat-brain primates can match. The Minds are a total inversion of the classic
"AI overlord" trope: They're genuinely concerned with the well-being of the
Culture citizens, regard their citizens not as means to an end but as an end in
themselves, and handle the political and administrative duties in the Culture
so humans won't need to trouble themselves with it. They, incidentally, happen
to be much, much better at it than humans, too. Drudge work in the Culture is
handled by nonsentient machines; even their sentient robots are full citizens
with full civil rights.

Apart from short stories, this book was the first glimpse readers got into the
universe inhabited by the Culture.

Unfortunately, it's also a rather mediocre story.

The POV character, Horza, is an *enemy* of the Culture. He despises it as a
society run by machines, in which the living citizens are spoiled and pampered
- but deprived of true *meaning* in their lives. Life, Horza argues, is a
messy, chaotic affair, and the Culture - a society of absolute plenty, ruled by
machines - leads to stagnation and is therefore fundamentally anti-life.  And -
while Banks himself is obviously partial to the Culture - this is not an
entirely unreasonable view. The book tells the story of a particular
misadventure during his involvement in the war between the Culture and the
Idirans (a species of militaristic religious fanatics), where he fights as a
mercenary on the Idiran side. He's a Changer; an artificially created species
designed for work as spies - for which they have a number of very useful
natural abilities, not the least of which is the ability to (given some time)
perfectly assume the form of other humans. The misadventure itself pits Idiran
and Culture agents against each other in a rush to recover a crashed Mind from
a planet watched over by a near-omnipotent alien intelligence that even the
Culture is afraid of.

However, I found the episodic and disjointed plot rather annoying; many side
plots are opened without being properly closed, and the many episodes and
incidents sometimes barely tie together. It reads more like a collection of
(all good, mind you) short stories strung hastily together into a novel. 
I didn't like Horza - he came across as a surprisingly bland and
one-dimensional character (an impressive feat for a shape-changing fanatic
mercenary from a dying species), and I was annoyed by his large collection of
special abilities that suddenly come into play when needed; his Changer biology
often seemed like a rather lazy deus ex machina (although all his abilities are
explained in-depth and *well*, when he uses them). In fact, the characters 
generally seemed entirely uninteresting - with the sole exception of the
Culture drone Unaha-Closp, who I found the only really enjoyable character in
the book.

Ultimately, the bland characterization and the disjointed narrative made it
hard for me to *care*. I *love* the setting, the humour, the events themselves.
But unfortunately, reading *Consider Phlebas* ended up feeling a bit like a 
chore. I finished it slightly over a year ago, and didn't return to the Culture
universe until I decided to read the second book in that cycle (*The Player of
Games*) recently. 

*Consider Phlebas* is not a *bad* book by any means, and I still recommend
reading it, if only because it's what started out the *Culture* cycle.
