%nodate
%notitle
%nodropcaps
%lang da

Her samler jeg de af mine sider, som næppe er af nogen
interesse for folk, der ikke taler dansk. Det er et udtryk
for mine tendenser til storhedsvanvid at *alle* mine sider
ikke ligger her.

* [[Facts om Jakob Stegelmann]]
