%date 2014-01-10
%author Greg Egan
%category [[Book Reviews]], [[Notebook]]
%rating 5

The brief version: Fuckin' *awesome*.   
The more characteristically verbose version:   Greg Egan's *Diaspora* is the
best hard sf novel I've read in a very long time.  It's not exactly light
reading - but most hard sf isn't meant to be. 

Most of the POV characters are entirely made of sentient software. There are
three primary strains of human life in Egan's future history: The *fleshers*
(biological humans), the *gleisners* (software minds inhabiting robot bodies)
and the *citizens* (software minds, and digitized humans, living entirely
inside a supercomputer complex). The lead character is a citizen, and we
literally follow vis life from conception till ... well, for lack of a better
term, completion.

"Vis"? Yeah, most citizens "born" after the Introdus (the historical event where
much of humanity decided to be digitized and become citizens) don't have a
gender identity, and use the neutral pronouns ve/vis/ver. This might initially
seem jarring from a purely linguistic point of view (since those are not actual
English pronouns), but I quickly got used to it - particularly because it
*makes sense*; why would late-generation software entities feel in any way
connected to a social role that is so based on a biological concept that no
longer has any real meaning for them? There are a few citizen-"born" citizens
(including one main character) who *do* adopt a gender identity - their "mind
seeds" are based on algorithmically generated variations of what was originally
human minds, after all - but in general, citizens are asexual and genderless.

I had prepared myself for a book that would concern itself with conflicts
between these multiple ways of being human (eg. a "space opera"-ish story
similar to Bruce Sterling's Shaper/Mechanist works or Alastair Reynolds'
*Revelation Space* cycle), but there was actually remarkably little of that.
The gleisners and citizens mostly exist in a state of semi-friendly nonviolent
competition, and both are highly protective of the fleshers (who, however, tend
to be suspicious of nonbiologicals). It's strongly implied that there *has*
been violent conflicts between the fleshers and the nonbiological human life,
but by the time of the story, peace has reigned for decades. There is, in
fact, only one violent scene in the entire story.

The central crisis of the story isn't warfare or a villainous plot: It's an
astrophysical disaster, calling for scientists and explorers and diplomats, not
warriors and generals. It's about humanity, now divided into multiple distinct
posthumanities, trying to avoid extinction in the very long term. It's about
the grim realization that a mistaken view of theoretical physics led to an
extinction event that could have been predicted (and possibly avoided) using
better science. 

Consequently, a lot of the "action" isn't of the *spaceship shoot laser, BOOM!*
variety (with apologies to [the
Nerd](http://cinemassacre.com/category/avgn/avgnepisodes/)), but about people
exploring, making scientific discoveries and trying to make sense of those.
Consequently, there's a lot of strange multidimensional particle physics
speculation and "techtalk" (as is common in the genre) - which I enjoyed (even
though I admittedly found the fictional wormhole-based physics paradigm of
"Kozuch theory" *weird*). There's *also* personal tragedy, love, hate, regret,
failure, victory and joy. Most of which happens to be the tragedies, love
affairs, failures and victories of people made entirely out of software.

It is, in other words, an excellent hard science fiction book. I found myself
almost unable to put it down after I started reading it. Highly, highly
recommended.
