%date 2014-10-22
%rating 3
%category [[Book Reviews]], [[Notebook]]
%author Jack McDevitt

Jack McDevitt's *Engines of God* is --- much like [[Eternity Road]], the first
book of his I read --- a science fiction story about archaeological discovery.
Where *Eternity Road* was concerned with people in a post-apocalyptic future
society trying to make sense of the pre-apocalyptic world, *Engines of God* is
about xenoarchaeology --- the archaeological study of alien species. Set
roughly 200 years from now, its universe has faster than light
("transdimensional") travel and communication.

Earth is in a bad state, ravaged by environmental destruction and 
political upheaval. Minor colonies have been established elsewhere
in the solar system and in the larger galaxy, but planets with
human-friendly environments are *extremely* rare, and the beleaguered
population of Earth desperately needs more space. In fact, at the time
of our story, only three are known. Earth itself, the planet of Nok
(currently inhabited by a pre-industrial sapient alien species) and
the planet of Quraqua --- formerly the site of an advanced
civilization, now millennia extinct. The greatest archaeological
mystery of all, however, are the "Monuments" --- giant alien statues
of uncertain purpose, scattered across the galaxy. The first was
discovered on Saturn's moon Iapetus, right in our solar system.

The book is roughly divided into three acts. In all, the primary POV
character is Priscilla "Hutch" Hutchins, a pilot working for the
Academy, an international scientific institution. In each act, she's
backed up by various ensembles of other characters (some of whom
temporarily assume POV duty), most of whom are archaeologists,
researchers or (like herself) assistants to archaeologists and
researchers. 

In the first act, Hutch is tasked with assisting archaeological 
excavations on Quraqua, and with evacuating the archaeologists working
there. You see, shortly before the beginning of the story, Quraqua has
been handed over to a private corporation looking to terraform it ---
an effort that will make it hospitable to humans, but will also
destroy the archaeological remnants of its former inhabitants, the
Quraquat. For obvious reasons, Academy archaeologists are engaged in
a mad scramble to save as much evidence as they can before the ice
asteroids and icecap-melting atomic bombs ruin everything. The second
act is primarily concerned with the search for the Monument-Maker
homeworld, and the terrible misfortunes that befall the search crew, 
and the third is about what happens when they find said homeworld.

I'm not going to spoil anything, it's good enough that you should go
read it. 

Unfortunately, it features a rather anticlimactic (and apparently 
hurried) finale, and ... well, too many bad action scenes. Some of
them felt like an attempt to put a Hollywood action flick to paper.
A redeeming factor is that McDevitt (like he also did in *Eternity
Road*) very effectively avoids casting anybody as a redshirt. When 
people get killed, they're people with names, personalities and
backgrounds; people we've gotten to care about. In the one scene where
a freshly-introduced support character gets killed, another character
actually explicitly gets called out for treating it like a non-event.

I'd recommend it. I didn't like it quite as much as I liked *Eternity
Road*, but I'm definitely reading the rest of the series.
