%category [[Notebook]]

The traditional left vs. right spectrum isn't the only tool
for comparative political analysis --- the libertarian vs.
authoritarian spectrum given by the [Political
Compass](http://www.politicalcompass.org/) is one example
of an orthogonal axis, which has explanatory power in other
issues than economics and class affairs. Here is an example
of yet another axis, which I think can explain the
behaviour of certain political entities *not* easily
predicted by either left vs. right or authoritarian vs.
libertarian. As a running example I'll use Danish political
parties, but I believe the basic scheme also applies
internationally.  More on that later.

The *establishment bloc* consists of parties and politicians that
primarily view themselves as the mere administrators of an
established politico-economic systems. In terms of
classical ideologies, the Danish establishment bloc represents a
kind of hybrid between social democratism and conservatism,
and is best summed up by the slogan "the politics of 
necessity", often invoked by the former Social Democratic
minister of finance, Bjarne Corydon. The politics of
necessity is a distillation of the view that politicians 
ought not to act according to strong political principles, 
but rather according to purely pragmatic considerations
within an existing political framework. In Danish party 
politics, it consists of most of the older and larger 
parties, including the Social Democrats, the Social
Liberals, the Liberal Party, the Conservatives and the 
Socialist People's Party. 

The most prominent members of the establishment bloc are
professional career politicians, and the establishment bloc
has spawned an aristocratic politicians' class, which has
its own class interests. Thus, all parties within the
establishment bloc --- regardless of whether they're
nominally conservative, liberal or socialist --- have
certain common issues: They support lucrative wages and
pensions for politicians (while advocating austerity for
the common citizenry), mass surveillance of the people
(while advocating legal protection of politicians' rights
to conduct secret business), various large tax-financed
prestige projects, and centralization of power. In EU
countries, the establishment bloc largely supports EU
centralization, since it cements their purely
administrative role.

The *ideology bloc* consists of parties and politicians who
primarily view society from some grander, more or less
coherent vision. Usually, their primary project is some
fundamental restructuring (or abolition of) the system, and
in Denmark it's represented by the Unity List, the
Alternative, and Liberal Alliance. For obvious reasons, the
ideology bloc isn't popular in the politicians' class, but
it largely profits whenever the loathing of politicians
(and the antipathy towards the establishment) surges in the
common citizenry. Its members often have little financial
gain from their political work (whether because they pay
their earnings to the party treasury, or because they make
their money in private business), and it consistently works
*against* special privileges for the politicians' class and
*for* the legal rights of the general public. This is why
parties that fall on polar opposite ends of the left/right
spectrum (the Unity List and Liberal Alliance) will ally
with each other on legal policy and against politicians'
privileges, despite near-complete disagreement on economic
politics and general view of society.

There is a single *centre* party in Denmark, namely the
Danish People's Party. Its rhetorical style is unabashedly
ideology bloc (and, like the ideology bloc, it thrives on
general disgust with politicians), but in practice it often
supports the establishment bloc. This is because, like most
far-right populist parties, its central vision is to *keep*
the establishment, but to throw out foreigners and to
replace the people in power with some more "authentic"
"voices of the people" (eg. themselves). This is why such
parties will usually refuse any actual political
responsibilities (such as taking ministerial posts): This 
would force them to *openly* practice establishment
policies, which would alienate their voters.

In recent years, Danish politics has taken a major swing
away from the establishment bloc. In the general election
of 2015, all establishment parties except the Social
Democrats lost voters, and all the ideology parties (plus
the Danish People's Party) gained voters. 

Outside of the admittedly rather specific arena of Danish
politics, we can see similar currents in international 
politics. In Britain, Jeremy Corbyn (an ideology bloc
figure) took over leadership of Labour with a comfortable 
lead, ahead of the entire Labour establishment. In the US,
both Donald Trump and Bernie Sanders (both of whom are 
anti-establishment figures within their parties, even 
though they have widely different ideological views) are
currently dominating the debates.

Ideology bloc politicians may be either left, right or
centre, and may be either libertarian or authoritarian.
Some (eg. Trump) might even be part of the economic
establishment, but still find themselves in opposition to
the party-political establishment because they refuse to
play by the established rules.

Establishment bloc politicians may also fall on either side
of the left-right axis (although they tend to be closer to
the centre than ideology bloc politicians), although they -
for obvious reasons - tend towards some degree of
authoritarianism.
