%date 2014-07-19
%rating 4
%category [[Book Reviews]], [[Notebook]]
%author Jack McDevitt

*Eternity Road* is set about a millennium into the future, after a
virulent plague has decimated the Earth's population and utterly
destroyed high technological civilization. New cultures (and the
roving barbarian bands that are all but cliché in post-apocalyptic
fiction) have arisen, many of which take a both historical and 
mythological interest in "The Roadmakers" --- the long-dead
civilization nicknamed after their most ubiquitous and visible
leftover constructions. With access to only few pre-Plague books,
future scholars speculate about the spiritual significance of the
strange artifacts they find --- artifacts such as a variety of figures
made of a strange, flexible material that is neither metal nor wood,
or metal cylinders inscribed with the mystical incantation *Pepsi*,
all no doubt created by the Roadmakers for their religious rituals.
One such culture is the city-state of Illyria, a small republic in the
Mississippi valley, with a level of technology roughly comparable to
that of the 1700s. There are some anachronistic oddities --- they can
make firearms, but not steam engines or the printing press.

The story opens with the return of Karik Endine, a scholar who has
spent his career attempting to locate the fabled community of Haven
(reputed to be a surviving Roadmaker establishment or a storehouse of
Roadmaker knowledge), from an expedition that went disastrously wrong;
all other members were killed. With his death of natural causes nine
years later (a period in which he has been almost entirely reclusive,
reduced to a shadow of his former vibrant self), a number of sketches
from the expedition are found --- as is a handwritten copy of Mark
Twain's *A Connecticut Yankee in King Arthur's Court*.  Speculation
abounds that he did indeed find Haven, and a second expedition is
organized and launched --- both attempting to find Haven, and
attempting to find out what happened to the first expedition.

The expedition members are all interesting characters. Chaka, the 
sister of one of the dead first expedition members, Silas, an elderly
historian and Roadmaker expert, Quait, a younger scholar and military
conscript, Shannon, a woodsman, Avila, a fallen priestess (with medical
skills) and Flojian --- Karik's rather useless merchant son. They're 
all believable and well-written characters, and those of them who die
actually feel like *losses*. They're people with unfinished business
and personal development, so when they die, it's a story thread that
gets snipped off that *could* have led to interesting developments. In
this case, the survivors also have to deal with the loss of skills
that the expedition needs.

In a related note, in this kind of story it seems to me that it's
always the characters I find most *interesting* who get killed off.
Although this is obviously a bit annoying, it's also an indicator of
good storytelling. Death starts seeming downright *trivial* when the
characters reduce to Main Man, Leading Lady with Ensigns Four Shades
of Redshirt, and we all know right from the beginning who's going to
die along the way.

Good storytelling is, in fact, what saves *Eternity Road* from being
Just Another Post-Apocalyptic Adventure. We've seen all of it before:
The ruined cities, the roving bands of barbarians, the mythologization
of past culture, science and technology, the low-tech survivors. But
here, it's done *well*. The expedition has a *feel* more akin to an
old-timey archaeological expedition than to the tired "six brave
adventurers, who..." trope: All members are learned in Roadmaker lore,
except the wilderness survival expert and the medical expert. And yet,
the tone of the journey and the encounters along the way is oddly
reminiscent of Tolkien.

Definitely recommended. I'm going to have to read more McDevitt (who,
I understand, likes playing with future archaeology and
xenoarchaeology as themes in his works).
