%date 2014-01-02
%rating 4
%category [[Book Reviews]], [[Notebook]]
%author Paul McAuley

*Evening's Empires* is the fourth installation in Paul McAuley's cycle of
novels following *The Quiet War* (2008). It's also, in my opinion, the best of
the bunch so far. It's set roughly 500 years after the predecessor *In The
Mouth of The Whale* (2012), placing it some 1500 years after the events of *The
Quiet War* and *Gardens of the Sun* (2009). Like the two first stories (but 
unlike the third), it takes place in our solar system.

A quick digression: I really need some name for that universe. I think calling
it "The *Quiet War* Universe" both diminishes the later stories *and*
misrepresents it; not only are there many historical events in the cycle that
are at least as important as the Quiet War itself, the war is actually *ancient
history* by the time the third and fourth novels take place.

One of the great things about the backdrop is that this universe feels
lived-in. There's lots of interesting cultures (both human and posthuman), 
lots of interesting tech (the workings of which is often only sparsely
detailed). There's very little classical Magitech (in particular, there's no
faster-than-light travel), although there *are* lots of highly speculative
technologies (personality uploading, a bewildering array of futuristic genetic
engineering techniques, sentient AI, to name a few), most of which is concerned
with creating novel post-humanities.

It has a big and complicated history, and *Evening's Empires* is full of little
references to events both historical and contemporary, giving a distinct
impression that the universe doesn't revolve around our POV character; he's
just one of many people living in it. The other characters have their own
lives, and from the various small insights we're given into them, they could
easily have their own stories too. This is one of the things I've consistently
liked about all McAuley's works, and is also one of the things I particularly
enjoy about Alastair Reynolds' *Revelation Space* cycle and Iain M. Banks'
*Culture* stories.

The historical backdrop has a distinct "late Dark Ages" feel. The True Empire
(which feels sort of like an analogue of the Roman Empire) declined and fell,
and a menagerie of both human and posthuman successor cultures have risen and
fallen since. Rather than large nation-states, the predominant mode of social
organization has become clans, small communes, city-states and religious
conclaves. Intellectuals aren't as much making new discoveries as picking
through the ruins of the fallen empire of yesteryear. I enjoy the fact that
we've never actually seen the True Empire up close in any of the novels: The
two first novels are from long before the empire was established, the third
deals with a remote True Empire colony, and the fourth is set after the empire
collapsed. Again - this universe feels like it has an actual *history*.

Unlike the three earlier novels in this backdrop; this one has only a single
POV character - the others had multiple separate POV characters, sometimes with
only very little interaction between them. This, in my opinion, allowed it to
rise above its already-impressive predecessors. This is not only another trip
to a compelling and detailed future (as the three others): It's also the
coming-of-age story of Gajananvihari Pilot, whose family was murdered and its
spaceship hijacked immediately prior to the events of the novel. Hari is a
great protagonist from a storytelling perspective: He has lived nearly his
entire life on board his family spaceship, and his knowledge of the universe
outside the family ship and business is about as limited as that of the reader
(allowing the usual SF exposition dumps to take place in-character without
breaking the story flow). The story is also a quest for revenge and a
scientific mystery (dealing with the aftermath of the events of *In The Mouth
of the Whale*), and manages to blend space opera and hard SF in just the right
proportions (in fact, this is largely why I love the works of both Paul McAuley
and Alastair Reynolds so much). There's less hard science exposition than in
the two first books - possibly because much of the science in those dealt with
biology, and McAuley himself is a biologist by education.

A minor nice touch: There's lots of references to other SF writers throughout,
including at least Asimov, Clarke and Silverberg (which makes a lot of sense:
Why *wouldn't* future space colonists pay homage to old science fiction authors
they might have read once?). There's even a clever Tolkien reference near the
end.

Easily my favourite installation in McAuley's series so far - and his is one of
my favourite SF series to date, so that's high praise. Highly recommended.

An aside: McAuley has revealed that his next novel *isn't* set in this
universe, but has also hinted that he will probably return to it later. I'm
already looking forward to my next visit in it.
