%date 2014-12-20
%author Iain M. Banks
%rating 4
%endnote This review encountered an endnote rather in the same way as a civilizationa encounters an Outside Context Problem.

Once again I've read a Culture novel, and this time, it deals with an incident
in which the Culture encounters an Outside Context Problem -- an Outside
Context Problem, of course, being "the sort of thing most civilisations
encountered just once, and which they tended to encounter rather in the same
way a sentence encountered a full stop". Have I mentioned that Banks' humour
reminds me of Douglas Adams?

In this case, a splinter group of the Culture has discovered a Big Dumb Object
- a large, perfect black-body sphere which happens to be about 50 times older
then the universe itself. Needless to say, this *completely* turns the tables
on the Culture.  

In most of their stories, the enlightened, anarchist, post-scarcity, sexually
liberated utopian Culture citizens are pitted against various hostile alien
civilizations that are *by far* their technical and scientific inferiors ---
and which also happen to often be almost cartoonishly cruel, sadistic and
stupid. *Excession* does, in fact, also include such a rival civilization ---
one which refers to *itself* as The Affront, and which takes such a delight in
causing suffering and misery that their domesticated animals are genetically
engineered to suffer more and be more acutely aware of their suffering. Their
society is a strict patriarchy, in which a small ruling elite of elder males
brutally oppress a large population of females and castrated lower-caste males.

One might wonder how such a ridiculous society could ever rise to the point of
mastering long-distance space flight and genetic engineering in the first place
--- and the answer, of course, is that they didn't.  They were uplifted by an
elder species.

Right, so we have the Culture, a bizarre alien artifact that's older than the
universe, and a murderous villain species. How do all those pieces fit
together? Well... here's where it gets complicated. The story follows *many*
plot threads, and unfortunately quickly gets rather confusing. The major thread
deals with the discovery of the Excession (aforementioned artifact), and with
how the Culture and the Affront both want property rights over it. However,
what is happening *behind the scenes* is at least as important: A cabal of
Culture Minds (the AIs that manage their entire civilization) have decided to
exploit the discovery into goading the Affront into declaring war on the
Culture --- in no small part because that particular conspiracy of Minds want
nothing more than to overthrow the Affront. And thus, in this story, most of
the major characters are AIs with rather silly names. The primary biological
character is an insufferably smug diplomat who represents the Culture on the
Affront homeworld, and who *idealizes* his hosts. 

It's a *weird* story. Of the Culture books I've read so far, it is the one that
most effectively gives me an insight into the *Minds* of the Culture --- to the
extent that it's possible to convey what a being a trillion times more
intelligent than me might be like.

Although I liked it overall, I unfortunately found the many separate plot
threads confusing and mostly unnecessary. Still, I'd definitely recommend it.
