%date 2014-10-05
%author David Brin
%rating 4

I [[Sundiver|haven't]] [[Startide Rising|exactly]] [[The Uplift War|been]] [[Heart
of the Comet|impressed]] with what I've read by Brin so far --- *particularly*
those of his works that for incomprehensible reasons get hailed as great
science fiction masterpieces. However, he also writes [really interesting blog
posts](http://www.salon.com/1999/06/15/brin_main/) in which he absolutely
*nails* everything that's *good* and *right* about science fiction. So why did
his books suck so much? 

Well... it occurred to me that the Brin I've read has all been his 80's stuff,
so perhaps my judgment of him hasn't really been fair. And so I went into his
most recent work, *Existence* (2012), with a combination of dread (please,
*please*, Mr. Brin, can we have a book in which you don't plant demented images
of a [[Uplift War|chimpanzee lap dance]] or [[Startide Rising|dolphin
interspecies sex predators]] in my already tortured mind?  *I code in
JavaScript*, I have enough eldritch horrors stealing my sleep already!) and
curiosity.

This one, however, is actually *good*. 

It does have its flaws. Stylistically, Brin's writing hasn't changed
much since *Uplift*: Most of the characters think and speak as if they
have cybernetic thesaurus implants, and he sure likes him some
exclamation marks!!! Some of the names are hard to take seriously 
(they had a nuclear terrorism event, and named it *Awfulday*?). More
substantially, nearly the first third of the book is basically a giant
intro, which seems to primarily exist to deliver exposition on the
future world. There are entire chapters, in fact, *entire subplots*,
that seem to have no bearing on the actual story. Like in *The Uplift
War*, we have *lots* of POV characters, and we switch back and forth
between them in quick succession --- to such an extent that it's easy
to lose track of them. Cliffhangers are overused to the extent that
they become a source of annoyance, rather than suspense.

Also. Dolphins. *What is it with Brin and those fucking dolphins?* 
There's a subplot involving dolphins that *goes nowhere* and adds
absolutely nothing to the story --- it seemed to be in there solely
because Brin likes dolphins, or tries to capitalize on his reputation
as "that guy who writes sf stories about creepy dolphin sex
predators". To be fair, these dolphins didn't *do* anything creepy
(although, hilariously, they did try to teach a human to speak dolphin
by rewarding him with fish when he responded correctly), and I'd be a
world-class asshole if I assumed them to be creepy sex predators just
because they happen to be dolphins in a David Brin story. `#notalldolphins`

The setting is a quite plausible near-future scenario: It's vaguely
post-cyberpunkish, with environmental disaster, nuclear terrorism, 
all-encompassing media surveillance-from-below (there's no Big Brother
state, rather everyone is watching everyone else using
Internet-connected eyeglasses, drones and similar gadgetry). There's
some space industry, but nobody permanently lives off-Earth. Political
factions are constantly squabbling --- lurking behind the scenes of 
the chaotic landscape is a conspiracy of ultra-rich conservatives,
poised to slam the brakes on scientific progress that they have no
control over (and less understanding of). There's an "autism
epidemic", and autistic activists are railing against being classified
as defective. Strange genetic experiments are carried out by both
companies, private researchers and political activists. The world has
been utterly consumed by social networking.

But on the other hand, people are flying Zeppelins, so there's that.

It's a world that I can certainly imagine growing from ours. It's also
one I'm very, *very* grateful I don't live in. Into this world comes
an alien artifact --- an orbital debris collector accidentally finds
a little crystal object, containing the uploaded personalities of a
community of alien beings. It is the implications of this find that
drives the main story of the book and concept of the book.

That story --- when it actually gets told --- is *fantastic*. Utterly
fantastic. Top-class science fiction. It's difficult to describe
much of it without destroying everything with spoilers, but the
ultra-condensed version is that it's about the galactic-scale
evolutionary competition of intelligence and civilization (and the
resolution of the Fermi paradox). It actually does the grandiose title
of the book justice; it gives an extremely imaginative and detailed
vision of the cycle of "life" (or, rather, existence) of technological
civilizations --- including how these can self-destruct, or indeed how
they can conceptually exist forever. Particularly intriguing is that
it *primarily* focuses on the implications of the means by which
civilizations (and even *individuals*) can maintain perpetual
existence.

The final third of the book primarily concerns teams of
xenoarchaeologists (including humans, cyborgs, neanderthals and AIs
and, thankfully, no dolphins) --- exploring the remains of alien
civilizations, and beginning the political and scientific process to
decide the future of humanity. If this part had comprised the majority
of the book and the rest condensed into the intro it feels like it
should rightfully have been, I'd have forgiven this book all its flaws
and probably considered it among the best sf reads of my year
(although it'd probably still be behind [[Diaspora]]).

As it is, I can still definitely recommend it. It's a good book. If
you slog through the first (boring and meandering) part of it and get
to the good stuff, there's a shiny reward for you. It's by far the
best Brin I've read so far.
