%nodropcaps
%date 2015-08-10
%lang da

<div style="margin-bottom:24px;text-align:center;font-size:14px;font-style:italic;">
<img src="files/stegelmann.jpg" width="546" /> Selvportræt af
Jakob Stegelmann, tegnet m. Deluxe Paint III på Amiga 500.
</div>

___

Jakob Stegelmanns computer har ikke nogen disk; han kan huske
indholdet af alle sine filer i binær. Når han skal bruge en
fil taster han den bare ind igen. Han taster iøvrigt
hurtigere end en SSD kan læse, så faktisk sparer han tid.

___

Jakob Stegelmann har altid ret. Faktisk peger nye opdagelser
fra kvantefysikken på at hvis Jakob Stegelmann hypotetisk set
tog fejl, så ville tid-rum-kontinuumet vride sig sammen og
universet ville omorganisere sig med tilbagevirkende kraft,
så han alligevel har ret.

___

Engang indgik Jakob Stegelmann og Superman et væddemål om
hvem der var stærkest. Taberen skulle gå med sine underbukser
udenpå tøjet.

___

Darth Vader ved det ikke, men faktisk er det Jakob
Stegelmann, der er Luke Skywalkers far.

___

Engang stillede Gandalf op mod Jakob Stegelmann i en dyst på
viden.

Det er derfor, Gandalf altid går med en høj grå dosmerhue.

___

Grunden til at Gandalf ikke går med hat efter sin
tilbagekomst efter faldet med balroggen, er at Jakob
Stegelmann mente han havde fortjent en level up. Til gengæld
mistede Gandalfs hår resten af sin farve, da han efter sin
Balrog-fight ankom til Valinors bredder og fik øje på Jakob
Stegelmann der stod og ventede på ham.

___

Den oprindelige arbejdstitel på Christopher Nolans film "The
Dark Knight" var "Et par dage i Jakob Stegelmanns liv".

___

Hvem ville vinde hvis Jakob Stegelmann mødte Chuck Norris
in-game?

Det er et tåbeligt spørgsmål, der ca. svarer til "hvem ville
vinde i en episk deathmatch mellem Optimus Prime og Finn
Nørbygaard".

___

Grunden til at computerspil ikke automatisk gennemfører sig
selv når Jakob Stegelmann sætter sig ved skærmen er at de
ikke tør kede ham.

___

Jakob Stegelmann har gennemført World of Warcraft.

På en 8-bit Nintendo-konsol.

Det tog ham en formiddag.

___

Grahams tal, som er så stort at det ikke ville kunne skrives
i det observerbare univers selv hvis man kunne skrive et
ciffer på hver eneste elementarpartikel (selv hvis man
skriver i opløftningsnotation, og selv hvis hvert ciffer er 1
Planck-volumen stort), blev oprindeligt lavet som en måde at
approksimere Jakob Stegelmanns IQ.

Ved et pudsigt sammentræf er det også hans high score i
Tetris.

___

Jakob Stegelmann kender alle snydekoder til alle spil,
inklusive skak, fodbold, kryds-og-bolle og vandpolo. Ligesom
undertegnede samler han nemlig på ubrugelig viden.

___

Da han var 4 år gammel byggede Jakob Stegelmann en fuldt
fungerende TARDIS i Lego - i naturlig størrelse.

___

Jakob Stegelmann bruger aldrig God Mode i computerspil.  Gud
bruger dog nogle gange Jakob Stegelmann-Mode.

___

NSA læser dine mails.

Jakob Stegelmann plejede at læse NSAs mails, men det gider
han ikke mere --- de skriver aldrig noget om tegneserier,
computerspil eller Star Wars.

___

Nogle mennesker bruger passwords.

Nogle mennesker bruger passphrases.

Jakob Stegelmann bruger et episk passmanuskript på 721 sider,
der indeholder et storslået screenplay til en film hvori
klimakset er en kolossal deathmatch mellem Godzilla, Optimus
Prime, Indiana Jones, Kejser Palpatine, Superman, Doktoren,
Lex Luthor, samtlige X-Men, Sauron, Egon Olsen, Dr. Manhattan
og hele besætningen fra USS Enterprise NCC-1701. At indspille
den ville kræve et special effects-budget der ca. svarer til
Kinas bruttonationalprodukt.

___

Engang stillede Jakob Stegelmann op mod hele Dalek-imperiet
i en Tekken-dyst.

Taberen skulle bære rundt på en lokumssvupper resten af sine
dage.

___

I fysikken er Planck-tiden defineret som den tid, det tager
lyset at bevæge sig 1 Planck-afstand, og betragtes af nogle
fysikere som det kortest mulige tidsinterval.

Det er også hvor lang tid Chuck Norris kunne klare sig mod
Jakob Stegelmann i et spil Street Fighter II.

Han brugte alle sine continues.
