%author Alastair Reynolds
%date 2015-07-13
%category [[Book Reviews]], [[Notebook]]
%rating 4

Alastair Reynolds' *Galactic North* is a collection of short stories set 
in the [[Revelation Space Universe]]. The stories are ordered by
in-universe chronology, with the first story (*Great Wall of Mars*) set
around the year 2200, and the titular *Galactic North* extending to about
40.000 years in the future. Written between 1990 and 2006, most of the 
stories have made earlier appearances in sf magazines.

This was in fact the first Reynolds material I ever read. I picked it up
in *Nexus*, a fine purveyor of comics, sf books, RPG material and 
nerd paraphernalia in Reykjavik, during a 2009 vacation in Iceland. I found
the back cover blurb irresistible: 

> Centuries from now, solidarity stretches thin as humanity spreads past
> the solar system and to the nearest stars. Technology has produced
> powerful new tools -- but lethal risk will always accompany great
> advancement.
> 
> And without foresight, opposing groups may fracture multiple worlds.
> Between the Demarchists and the Conjoiners, the basic right to expand
> human intelligence beyond its natural limits has become a war-worthy
> cause. Only vast lighthugger starships -- manned by the panicky and 
> paranoid Ultras -- bind these squabbling colonies together. 
>
> The rich get richer. And everyone tries not to think about the worrying
> number of extinct alien civilizations turning up on the outer reaches of
> settled space...because who's to say that humanity won't be next?

It didn't disappoint. I inhaled the book from the passenger seat during an
extended drive across Iceland, and finished it in a single marathon
sitting. I then proceeded to buy the original *Revelation Space* trilogy
(as well as *Pushing Ice*) once I got back to Denmark. And now I've re-read it.

The *Revelation Space* setting is a strange mix between hard(ish) science 
fiction and space opera. Humanity has turned into a severely 
fractured spacefaring species. The two primary factions are the Demarchists
and the Conjoiners. The *Demarchists* practice a form of radical direct
democracy, in which voting on political issues is pervasive, perpetual,
carried out by cybernetic implant linked to gigantic polling computers, and
mostly a subconscious process for its citizens. The *Conjoiners* are a true
hive mind, using cybernetic implants to link their minds into a collective
consciousness. The *Ultras* mentioned in the blurb are independent
near-lightspeed starship crews, most of whom have so extensive cybernetic
modifications that they are barely recognizable as human, and do not form a
cohesive political faction on their own (in fact, one story is specifically
about a violent battle between Ultra crews). There are no active alien
cultures at near-human levels of development, and there is no
faster-than-light travel.

Here are some brief unspoilered introductions to the stories.

1. *Great Wall of Mars* (2205): The first story introduces Nevil Clavain, a
   recurring character who also has an appearance in the main 
   *Revelation Space* cycle. It concerns the breakdown of negotiations
   between the original Conjoiner nest on Mars and the Coalition of Neural
   Purity, a conservative faction primarily concerned with fighting the
   Conjoiners (and maintaining an uneasy peace with the early Demarchists,
   who live in the Outer Solar System).
2. *Glacial* (2217): Another Clavain story, set after the Conjoiners have
   fled the Solar System and come upon a collapsed American colony on an
   icy planet around the star Ross 248. The story is essentially a science
   fiction murder mystery: All the colonists are centuries dead, but it 
   appears foul play may have been involved.
3. *A Spy in Europa* (2330): Back in our solar system, this is an espionage
   and intrigue thriller involving an operative from *Gilgamesh Isis*,
   an anti-Demarchist faction that doesn't survive into the *Revelation
   Space* era. Double-crossing, triple-crossing and backstabbery ensues!
   Also, mutant fish-men.
4. *Weather* (2358): Set on an Ultra ship under attack by an Ultra pirate
   crew, sheer dumb luck makes the difference in the battle and our Ultra
   protagonists pick through the carcass of their adversary. They find an
   abducted Conjoiner girl enslaved by the pirates, and take her aboard 
   despite the anti-Conjoiner sentiment of their ancient Captain (who was
   around for the events of the first story). 
5. *Dilation Sleep* (2513-2540): One question every science fiction writer
   who doesn't want to just write [[Diaspora|stories about software]] is
   why anybody would go through the effort of launching canned apes into 
   space instead of just using AI-driven starships. In this story, we
   follow a non-Ultra starship, on which the crew works as "heuristic
   resources", assistants to the ship computer, on a ship carrying Demarchy
   citizens fleeing the Melding Plague (a cybernetic pestilence that causes 
   the near-ubiquitous cyberimplants to turn into a malignant, cancerous
   miniature grey goo). The story follows a medical crisis on board --
   three guesses which illness somebody caught.
6. *Grafenwalder's Bestiary* (2540): Set after the end of the Plague, but
   with its effects still fresh in memory, this story follows an
   ultra-wealthy security systems specialist, collecting human and nonhuman
   "monsters" in his personal zoo to exhibit to his friends in the local 
   bourgeoisie. The story follows his attempts to get hold of one of the 
   mutant fish-men from the third story --- and sheds some light on the 
   bizarre upper echelons of post-plague Demarchy society.
7. *Nightingale* (2600): My least favourite story from the collection, 
   this one involves a small commando raid trying to extract a wanted war
   criminal apparently hiding on a sentient hospital ship.
8. *Galactic North* (2303-40000): The final and titular story concerns
   another captain (transporting frozen passengers) attacked and tortured
   by Ultra pirates. This kicks off a millennia-long revenge plot
   (near-lightspeed time dilation makes for some crazy timelines), taking
   place while the galaxy is slowly being destroyed by rogue terraforming
   devices.

All in all, highly recommended! It can be read even if you know nothing
about *Revelation Space*, although re-reading it (after having read the
rest of the series), I can see that there were some (non-essential)
references I missed on my first reading. I'll probably re-read the whole
series soon; it's some of my favourite science fiction.
