%date 2015-08-09

We all know that there's a huge plot hole in *The Lord of the Rings*:
Why didn't Gandalf just fly an Eagle to Mordor and destroy the One
Ring? [HISHE](https://www.youtube.com/user/HISHEdotcom/videos) 
did one of their first videos about it, and there's an elaborate
[fan theory](http://np.reddit.com/r/FanTheories/comments/130it2/lord_of_the_rings_a_theory_about_the_eagle_plot/)
speculating that Gandalf might actually have been
planning to do exactly that.

<div style="text-align:center;margin-bottom:24px"><iframe width="460" height="260" src="https://www.youtube.com/embed/1yqVD0swvWU" frameborder="0" allowfullscreen></iframe></div>

Well, why *didn't* he? It turns out there are several good reasons.

The dull, out-of-universe explanation is, obviously, that it'd make
for a boring story, and Tolkien wanted to tell a greater epic. It's
doubtful that Tolkien even *thought* of the eagle plan, though. He
doesn't address it in any of his letters, and if he was aware of the
plot hole while writing *The Fellowship of the Ring*, he'd certainly
have somebody suggest it at the Council of Elrond, only to have the
idea officially shot down by Gandalf or Elrond. 

But, as it turns out, it'd probably be a *bad idea*, even
in-universe.

The eagles are not subject to Gandalf's command. As Maiar of Manwë,
they are in fact his equals. In *The Hobbit*, it's made very clear
that they help him out in that story not because he orders them to,
but because they *owe him a favour*: He once saved their leader,
Gwaihir the Windlord, from a poisoned arrow. It's entirely possible
that they would refuse. However, given that they're on the same side
as Gandalf (and enthusiastically join the fight against Sauron's
forces later on), they'd probably only do so if they had good reasons
to. However...

Ring Corruption
===============
With the sole exception of Tom Bombadil, the One Ring's corrupting
influence on creatures appears to be proportional to how powerful
they are. Gandalf doesn't even dare touch it. The one time he handles
it (in *Fellowship*), he does so using tongs. Likewise, Galadriel
avoids touching it, and even its *presence* is
enough to create a temptation she has to actively resist. This is
precisely why Gandalf is confident in entrusting it to a hobbit ---
hobbits are generally humble beings without any major magical
abilities or lust for power; they typically don't even *want*
influence on the greater events of the world. They're not immune (as
Sméagol's sad story attests), but their nature makes them less
vulnerable to its corrupting influence than humans, and *especially*
Maiar and high elven royalty. The eagles, also being Maiar, would
almost certainly be corrupted and turn to evil if they were given the
ring. They'd most likely be aware of this (having been actively
fighting Morgoth's agents since the First Age). Of course, they 
might be able to withstand its influence if they were merely tasked
with carrying a hobbit rider.

Mordor's Air Defenses
=====================
We know, from *The Hobbit*, that the Eagles avoid going near Laketown
(and human territory in general) because they're afraid of archers.
They've been shot at in the past while attempting to raid livestock, 
and this in fact nearly claimed the life of Gwaihir, their leader.
The archers of Laketown are mostly shepherds and fishermen with
simple bows, whereas Sauron has thousands of highly-trained orc,
Easterling and Haradrim military archers stationed in Mordor.
Furthermore, Sauron has his own air force, in the form of the fell
beasts, notably used as mounts by the Nazgûl.  It's entirely likely
that an eagle could defeat a fell beast in a fight (in the movie
adaptation of *Return of the King*, we actually *see* an eagle
defeating a beast-mounted Nazgûl), but a single eagle would be hard
pressed to handle a group of them. This would necessitate sending an
entire group of eagles, and that would effectively preclude a stealth
mission. Without the element of stealth (and Sauron would be able to
spot a squadron of giant eagles from half a country away), they'd be
forced to deal with the entire massed forces of Sauron's archers and
however many fell beasts are at his command^[There's an entire region of Mordor named simply "The Vale of the Fell Beasts", so it seems likely that there were more of them than the Nazgûl's mounts]. We know, for a fact, that they're both afraid of archers, and
sufficiently vulnerable to archery that they've been harmed by
archers in the past.

On the other hand, we also know that the Eagles can fly at high
enough altitudes that even Aragorn's superhuman eyesight isn't able
to clearly see Gwaihir flying overhead in *The Two Towers*. An
English longbow has a maximum range of about 350 meters, and the bows
used by orcs, Easterlings and Haradrim would probably be considerably
shorter-ranged than that --- particularly those of the Haradrim and
the Easterlings (noted as by far the deadlier of Sauron's archers),
who used short compound bows, and the latter of whom even favoured
horse archery. So if the eagles could just stay at a very high
altitude, then they should be safe from archers (and only have to
deal with fell beast interceptors). Well...

Approaching The Cracks of Doom
==============================
That HISHE video aside, throwing the ring into the caldera of Mt.
Doom explicitly isn't enough to destroy it, it has to be thrown into
the Cracks of Doom, the underground workshop where the ring was
forged. The only entry to the Cracks of Doom is a long narrow tunnel 
bored into the mountainside. In other words, an eagle *couldn't* 
simply drop the ring from high above, it'd have to land and set a
rider into the tunnel. This would require it to give up the
aforementioned altitude advantage, and it'd be vulnerable to any 
archers Sauron had stationed at the mountain.

In neither book nor film adaptation did we see any archers on the 
mountain, and there likely weren't any. That's because Sauron wasn't
aware that anybody was trying to get to Mt. Doom --- he *was* aware
that two hobbits had infiltrated Mordor, but (given what the Mouth of
Sauron says during the parlay before the Battle of the Black Gate),
he apparently believed them to be on an espionage mission. If,
instead, he had spotted a squadron of giant eagle Maiar on a course 
for Mt. Doom, he'd have an entirely different response than he did to
three lesser humanoids attempting to sneak into his lands.

When the eagles *did* enter Mordor and fly to Mt. Doom (on their 
final rescue mission to fetch Frodo and Sam), they did so only after
Sauron himself and all of his armies had been defeated, after the
destruction of the One Ring.

Conclusion
==========
Even if Gandalf had asked the Eagles to fly to Mordor and destroy the
Ring, they'd probably have refused, and they'd be right to.


