%date 2015-03-14
%author Jared Diamond
%category [[Book Reviews]], [[Notebook]]
%rating 5
%endnote In a parallel reality, an Aztec computer scientist just reviewed a book about why Eurasia fell behind due to a crippling lack of corn, chili and alpacas.

In 1533, Spanish conquistador Francisco Pizarro and Inca emperor Atahualpa met
each other in the Andean town of Cajamarca, where the emperor was resting.
Pizarro had about 180 Spanish adventurers with
[arquebus](http://en.wikipedia.org/wiki/Arquebus)es, rapiers, steel body armour
and horses. Atahualpa had 80.000 Inca warriors armed with copper and stone
axes, spears, clubs and slings; he was resting after the final battle of a
civil war that had raged after a terrible smallpox epidemic had decimated
the Inca empire and killed Atahualpa's father with most of his court. Within
an hour of Pizarro and Atahualpa meeting each other, Atahualpa was in chains
among piles of dead Inca warriors, without a single Spanish casualty.  Why was
it that it was Pizarro who captured (and later murdered) Atahualpa, and not
some Inca adventurer who sailed to Europe and captured King Charles I after
rampaging his way through the disease-ridden ruins of Europe? This is the
question Jared Diamond sets out to answer in *Guns, Germs & Steel*.

The obvious answer is to list the *proximate* causes: The Incas didn't have
oceangoing ships, so they couldn't sail to Spain. They didn't have firearms or
steel armour, so even if they could go to Europe, their copper age
military equipment would have been useless against the Europeans' firepower.
They had no resistance to European pathogens like smallpox and influenza, so
even if they *had* both guns and ships, their invasion would have ended in much
the same way as the ill-fated Martian invasion from *War of the Worlds*. To add
insult to injury, they themselves didn't carry any pathogens that could have
wiped out millions of Europeans. That answer, however, doesn't address the
*ultimate* cause: Why was it that the Europeans had all those things, and their
contemporary Incas (or Australian Aborigines, African Khoisan and New Guinea
highlanders) didn't? 

Diamond frames the book in terms of a question once asked to him by the New
Guinea politician [Yali](http://en.wikipedia.org/wiki/Yali_(politician)): "Why
is it that white people have so much cargo and black people have so little?".
He quickly dismisses racist attempts at an answer. His own experiences working
in New Guinea has given him ample evidence that native New Guineans are just as
intelligent as Europeans, and many of them even more adaptable. He presents a
number of historical examples of non-European people using acquired technology
to have conquests just as one-sided as that of the Spanish vs. the Incas (such
as when musket-wielding Maoris from New Zealand subjugated the stone age
Moriori hunter-gatherers of the Chatham islands). Diamond's answer is that the
ultimate reason for the global division into haves and have-nots has little to
do with the *people* --- rather, it has to do with *places*, with biogeography. 

In brief (and in simplified form), the argument goes as follows.

1. Hunter-gatherers are unable to support large and dense populations, because
   they are unable to generate a large storable surplus of calories.
2. The best sites for early agriculture have Mediterranean climates. This is
   because Mediterranean climates favour annual plants (due to the winter
   rains), and the best survival tactics for annual plants (growing very large,
   protein-rich seeds) also make them uniquely well-suited for domestication
   and consumption by humans. Furthermore, a mostly dry climate makes it easy
   to store food.
3. Domestic animals can, depending on the animal, provide a stable supply of 
   meat, milk, muscle power (further improving food production efficiency), 
   swift transportation and military assault vehicles. 
4. Societies with a safe food surplus can support specialists not directly
   involved with securing the food supply, such as artisans and bureaucrats. 
5. Such specialists lead to more complex social systems and technological
   innovation (weapons, metallurgy, literacy, etc.).
6. Since domestic animals transmit zoonotic diseases, and diseases spread much
   more rapidly in dense populations than in sparse ones, citizens of dense
   societies with domestic animals will eventually develop immunities to a wide
   range of pathogens (albeit with terrible casualties along the way).
7. Societies with lots of easily-reachable neighbours at roughly the same level
   of technical sophistication will have *even higher* levels of technical
   development, because they also have access to all their neighbours' ideas
   (whether by trading for them, reverse engineering them, or stealing them).

In other words, the question of how to get guns, germs and steel reduces to the
slightly less dramatic question of how to get books, bread and cheese.

Eurasians (specifically Mesopotamians) were the first to get any of those
things, and this is precisely because they got dealt a geographically fortunate
hand. The Mediterranean-climate zone in Eurasia (plus North Africa) covers a
*much* larger land area than the corresponding zones in California, Chile,
South Africa and Southwest Australia. Of all the world's most protein-rich
self-pollinating plants (which are the easiest to domesticate, because they
won't lose desirable genetic characteristics to cross-pollination with wild
relatives), more come from Mesopotamia alone than from Australia, Sub-Saharan
Africa and the Americas *combined* (in fact, the only successfully domesticated
plant from Australia is the [Macadamia
nut](http://en.wikipedia.org/wiki/Macadamia)). Of Earth's 100+ large mammals,
only 14 were successfully domesticated, and only one of those (the llama) is
*not* native to the Old World. Both crops, domestic animals *and* technical
ideas easily diffused across Eurasia, because the continent's primary axis is
east-west (meaning that there will be much less climate variation compared to,
say, the north-south axis of Africa or the Americas).

I'm not a historian (and [neither is Jared
Diamond](http://en.wikipedia.org/wiki/Jared_Diamond)), and am not in a position
to judge the veracity of Diamond's factual claims. His argument seems, in broad
strokes, compelling to an interested and reasonably well-read layman. His
writing is also excellent. The weak point, it seems to me, is that the argument
*doesn't* tell us why the British colonized China, rather than the Chinese 
colonizing Britain. China *also* had guns, germs and steel, *and* had a
considerable head start on West Europeans. Diamond argues that this is *also*
due to geography; specifically that Europe's complex indented coastline led to
a much more politically fragmented subcontinent than the highly-unified China.
This meant that Zheng He's oceangoing expeditions could be halted by court
intrigue, whereas Christopher Columbus could go shopping among the many
competing courts of Europe. To me, this seems to be a case of "when all you
have is a hammer, everything looks like a nail", particularly because many of
China's early technological leaps *and* wars of conquest happened while it was
already a highly unified, centralized state. 

Still, I'd definitely recommend the book. Apart from its main aim of educating
about the influence of geography on history, I find it also has two other
uses: As an idea generation vehicle for alternate history fiction ("why
didn't rhino-mounted Bantu shock troopers topple the Roman Empire?" is an
*actual sentence* from the book, and is also probably on the top 10 most
awesome questions ever asked), and as an aid for fantasy and sf worldbuilders
to avoid some of the sillier blunders in the field.
