%date 2014-07-13
%author Nathan Lowell
%rating 2

*Half Share* picks up right where [[Quarter Share]] left off - on the good ship
Lois McKendrick, hauling massive cargo loads through the deep dark void of
interstellar space, where our protagonist Ishmael Horatio Wang (yes, seriously)
has just been promoted to an environmental services technician (which may sound
lowly, but in the first book he was a mess hall cook's assistant).  It's much
like the first book - no grand epic tales of action or skulduggery, just a
story about some people who happen to live and work in space.

As I mentioned in my *Quarter Share* review, I'm not necessarily 
hostile to the basic premise. It's clearly patterned after 19th
and early 20th century coming-of-age stories (as the protagonist's
name - which, by the way, raises eyebrows *by the other characters* -
indicates). 

Unfortunately, *Half Share* is dragged even further down by the two
mentioned weaknesses than *Quarter Share* was --- possibly because
Lowell's ability to write interestingly about mundane details isn't
quite enough to save *two* books. I criticized the first book for
the fact that *nothing happens*, but *Half Share* shows me that I was
being sort of unfair, since even *less* happened in this one. In
the first book, the characters were established, Ishmael's mother
died, he entered spacer service and had his first interstellar flight.
In this one, I struggle to even give a plot summary, because so very,
very little actually happens. It's mostly about Ishmael's interactions
with other crewmembers. Everybody likes him, and apart from a little
good-natured making fun of his naïveté, there's not even a hint of 
interpersonal conflict. Every female character gushes about how he's
so rare and special, every male character respects and looks up to
him.

It gets worse: Where Ishmael showed some signs of being a [Gary
Stu](http://tvtropes.org/pmwiki/pmwiki.php/Main/MarySue) in the 
first book, he takes the full plunge here. His worldly knowledge - for
someone who we've already established has lived a rather sheltered
life - is absurd and unrealistic. He turns out to have an
authoritative knowledge about gourmet food and fashion clothes even
though *this book* establishes that he's never been out to eat in his
entire life, and the only civilian clothes he ever owned was bought by
his mother. 

Add to this that the last *fourth* of the book was essentially a giant
toe-curlingly awful exposé about how nearly every named woman in the
book wants to have sex with him and how he manages to score with the
most attractive and sought-after woman in a spacer bar solely through
the power of suave. This, I hasten to add, is the same guy we've
repeatedly established is a rather awkward, naïve 18-year-old boy on
the very bottom of the social pecking order.

In other words, it had all the weaknesses of the first book, and even
managed to undermine one of the strengths: Character believability.
While Ishmael was a bit of a Gary Stu in the first book, the *other*
characters suffer in this one - particularly the female characters,
who are reduced from interesting spacers with their own interesting
stories I'd have liked to know more about to a combination of gushing
ninnies and dull sex objects. The aforementioned toe-curlingly awful
last fourth of the book is introduced by a *literally* two-page-long
description of Ishmael ogling their bodies when they're in civilian
clothes. Not exactly out of character for an 18-year-old boy, but the
fact that the *rest* of that part deals with how *every female
character in that part* reacts the same way to *him* seemed stupid. Am
I supposed to believe that these women - ranging from the nerdy
environmental specialist through (not one, but *two*) badass butch
rocker chicks ten years his senior, to the smoking hot officer every
man in the story dreams of - are all reduced to 18-year-old tittering
schoolgirls solely by the power of our hero's newly-bought fashion
clothes? Come on.

It was bad, but it wasn't [[Ringworld]]-level bad. I wouldn't recommend it,
and I hope [[Full Share]] is better.
