%date 2014-01-24
%author David Brin & Gregory Benford
%category [[Book Reviews]], [[Notebook]]
%rating 3

In 1986, Halley's Comet made one of its regular Earth flybys. That same year,
David Brin and Gregory Benford published *Heart of the Comet*, a hard SF
story set on the comet, as a celebration of its flyby.

Giving a rating to this book has been the hardest in all my book reviews yet.
Like [[Ringworld]], it has its share of both awesome and awful.  Unlike that
particular literary abortion, however, the awesome is *much* better executed,
and the awful not quite as egregious.

The plot is great. We follow an international scientific and engineering
mission to Halley's Comet, intended both to study the comet and to nudge it
into a short-period orbit to allow the Earth (and its Mars colony) to exploit
its resources (and to possibly become the first of many comet mining
operations). Part of the crew (including its entire leadership) consists of
*orthos* (for "genetically orthodox"), genetically unmodified humans, and part
consists of *percells* (named after the fictional scientist Simon Percell, who
developed genetic augmentation techniques that eradicated many diseases and
enhanced several human natural abilities). The expedition discovers a small
alien ecosystem of microbial life and colony organisms on the comet, and 
breaks into squabbling factions while fighting infestations of "Halleyforms"
and dealing with alienation from Earth. Their factions are both a result of
ortho vs. percell prejudices, as well as a variety of Earthside political 
struggles.

The story proceeds from early work on the comet to the eventual dawn of 
"cometary man", a new genetically tailored comet-dwelling species, breaking off
from mainstream *Homo sapiens*. There are all sorts of personal, political and
scientific struggles and plot twists along the way.

Likewise, the setting is *great*. David Brin has a Ph.D in astronomy,
specializing in cometary studies, and it shows. The comet is described with
such a degree of accuracy and detail that it becomes a believable place. The
political situation on Earth - recovering from the wars and environmental
devastation of the "Hell Century" and now reeling from percell vs. ortho riots
and displacements - is also depressingly believable. The forays into
speculative computer science are a bit silly, but not worse than other 80's SF.

Unfortunately, the characters are absolutely and utterly terrible. They're 
stereotyped to such a degree that they might as well be comic relief
caricatures. Allow me to introduce our three main characters: Carl Osborn is a
percell spacer, a square-jawed brave young All-American Hero who somehow
manages to combine being a genetically perfected superman with being a
Relatable Working Everyman. He's also awkward around women. Virginia Herbert is
a gifted computer hacker, who would obviously have gone on to become a
housewife if not for the tragic death of her mother (because *obviously*, women
need traumatic events to have any non-domestic aspirations in life). She's also
a choleric lunatic who's equally prone to writing awful poetry and holding the
entire expedition hostage when in the throes of her Womanly Emotions. Finally
we have Saul Lintz, an elderly brilliant scientist and Jewish stereotype, who
knows everything about biology, is Jewish, participated in creating the percell
population, and is Jewish. If I imagined voices while reading I'd probably
imagine him sounding exactly like Mel Brooks. These three form the most
face-clawingly awful love triangle in the history of science fiction.

The main characters are so stereotyped it's almost impossible to care about
what happens to them. I found the scene where Virginia holds the entire mission
hostage in order to be cryogenically frozen along with her love interest
particularly infuriating - if anyone actually acted this way, any sane mission
commander would promptly grant them their wish and keep them frozen for the
rest of the mission. Some of the supporting cast certainly have their moments,
but most of the interesting ones either get killed off, or devolve into even
worse stereotypes.

It's not quite as bad as Ringworld, but this is another grimace-inducing
example of science fiction obviously written by rich white American straight
guys for rich white American straight guys. I'm not saying there's anything
wrong with rich white American straight guys - some of those (including one of
the authors of this book) have written some damn excellent science fiction -
but I find it infuriatingly bad storytelling when you can use the characters'
ethnicities and genders to accurately predict who of them ends up screwing up
and jeopardizing the entire mission, and who gets to Heroically Save The Day.

The plot and setting was great, the characters awful. I found that the former
were good enough that curiosity and suspense managed to carry me through the
latter. Your mileage may vary.
