%date 2014-07-04
%author Eric Brown
%category [[Book Reviews]], [[Notebook]]
%rating 3

The briefest possible review I can give of *Helix* is that it's essentially
[[Ringworld]] done better. Like *Ringworld*, it's a Big Dumb Object story,
featuring a very similar premise of a mysterious artificial world. In this
case, we're dealing with a giant spiral structure consisting of thousands of
interlinked cylindrical worldlets, all strung about a central star. Its
influences from *Ringworld* are obvious and overt, and I won't be able to keep
myself from making comparisons between the two stories throughout this review.

There are two concurrent plotlines, one concerned with the last humans alive,
another with a community of aliens.

The human protagonists set out from a dying Earth, ravaged by environmental
disaster and desperate wars over the last remaining resources, in a starship
(the only such vessel ever constructed) with four thousand colonists plus a
handful of technical crewmembers. After suffering a mid-voyage accident that
damages their ship and kills a quarter of the cryogenically suspended
colonists, they are forced to land on the eponymous Helix and try to find a
human-habitable worldlet on it.

A concurrent storyline concerns some of the inhabitants of the Helix,
lemur-like aliens living under a strict theocratic society in the equivalent of
the early Industrial Age. Our alien protagonist is the wealthy, brilliant heir
to the business empire of airshipwrights founded by his father. He's also
secretly an atheist, who despises the totalitarian rule of the Church and who
tries his best to hide his lack of religious faith both from the Church
officials he has to deal with in his business, and from his highly religious
fiancée.

Unlike the ridiculous stereotypes in *Ringworld*, the human characters are
actually believable characters with believable backgrounds, believable
grievances, believable reactions to their situation, and believable
interpersonal conflicts.  Due to some past bad blood between some of the
characters (and a case of mistaken identity), some of them outright hate each
other.  But - and this is really what I would expect from people who have been
selected to take responsibility for the establishment of the first (and likely
only) extrasolar human colony - they're also *professionals*, capable of
suspending their personal issues when the task demands it.

The human POV character is a middle-aged, overweight engineer with mildly
depressive tendencies and who wouldn't be able to fight to save his life. He's
also a believably human being who grieves over the death of his loved ones and
who struggles to come to terms with his situation. This makes him much more
*interesting* than Niven's Captain Übermensch, Ph.D, because he *doesn't*
always have the skills and abilities to handle the situation, so he has to
*work* and *think* - and *grow* as a character - to get out of the scrapes he
ends up in.  He - again, in stark contrast to the *Ringworld* protagonist -
frequently has to rely on the expertise of his *crewmates* to survive.  This
makes for *much* more interesting character interaction than in *Ringworld*.

One thing I did find rather creepy was the romantic subplot between the POV
character and one of his crewmates. Specifically, the fact that *he kept
referring to how she reminded him of his daughter*.

Although *Helix* avoided much of what I hated about *Ringworld*, it did have
its share of clichés, plot contrivances and implausible technical details. The
first that jumped out: How the hell does a starship survive atmospheric
re-entry (and perform a successful landing) *while going at near-lightspeed*?
How can a bunch of religious fanatics whose highest technological achievement
is a Zeppelin analogue *repair and operate a ultra-high-tech alien spaceship?*

The Church - the main antagonists of the story - was essentially an
organization of cartoon villains. They had no sympathetic qualities, no
redeeming characteristics. Given that their thought policing was not effective
enough to keep prominent members of society from turning atheist, how could
people possibly have put up with their bullshit for so long? Their motivation
seemed to be reducible to "they're evil because they're evil".

But the *worst* offense - the one that blew my suspension of disbelief and had
me loudly exclaim *"BULLSHIT!"* - was the ability of one character to magically
pick up alien languages and interface with alien technologies due to an
ill-defined Magitech "smartware" brain implant. It seemed so wildly implausible
that she might as well have had a Babel Fish - and it was very obviously a plot
contrivance to allow the human and alien characters to talk.

Speaking of aliens, I also didn't much care for those. Put simply, they
*weren't* alien. They were essentially just humans at various historical
stages, except transplanted into lemur (and insect-lizard) bodies.

The Helix Builders were a complete disappointment and the final meeting with
them was entirely predictable. 

I'd probably regard it as the literary equivalent of an entertaining B-movie.
The science was implausible, there were too many clichés and obvious plot
conveniences, the villains were cartoonish and the aliens were essentially guys
in rubber suits. But there was also decent characterization, and unlike
*Ringworld*, it wasn't mired in stupid sexist dreck.

I liked it, but it's hardly a great masterpiece.
