%date 2014-04-16
%author Frank Herbert
%category [[Book Reviews]], [[Notebook]]
%rating 5

Frank Herbert's reputation can be summed up very briefly: He's the guy who
wrote *Dune*. A lot of people don't know much about his other writing (which
spans several genres) - and unfortunately, I must admit that I never read any
of it either. A former co-worker of mine recommended *Hellstrom's Hive*, so
here we are.

It was a horrifying, and utterly fantastic, read. Along with [[Diaspora]], it's
the high point of my year's science fiction reading so far.

The story is set two weeks into the future, as seen from somewhen in the 1970s.
The US is a police state, the Communists are still regarded as a huge threat to
US national security, and a secret agency (known simply as "the Agency")
monitors both citizens and other government entities. For their own good,
obviously.  It's a repressive paranoid nation, policed by a paranoid secret
police which press-gangs its agents and discreetly murders them once they're no
longer useful.

...and that's the *least* horrific society depicted in the book.

At some point, the Agency got hold of a set of lab notes belonging to dr.
Hellstrom, a soft-spoken if reclusive entomologist who makes a modest living
producing nature documentaries about insects, and lives on an old farm. The
notes indicate that Hellstrom is involved in work on some kind of
very-high-tech weapon, which obviously catches the interest of the Agency.
Operatives are sent to investigate - the first ones disappear without a trace,
thus *really* invoking government interest.

Unfortunately for everyone involved, Hellstrom isn't *just* working on a
superweapon. In fact, he is a front for the Hive, a giant human anthill of
"domesticated humans", living as social insects do, in secret underground
facilities around the world. They know that the Outside (the Hive word for us)
vastly outnumbers them - and they know that if they are ever discovered, they
will be exterminated. Most Hive people are simple workers, who live entirely to
serve the Hive (and have no instincts for personal preservation). Most of them
can't even speak verbal human language, instead communicating by gestures and
chemical cues. The Hive has existed for centuries - living in secret,
developing its own science, interacting with the Outside through specially
trained fronts.

The Hive is a fantastically well-developed concept. They view themselves as
"domestic" humanity, unlike the "wild" humanity of the Outside. Domestication
implies safety, and the Hive is all about safety. They aren't genetically
modified (they, in fact, have a cultural taboo against genetic modification),
they're just selectively bred - just like how humans have been doing to other
domesticated species for millennia. Essentially, the story asks what would
happen if humans applied the same domestication techniques to ourselves as we
have applied to other animals. The nominal "leaders" of the Hive aren't
tyrannical or power-hungry - they're more overseers than leader figures, with
all lust for personal power bred out of them. They, too, are domesticated
humans.

There are both Hive and Outside (Agency) POV characters. The Hive is not cast
as villains, but as the *heroes* of the story. Given how repugnant a society
the Hive is, viewed from most normal humans' perspectives, this is a *major*
feat of storytelling. From *our* perspective, the Hive appears alien,
repugnant, an assault on human nature.  From *their* perspective the Hive is
home, family, safety. A civilized, peaceful oasis in a threatening wilderness
of violent wild humanity that could crush it underfoot.

Obviously, there are extremely disturbing scenes - although they weren't done
in graphic detail. For better and worse, this allows the reader's brain to fill
in the blanks (and for better or worse, my brain is very good at filling
unpleasantries into those blanks).

Disturbing, horrific, frightening and absolutely fantastic. Highly, highly
recommended.
