%date 2014-07-07
%author Lewis Held
%rating 4
%category [[Book Reviews]], [[Notebook]]
%endnote Crocodile facial scales arise from tensile forces as the animal grows, making them more analogous to stretch marks than to the facial scales of lizards.

*How the Snake Lost its Legs: Curious Tales from the Frontier of
Evo-Devo* is a popular science book about evolutionary development ---
specifically, it's about how various traits of animals arose from an
*evolutionary* perspective, and how the same traits then arise during
the development of an *individual* animal. I suppose it's intended for
biology undergraduates, but as a layman I found it quite accessible,
and its use of biology jargon is well-explained in the glossary. It 
makes *heavy* use of references, and in fact the reference list takes
up a whopping *121* of the 278 total pages. But although it is
certainly rigorous and heavy on the jargon and references (and
*extremely* detailed), it's also engaging, easy-going and humourous.

It's structured as a collection of case studies, organized in five
main chapters (dealing with specific animals or specific anatomical
traits) and an "evo-devo bestiary" with a collection of animals and
how (or why) they developed various of their characteristics. All have
titles that seem more like something you might find in Rudyard Kipling
fables than in a biology textbook:

* *Why the chordate flipped upside down*
* *How the snake rebuilt its eyes*
* *How the cheetah got its spots*
* *Why the fly twirls his penis*
* *How the ape lost its tail*
* *How the kiwi almost lost its eyes*

Each little study describes the sequences of genes that control a
specific piece of animal morphology, the developmental mechanisms that
lead those genes to construct that animal trait, the apparent
evolutionary background of that gene sequence, and often the rather
weird story about how scientists discovered it - usually including
some the more interesting dead ends along the way. All is described
well enough that after having read one of the studies, I can give a
basic (although admittedly watered down - I am a computer scientist,
not an evolutionary biologist) description of - for example - how a
developing snake embryo makes so many more vertebrae than, say, a
mouse embryo.

The book is a treasure trove of fascinating and weird tidbits of
knowledge about evolutionary development and animal anatomy. It's
written with humour and great narrative skill, and was simultaneously
an enlightening and entertaining read. 

Highly recommended.
