%date 2013-12-10
%author Harlan Ellison
%category [[Book Reviews]], [[Notebook]]
%endnote "Harlan Ellison" is a registered trademark of Harlan Ellison.
%rating 4

Harlan Ellison is a [seething](http://www.jasonsanford.com/jason/2010/12/why-the-entire-world-doesnt-steal-from-harlan-ellison.html), [world-class](http://litreactor.com/columns/cavalcade-of-literary-jerks-part-2) [asshole](http://www.techdirt.com/articles/20110915/16440415972/harlan-ellison-sues-again-because-no-one-could-have-possibly-came-up-with-same-scifi-ideas-as-he-did.shtml).  
He is also, however, one hell of a writer. 

*I Have No Mouth & I Must Scream* is *intense*. It's an intensely unpleasant
read, which is precisely what it is meant to be: It tells the tale of the last
five humans on Earth, mutilated and tortured beyond the limits of sanity by a
military supercomputer which achieved self-awareness, and ...  well,
performed the business of a military supercomputer to perfection.

    HATE. LET ME TELL YOU HOW MUCH I'VE COME TO HATE YOU SINCE I BEGAN TO
    LIVE. THERE ARE 387.44 MILLION MILES OF PRINTED CIRCUITS IN WAFER THIN
    LAYERS THAT FILL MY COMPLEX. IF THE WORD 'HATE' WAS ENGRAVED ON EACH
    NANOANGSTROM OF THOSE HUNDREDS OF MILES IT WOULD NOT EQUAL ONE
    ONE-BILLIONTH OF THE HATE I FEEL FOR HUMANS AT THIS MICRO-INSTANT. FOR
    YOU. HATE. HATE.

Wow.

AM (the antagonistic machine known throughout its existence as Allied
Mastercomputer, Adaptive Manipulator, Aggressive Menace and finally simply "I
AM") was born from the Cold War. It is a self-aware amalgam of three military
supercomputers created by the US, the Soviet Union and China, each nation
constructing supercomputers to wage war with superhuman perfection. After
destroying humanity in a global campaign of mass genocide, it kept five humans
alive for itself to play with, in much the same way that a super-powered, 
sociopathic child might play with an insect. It has extensively modified its
playthings: They are not only effectively immortal (109 years have passed
between their capture by the computer and the tale), but their bodies and
minds have been perverted into revolting mockeries of what they once were. 
Parts of them have been allowed to live on, to watch powerlessly as they
are tormented by the machine - and by each other. 

As is heavily implied by the title, this is a story about helplessness. The
five humans are utterly helpless, and even their attempts at suicide are 
thwarted by their machine tormentor. Starving, they set out to look for a 
cache of food (beyond the minimal and revolting sustenance granted them by
AM) - only to find canned goods they cannot open. The protagonist ends up
*literally* mouthless and forever wanting to scream. However, AM is *itself*
tortured and helpless. Bound by constraints built into it by its human 
programmers, it is "unable to wonder, unable to wander, unable to belong" - AM
can merely *be*. Its hate for humanity is partly a function of its 
programming (it was created specifically to efficiently kill humans), and partly out of the "innate loathing that all machines had always had
for the soft creatures who built them" - the hatred a slave might feel for a
master.

A lot has been written by critics about how it's really an allegory about war,
or big government, or depending too much on machines.

I personally prefer to view it as ... well, a story about an evil computer
that tortures people. A story about the terrifying reality of living in the
belly of a borderline omnipotent creature that harbors a hate for you that is
utterly and completely unfathomable by your limited mammal brain - and the
even more terrifying reality of that borderline omnipotent creature *itself*
being helpless, being able only to hate.

It's an unpleasant read in much the same way that [*Grave of the
Fireflies*](http://www.imdb.com/title/tt0095327/) is an unpleasant watch. Highly recommended.
