%category [[Code]], [[Notebook]], [[Meta]]
%title datarama.dk
%notitle
%nodate
%meta The computational contraptions, procrastinatorium and opinionarium of Simon Kongshøj.
%sidebar nav links

Greetings, gentlebeings! Live from the frozen wastes of Denmark, this 
is *Datarama*, the website of Simon Kongshøj --- computer
scientist, bass player, compulsive tinkerer, serial enthusiast,
oxyglot & paramath.  

<h1><span>Latest Emissions</span></h1>
%RECENT

___

