%date 2015-03-01

Other Languages
===============
* [Scheme](http://schemers.org/)
* [Owl Lisp](https://code.google.com/p/owl-lisp/)
* [Elm](http://elm-lang.org/)
* [Self](http://www.selflanguage.org/)

Papers & Articles
=================
* Bret Victor: [Learnable Programming](http://worrydream.com/#!/LearnableProgramming)
* David Ungar: [Why I Believe in Dynamic Languages](http://people.dsv.su.se/~beatrice/DYPL/ungar.pdf)
* Dan Ingalls: [Design Principles Behind Smalltalk](http://www.cs.virginia.edu/~cs655/readings/smalltalk.html)
* Andrew Sorenson: [Programming with Time](http://impromptu.moso.com.au/extras/sorensen_ow_2010.pdf)
* Leo Brodie: [Thinking Forth](http://thinking-forth.sourceforge.net/)
* Guy Steele: [Growing a Language](https://cs.au.dk/~hosc/local/HOSC-12-3-pp221-236.pdf)
* Paul Graham: [Programming Bottom-Up](http://www.paulgraham.com/progbot.html)
