%date 2015-11-16 

Occasionally, some people will claim that Sweden's very high rape statistics
(#3 in the world, after South Africa and Botswana) is a result of their very
liberal immigration laws --- the logic being that immigrants are brutalizing
helpless Swedish women. However, rates of nonsexual violent crime in Sweden is
still very low compared to many other countries, *and* rape of Swedish men is
*much* more common than rape of men in most other countries. This seems
odd. So what gives?

Sweden has a much broader legal definition of rape than many other countries.
For example, Swedish law considers a variety of nonconsensual sexual acts apart
from penetrative intercourse to be rape, such as unwanted oral sex. Swedish law
also considers a sexual act rape even if the victim doesn't say "no", if it
happens in a context where the victim would not be able to give consent - such
as if asleep or severely intoxicated. Sweden is also one of comparatively few
countries in which a man being forced or coerced into sex by a woman is legally
considered to have been raped (this accounts for the very high incidence of
male Swedish rape victims). In many other countries, the aforementioned
scenarios are considered "sexual assault", but not rape.

Furthermore, Swedish government rape statistics consider *every* act in a rape
case a separate rape, so if somebody has been repeatedly raped by an abusive
partner over a period of several years, then that is counted as hundreds of
rapes (where most countries would count it as one rape case). Finally, Swedish
authorities are comparatively proactive in encouraging victims to report a rape
to the police.

After changing its legal definition and counting method in 2005, the number of
recorded rapes more than doubled the next year. As far as I know, there are no
analyses of correlation between Swedish rape statistics and immigration that
even attempt to control for the legal definition and counting method.
