%date 2014-01-05
%author Stanley Schmidt
%category [[Book Reviews]], [[Notebook]]
%rating 2

*Islands in the Sky* is a collection of short articles from *Analog*,
discussing the scientific, technical and economic background of space
colonization. It's edited by Stanley Schmidt (editor of *Analog*) and Robert
Zubrin (astronautics engineer and writer), the latter of whom I already knew as
the writer of *The Case for Mars* (which I'll review here later). Schmidt
states on the back cover blurb that this isn't science fiction, but "things we
can do".

Unfortunately, this is its major failing: If read as a straight-faced, sober
presentation on space colonization, the chapters about interstellar aliens,
hypothetical "negative matter" and similar highly speculative topics seem
absurd. On the other hand, if read as a collection of science fiction idea
fuel, the chapters arguing the industry benefits of space colonization and the
highly "down-to-earth" (if you will excuse the pun) treatment of Mars issues
seem pedestrian and dull.

There are lots of figures. Unfortunately, nearly all of them are so poorly done
that they look like the hellish spawn of a particularly abominable MS Paint
session, and they confuse more than they aid.

There were three chapters I found compelling: *Inward Ho*, *Colonizing the
Outer Solar System* and *Islands in the Sky*. The first and last chapters 
are the worst: They tackle economic issues, and are written in infuriatingly
patronizing language. The latter one inadvertently seems to make the case that
capitalism won't take us to the stars (I say inadvertently, since the author
is, of course, a libertarian). It also mentions, in passing, the possibility of
sticking all the annoying unemployed people on a starship and sending them off
into space (incidentally, given the kind of drive systems you'd need on a
starship, this would be equivalent to handing them a high-yield hydrogen bomb and telling them to fuck off).

Most of the book was best described as "meh". Robert L. Forward writes well (as
always), but his chapters seemed oddly out of place. There was some good Mars
material by Zubrin - but it appears to be condensed material from *The Case for
Mars*. 

Not exactly a waste of time, but there are much better books both on space fact
and on science fiction. This tries to be both, and unfortunately doesn't do
either convincingly.
