%category [[Notebook]]
%date 2015-10-27

* It is [better](http://radar.oreilly.com/2015/10/do-one-thing.html) to do one thing well than to do everything poorly.
* Just 20 years ago, [we didn't know that exoplanets existed](http://blogs.discovermagazine.com/outthere/2015/10/06/from-0-to-5000-planets-in-exactly-20-years/#.VjHIns-VuCg).
* An engineer at Google has successfully sent [a potato into space](http://www.ianww.com/blog/2015/07/17/sending-a-potato-to-near-space/).
* Large swarms of ants have both [liquid-like and solid-like](http://phys.org/news/2015-10-ants-solid-like-liquid-like.html) properties.
* In a sane language, [this function](http://php.net/manual/en/function.uopz-overload.php) would be named `ia_ia_cthulhu_fhtagn()` or `launch_ALL_the_missiles()`.
* Bill Paxton is the only actor who's been killed by both [an Alien, a Predator and a Terminator](https://www.youtube.com/watch?v=DHg6S4AYlb4). Lance Henriksen also gets mentioned for that particular honour, but I call shenanigans: His character got maimed, but never killed, by the Alien.
