%date 2015-11-24
%author David Marquand
%category [[Book Reviews]], [[Notebook]]
%rating 4

Although historian David Marquand's *Mammon's Kingdom* is
nominally about Britain (it's even subtitled "An Essay About
Britain, Now"), its main points appear to apply, at least, to
my own native culture of Denmark as well, modulo some
historical details. While its subtitle is at least accurate
inasmuch as the book is an essay about Britain, it's only
partially about *now*. Well over half of it is about the
historical shifts that *led* to the current state of affairs.
The chapter titles serve as a satellite-photo view of
Marquand's points: 

1. Hedonism Trumps Honour
2. Amnesia Conquers History
3. The Market State Invades the Public Realm
4. From Fate to Choice and Back Again
5. Charismatic Populism Smothers Democratic Debate

The main point is that British culture has been *marketized*^[In Denmark, the last Social Democratic minister of finance openly declared that we ought to move from a "welfare state" to a "competition state", centered entirely around the needs of the market.],
that capitalism has been promoted from being an economic system
to being an all-pervading cultural force --- and hence, that
Britain has become Mammon's Kingdom, a country of culturally
and morally impoverished money-worshippers. A marketized 
society will inevitably start to shed its cultural and ethical
values when they're not of immediate use to the economy, and
the result is a vestigial public realm with no use for
history, honour or democratic debate --- or any piece of
nature that isn't marketable. With any notion of a "common
good" destroyed, the stage is set for massive inequality, 
rampant consumerism, class snobbery, political corruption and
decay of democracy. It's the same basic point Marcuse made
decades ago in [[One-Dimensional Man]].

Perhaps the largest difference with Marcuse's polemic (apart
from Marquand being a much clearer writer) is that Marcuse was
predicting a bleak future from a position when progressive
counterculture (and a thriving civil rights movement) was still
making strides; Marquand is reporting from the midst of the
very society Marcuse was warning about. Everything has been
marketized, and the market logic has gotten so deep inside our
heads that even the thought of a non-market-driven civic
culture seems like a quaint, naïve fantasy.

Perhaps ironically, the 1960s counterculture movement is among
the villains of Marquand's piece: It represents *moral
individualism*, which was part of a two-front battle against
the public realm, the other front being fought by *market
individualism*, as advocated by Friedrich Hayek et.al. These
two movements are situated on opposite sides of the left-right
spectrum, and are largely mirror images of each other: Market
individualism imagines people of traditional, conservative
moral virtues operating in a laissez-faire economy, whereas
moral individualism imagines morally libertine actors within a
vaguely-defined collectivist economy. Although opposed to each
other, both sides were also opposed to the public realm^[It occurs to me that in terms of the Political Compass, the  zeitgeist of the postwar years was - on both left and right - a major shift towards libertarianism.]. 
However, this individualist ideology didn't lead to more civic
liberty: In fact, it led to *the opposite*, with massive
centralisation and government strongarm tactics being imposed
(under the Thatcher government) in order to break unions, crush
social mobilization and clear the way for marketization. The 
old public realm elites (intellectuals, public service
officials and working-class leaders) fell, and were replaced
with a new market elite, with no loyalty to society and no 
merit beyond money and celebrity. And the old elites, Marquand
argues, were at least *decent*.

Although I agree with Marquand in his opposition to
marketization, I find that a weak point of the book is
that it seems to come *very* close to an unhealthy
glamourization of the past; the Romantic trope of the Lost 
Golden Age as applied to the recent past of British history. 
Almost inevitably, the Lost Golden Age turns out to have been
rather less golden in reality (and reviewers with [better knowledge of British history than me](http://www.lrb.co.uk/v36/n15/jeremy-harding/gloomy-pageant) have accused Marquand of committing
partial accounting). Viewed as political polemic, the notion
of resurrecting the past is probably also rather useless
outside of conservative circles.

The conclusion is unfortunately (and, I guess, symptomatically)
the weakest part of the book, and is very close to a
non-conclusion. Marquand suggests that Britain have a "national
conversation" about how the market can be "re-tamed", and
suggests that a new civic society might be forged that combines
the conservative, liberal and socialist traditions, with a
morality in which "the common good comes before individual
appetites". He also suggests that religious tradition might
have a role to play in drafting a new civic culture --- if only
for religious experience in creating community; Marquand
himself is an atheist. There is nothing in the conclusion that
suggests any *action*, and it seems to me that calls for
"national conversations" (regardless of nation or subject) are
a dime a dozen these days, and rarely lead to any actual change
beyond the generation of a large number of tweets and Youtube
videos.

Nevertheless, it's a thought-provoking book, and Marquand makes
his points well.
