%notitle
%nodate

Merlin is a functional dynamic programming system in the Lisp
family. It's designed and intended for a low-ceremony,
refactoring-based, exploratory approach to writing software. World
domination wasn't a design goal; if your tastes in programming
languages differ from mine, you have my sincerest condolences for
your misfortune. The implementation is in its early embryonic
stages.

**NOTE:** This page reflects the current state of the language. It
is a work in progress, and these pages are subject to sudden and
apocalyptic change with no notice.  

Download & Resources
====================
* [[Merlin 0.0.3|Stable Prerelease]] (0.0.3)
* [Development Release](https://github.com/datarama-dk/merlin) 
  (GitHub)
* [[Inspirations for Merlin]]

Features
========
* *Language*
    * Small, dynamically-typed λ-based core
    * Full Unicode identifiers
    * First-class functions
    * Pattern matching
    * Variadic functions
    * Quasiquotation
    * Code is data
* *Implementation*
    * Self-hosting compiler
    * Targets JavaScript
    * [[Software License|Permissive free software license]]

Revision History
================
* [[Merlin 0.0.3|0.0.3]] -
Pattern Matching, Quasiquote & more
<span class="date">SEP 2015</span>
* [[Merlin 0.0.2|0.0.2]] -
Self-Hosting Compiler
<span class="date">AUG 2015</span>
* [[Merlin 0.0.1|0.0.1]] -
Core Language Interpreter
<span class="date">JUL 2015</span>
