%title Merlin 0.0.1
%date 2015-07-22
%subtitle Core Language Interpreter

This release implements the Merlin core, a small functional language
based on s-expressions. The language is dynamically typed,
statically scoped, purely functional and features strict evaluation.
The current core provides:

* Lists
* Atoms (symbols and numbers)
* Primitive functions (`pfun`s)
* User-defined functions (`ufun`s)
* A basic quotation mechanism
* A small collection of special forms: define, if, let, and, or, let, λ

It's implemented as a simple interpreter, written in
[Gauche](http://practical-scheme.net/gauche/) Scheme. The only 
purpose of this interpreter is to host the development of the 
(JavaScript-targeted) compiler that is to become the main
implementation. I wanted to have a simple (but inefficient and 
stripped-down) implementation ready as quickly as possible, so I 
could do the rest of the Merlin implementation in Merlin itself.

In other words, this is a throwaway interpreter. Don't expect much
from it.

Download
========
tar.gz: [merlin-0.0.1.tar.gz](files/merlin-0.0.1.tar.gz)  
MD5: `1bd5e67e94d22cd7a1751aafd69f1c1f`  
SHA256: `273b509cabc7d315203d587560ba636c4aadc9592b7ac35e29f04eb459955aaa`
