%title Merlin 0.0.14
%date 2015-08-11
%subtitle List Quotations

This is a very minor revision, which extends the symbol
quotation mechanism introduced in revision 0.0.12 with
support for quoted *lists*. It currently works in the most
naïve way possible: It simply constructs a nested `cons` 
expression.

Unfortunately, there's a pitfall to this method: It gives 
some rather wonky comparison semantics (although I know
of at least [one](http://alex.nisnevich.com/ecmachine/) Lisp
with the same behaviour): It means that `(= '(1 2) '(1 2))` 
will be false. For *dynamically* constructed lists, eg. 
`(= (· 1 2) (· 1 2))`, this is perfectly reasonable
behaviour for `=`. However, for *constants*, it'd be much 
more sensible to consider all lists with the same elements
equal to each other. Furthermore, this method has poor 
performance for large quoted lists in recursive functions, 
since they'll get reconstructed repeatedly & uselessly. In
other words, this implementation doesn't treat them as true
constants.

There are a number of ways to support this, but the one that
I like the most requires a little more compiler tooling to
support. Fortunately, that tooling is precisely what I'm 
planning to implement next.

This revision also ditches the `RELEASE.md` and `HISTORY.md`
files in favour of a more traditional changelog.

Download
========
tar.gz: [merlin-0.0.14.tar.gz](files/merlin-0.0.14.tar.gz)  
MD5: `ea5113c8eca10cb2fd3d044d7773f94a`  
SHA256: `6bc4cb568fc2b8eba7c79b2d4407cd915d2b791713acc00b8fbb804300923fcc`
