%title Merlin 0.0.1: Core Language

This release implements the Merlin core, a small functional language
based on s-expressions. The language is dynamically typed, statically
scoped, purely functional and features strict evaluation. The current
core provides:

* Lists
* Atoms (symbols and numbers)
* Primitive functions (<pfun>s)
* User-defined functions (<ufun>s)
* A basic quotation mechanism
* A small collection of special forms: :, if, let, and, or, let, λ

It's implemented as a simple interpreter, written in
[Gauche](http://practical-scheme.net/gauche/) Scheme.

Download
========
* Source tarball: [merlin-0.1.0.tar.gz](files/merlin-0.1.0.tar.gz)
* MD5: 
* SHA256:
