%title Merlin 0.0.2
%date 2015-08-18
%subtitle Self-Hosting Compiler

With this release, the Merlin compiler can now compile itself,
and the Scheme-based interpreter has been discarded. The rest of
the language development will be done in Merlin itself.

The compiler only compiles a small core language; the bare 
minimum required to build a self-hosting compiler. There's still
lots of work to be done with it. 

* The language still lacks several important features:
    * Variadic functions
    * Quasiquotation
    * Macros
    * Modules
* The language is purely sequential, and has no interaction story.
* The compiler performs no optimizations. I'm planning a
  CPS-based optimization phase for a later releaase.
* Tail calls aren't optimized. Any long-running recursion, even
  a tail-recursive one, will memory leak and crash.
* The backend has no real model of JavaScript, it just blindly
  bangs strings together.
* The runtime is an absolute mess.
* Neither compiler nor runtime produce useful error messages.
* The runtime is entirely focused on `node.js`, and isn't browser-friendly.

But all those things are for a succession of future releases. 
For now, I celebrate.

Download
========
tar.gz: [merlin-0.0.2.tar.gz](files/merlin-0.0.2.tar.gz)  
MD5: `ce85f3fc62a40074df64199d8ed774a9`  
SHA256: `9374a76158558ed1ea0b9fb17965eaa918703c1c4e919c9e935297b0ca80cfed`

