%nodate
%cdesc self-absorbed nonsense

* [[About Me]]
* [[Colophon]]
* [Chronological Archives](archive.html)
* [[No Comments|Where are the comments?]]
* [[Content License|Copyright License]] (text)
* [[Software License|Copyright License]] (code)
