%date 2014-01-16
%rating 1
%category [[Book Reviews]], [[Notebook]]
%author Ollivier Dyens

Ollivier Dyens' *Metal and Flesh* (with the ominous subtitle "The Evolution of
Man: Technology Takes Over" is a nonfiction treatment of the broad concept of
*cultural biology*: The complex interplay of biology and technology that makes
up contemporary and future human life. 

As even a cursory glance of my science fiction book reviews here would reveal,
I find posthuman themes fascinating. You'd think something like this was right
up my alley.

Unfortunately, this book is a towering compendium of bullshit.

The main point of the book is that human life is primarily concerned with
*intelligence*, and only secondarily with mere biology - that we, as humans, 
imbue our environment with intelligence, and that our intelligence is also the
driving force of our own evolution. We use our intelligence (and the tech we've
created with it) to take direct control over our bodies, and use medical
implants and cosmetic surgery to adapt ourselves into other forms than what is
strictly prescribed by our genotype. We have also constructed machines that
allows us to gain impressions about phenomena that aren't observable to our 
biological senses - X-ray photography, cell microscopy and deep space radio 
observatories are all examples of such "machine-mediated senses". It may thus
be the case that, at some point in the future, nonbiological intelligent life
descended from humans (such as the citizens and gleisners from
[Diaspora](diaspora.html)) might be the primary expression of intelligence on
Earth, because intelligence does not *necessarily* have to be meat-based.

That's not a bad starting point. In fact, I *agree*.

Unfortunately, this book argues its case using an arsenal of the absolute worst
the weird world of post-modernist humanities has to offer: Florid, pretentious
prose, pseudo-science, obscurantism, nonsense, and outright factual errors.
It's written in the style, common for post-modernist academics, that hackers
have long enjoyed making fun of by [getting computers to imitate
it](http://www.evolutionzone.com/kulturezone/c-g.writing/cgw.baudrillard.txt) -
a bit funny, given the topic of the book.

I'm going to give a few examples of particularly egregious passages. They are,
unfortunately, more or less representative of the work as a whole.

> Human beings are poor physical specimens. We are weak, with neither fangs nor
> claws, and our hearing, vision and sense of smell are all mediocre. Human
> beings do not run, jump or swim very well, and are easily overwhelmed by
> climate. Furthermore, our progeny is born weak and stays vulnerable for a
> long period  of time. How, then, may we justify our presence in this
> ecosystem? 

In actual fact, humans are among the best long-distance runners on the planet,
rivaled only by horses, dogs, hyenas and ostriches. Our bodies are
*impressively* [well-built for endurance
running](http://en.wikipedia.org/wiki/Endurance_running_hypothesis): Our
bipedal gait is more energy-efficient than quadruped animals, our sweat glands
can deposit cooling water directly onto the skin (unlike all non-primate
mammals), we have relatively large hearts and unrestricted breathing during
running. A human in good shape is capable of running many of the animals on the
African savannahs to death from exhaustion - this is very likely the oldest
method of hunting ever employed by hominins. We're also one of the very few
mammals in the world with trichromatic colour vision (a very useful trait for a
creature that needs to find red fruit and berries among green leaves). While 
white Europeans are definitely "easily overwhelmed by climate", the African
ancestors of all of humanity - just like some modern-day African people - did
quite well with only simple shelters and little protective clothing. So yeah -
even discounting our distinctive large forebrains and our propensity for making
cool gadgets, humans *had* a good justification for our "presence in the
ecosystem".

I realize that what Dyens is trying to get at is that our intelligence is our
main defining trait as a species, and that this also explains our fascination
for machine intelligence. I agree. But this premise is flat-out wrong.

> Pamela Anderson, for instance, is no longer a human being. She has become an
> ideological virus (a meme) shared by thousands of men. [...] What attracts
> most men to this actress is not only her body (since clues to its immunity
> and fertility can easily be, and are, manipulated), but also the fact that
> she is less biological than cultural. Pamela Anderson is, essentially,
> Internet images, magazine images. Pamela Anderson is a network of signs and
> desires. Her ontology is cultural in nature, for she has neither presence nor
> existence in the organic world.

What. The. Actual. Hell?

This is not only degrading, it's *nonsense*. It reads like the kind of bullshit
a Markov chain might spit out.

> Antiviral software must know the "perfect" state of the network or machine
> that it protects. Filtering software must be aware of an e-mail's "perfect"
> form before deciding whether or not to destroy it.

This, again, is flat-out wrong. Antiviral software detects the *presence* of
viruses (either by looking for signatures of known viruses or by detecting
specific system activities often used maliciously), not their *absence*. It
doesn't need to know anything about any "perfect" state, and it is in fact
[proven to be
impossible](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.25.1508&rep=rep1&type=pdf)
for any algorithm to guarantee the absence of virus. Likewise, spam filters
use messy heuristics, not any notion of "perfect forms".

> Melancholy, sadness, joy, terror, anger and the like constitute an Esperanto
> that every human being -- every mammal -- can read, understand, and share.

Esperanto is designed specifically to facilitate clear communication
with little ambiguity. The nonverbal language used to communicate the above 
emotional states ... not so much. Apart from the fact that I (and other people
on the autism spectrum) am apparently not a human being or a mammal in Dyens'
view; emotional nonverbal communication across species is *notoriously*
difficult: Most people who aren't primatologists or animal handlers tend to
misinterpret the threatening display of teeth by a chimpanzee as a "smile"
implying happiness.

> For Hitler, for instance, the body of a concentration camp prisoner has but
> one use: The diffusion of Nazi ideology. Such a body endures tortures,
> terrors, and suffering not only because such manipulations strip any trace of
> humanity away from it (causing it to disappear completely; a concentration
> camp prisoner does not exist as a human entity but rather as a symbol of
> Nazism), but also, and especially, because such a transformation shocks,
> horrifies and terrifies.

... why, then, did the Nazis *actively attempt to keep the
concentration camps secret*? Even most Germans didn't know about them,
and the outside world had no idea they existed until the Soviets
discovered one in 1944.

> But digital images are, by definition, contradictory, the image of a number
> being a number itself. Digital images are an impossible construct, for they
> do not deal with our reality, nor do they exist in or through our reality.
> Their reality exists in the dynamic overlapping between the organic and the
> nonorganic.

The fact that *millions* of digital images are created every day (and that some
of them even end up getting printed onto wood pulp!) would indicate that they
do, in fact, exist. Hence, *they're not fucking impossible*!

> [The cyborg] is a simulacrum that transcends the original, a monster that
> inexorably destabilizes all human foundations. [...] The cyborg is a semantic 
> transformation of the body; it is a living being whose identity, history and
> presence are formulated by technology and defined by culture. It is a body free
> of dualities, guilt, sexual repression and frustration. [T]he cyborg is a
> sexless living being, man, woman and machine all at once. The cyborg is the
> obliteration and collapse of the biological.

A friend of mine lost his hearing due to a degenerative nerve disease early in
his life. As a small child, he had a Cochlear implant, artificially restoring 
his hearing. As someone whose nervous system is now directly interfaced with
an electronic device, he is a cyborg. He's not a monster, a "semantic
transformation of the body" (whatever that Markovesque piece of gibberish is
supposed to mean), a sexless being, or the "collapse of the biological". He's
just a boy with electronics in his ears.

These passages aren't that far out of the ordinary for this book (although they
are, admittedly, among the worst). It's full of nonsense and falsehoods - but
given that the author at one point writes that reality is a social
construction, I get the distinct impression that he writes from a particular
tradition (the very same one mocked by Rob Pike in the very first link in this
review) in which factual correctness isn't held in a very high regard.

The best I can say for it is that it's mercifully short. At just under 100
pages, I read it in about an hour. Unfortunately, I cannot now un-read it. Stay
away.

NOTE: If it turns out that Ollivier Dyens *is* in fact a Markov-based text
generator, well played. Joke's on me.
