%nodate
%cdesc serialized brainwaves

Programming Language Design
===========================
* [[Shadow Worlds]]

Fiction Commentary
==================
* [[Gandalf and Those Damn Eagles]]

Fiction
=======
* [[The Endless Cycle]]
* [[Two-Thousand Fifteen]]

Politics & Society
==================
* [[Establishment and Ideology]]
* [[Is Sweden really the European Rape Capital?]]
* [[Why the educational system is a mess]]

Reviews
=======
* [[Book Reviews]]
* [[Film & TV Reviews]]
* [[Tsundoku Pile|My *tsundoku* pile]]

Link Posts
==========
* [[Links for Week 44, 2015]]

In Danish
=========
* [[Facts om Jakob Stegelmann]]
* [[Om partipolitiske magtblokke]]
