%date 2015-08-12

Højre ("blå blok") vs. venstre ("rød blok") er ikke den eneste måde
at sætte dansk partipolitik på et spektrum. Her er et eksempel på en
anden, som er i stand til at forklare dele af det politiske
spektrums adfærd som højre-venstre-spektret *ikke* forklarer, men
som omvendt ikke forklarer andre. Der findes også andre spektre, der
giver mening og har forklarende kraft.

*Systemblokken* består af partier og politikere der først og
fremmest betragter sig som rene forvaltere af et på forhånd fastlagt
politisk-økonomisk system. Omsat til klassiske ideologier er den i
dansk kontekst en slags hybrid mellem socialdemokratisme og
konservatisme, og begrebet "nødvendighedens politik" - synspunktet
at politikere ikke bør agere ud fra politiske overbevisninger, men
ud fra rent pragmatiske overvejelser indenfor de eksisterende rammer
- kunne være dens slagord. Den består af RV, S, V, K og SF (sorteret
i rækkefølge "mest systemorienteret" -> "mindst systemorienteret").
Fordi systemblokkens mest prominente medlemmer alle er
professionelle karrierepolitikere tjener den en aristokratisk
politikerklasses interesser, hvilket bl.a. kommer til udtryk i at
alle partier i systemblokken er enige om lukrative løn- og
pensionsordninger til politikere (mens resten af befolkningen skal
skære ned), masseovervågning af befolkningen (og forargelse over
overvågning af politikere), mørklægningsloven (der på Orwellsk
kaldtes "offentlighedsloven"), store skattefinansierede
prestigeprojekter og magtcentralisering. Systemblokken er
EU-positiv, fordi yderligere EU-centralisering styrker dens rene
forvalterrolle.

*Ideologiblokken* består af partier og politikere der først og
fremmest betragter samfundet ud fra en større, mere eller mindre
sammenhængende vision. Disse har som bærende projekt en gennemgående
omkonstruktion (eller evt. afskaffelse af) systemet, og blokken
består af partierne EL, LA og Alternativet. Af oplagte årsager er
den ikke populær hos politikerklassen, men til gengæld får den vind
i sejlene når politikerleden (og den generelle uvilje mod systemet)
i den almindelige befolkning stiger. Dens medlemmer er ofte
økonomisk uafhængige af deres politiske virke (ELs medlemmer betaler
partiskat, og LAs tjener deres penge i erhvervslivet). Derfor
arbejder den konsekvent *imod* politikerklassens privilegier, og for
almenbefolkningens retssikkerhed - det er derfor EL og LA f.eks.
ofte stemmer sammen om retspolitik og imod særlige
politikerprivilegier, selvom de er lodret uenige om økonomisk
politik og generelt menneskesyn.

Der er et enkelt *midterparti*, nemlig DF. DF fører retorisk stil
som ideologiblokken (og lever ligesom den højt på politikerlede),
men stemmer i praksis sammen med systemblokken. Det er derfor, DF
ikke vil have ministerposter: Hvis de får ministerposter sammen med
systempartier, så bliver de tvunget til *åbent* at føre
systempolitik (og indgå i rollen som forvalter af EU-bestemt
politk), hvorved de fremmedgør deres vælgere.

Folketingsvalget i 2015 kan betragtes som et historisk nederlag for
systemblokken.
