%date 2015-10-28
%category [[Notebook]]

A concept I've found very useful in thinking about my own
language design projects is the *shadow world*, a term 
originally coined by [Gilad Bracha](http://gbracha.blogspot.dk/2014/09/a-domain-of-shadows.html). The basic 
