%title Essays (Orwell)
%date 2015-11-24
%author George Orwell
%category [[Book Reviews]], [[Notebook]]
%rating 5

From Penguin's *Great Orwell* series, this is a collection of
George Orwell's nonfiction. Orwell wasn't a thinker who liked
to limit himself, and so the collection ranges from
recollections on the Spanish Civil War through musings on
totalitarianism to thoughts on the mating habits of toads. He
tells about his life as an officer in British colonized 
territories (and how he subsequently came to find imperialism
utterly disgusting) --- and in a bookshop, selling used books
(and, as it were, boys' weekly magazines). He can write with 
authority on what life is like in a British 1930s homeless 
shelter *and* give a massive 60-page literary criticism of 
Charles Dickens. He'll rail and rage against pacifism (a 
philosophy he despised), and then tell why it was precisely the
right strategy for Gandhi. He can make his experiences as a 
schoolboy picked on by upper-class bullies seem every bit as
viscerally unjust as the evils of the fascists he fought in
Spain.

I've long [[Two-Thousand Fifteen|admired Orwell]], and although
I've loved his fiction since I was old enough to understand it,
I think he's even *better* as a nonfiction writer than as a 
fiction writer. An unorthodox and fearless thinker, Orwell
wrote in clear, direct language with no pretension and no 
buzzwords. The prototypical democratic socialist, he (in
contrast to lazier, more tribalist thinkers) entirely rejected
both the Stalinist intellectual current of his time (which he
regarded as no better than fascism) *and* the rigid capitalist
class society. If there's any one common strand in his 
political life, it's an enduring hatred of authoritarianism.

Orwell lived in a time that's still regarded as one of the most
evil in modern history. He was a contemporary of Hitler,
Stalin, Mussolini, Mao Tse Tung and Franco. He wrote in the
very beginning of the mass media culture we now live in --- and
if there's any thinker who ought to be considered required 
reading for anybody who lives their daily life soaked in both
political and corporate propaganda, it's Orwell.

I can't recommend this collection highly enough.
