%date 2014-10-31
%rating 5
%category [[Book Reviews]], [[Notebook]]
%author Stephen Baxter

Before going on with this review, I have to point out that my scoring system
here isn't intended as an attempt at an objective measure of literary quality.
It simply denotes how much I enjoyed reading a particular book. 

And thus, *Proxima* is without a doubt the most flawed work to date that I've
had to give a full 5 stars. Stephen Baxter is sometimes described as "Arthur C.
Clarke's natural successor" (including on the back cover blurb on this book),
and I completely agree: His writing largely has the same strengths *and*
weaknesses as Clarke's did.

I *loved* Proxima. I was almost unable to put it down after I started it, and
read its 450 pages over the course of three workdays. Its primary story thread
tells the story of Yuri Eden, a cryonically suspended remnant of the "Heroic
Generation" --- an era of extremely energy-intensive prestige projects that
essentially ruined the Earth (of course, leaving coming generations with their
mess). His parents had him put in stasis in the hopes that he'd eventually be
unfrozen in a better world --- but, unfortunately, he wakes up in a world in
which he is despised as a link to the horrors of the past. Essentially, people
treat him in much the same way as the cryonically suspended offspring of Nazi
party officials would probably be treated if they woke up in early 1950s
Warsaw. He's eventually loaded onto an early starship along with a band of
petty criminals, unemployed people and other social undesirables, and sent on a
one-way trip to colonize the third planet of the red dwarf Proxima Centauri.
The story of the colonization effort is one of conflict, murder, grim survival
and discovery, and is done extremely well. I *loved* the bizarre alien
ecosystem of *Per Ardua* (AKA Proxima C), and I also much enjoyed Yuri's story.

I particularly enjoyed the psychology of this story thread. To the UN
astronauts depositing the unwilling settlers in an alien star system, this is a
glorious tale of interstellar colonization. To the settlers themselves, they're
being marooned by smug assholes on some bullshit planet in the middle of
nowhere. This, once again, is done *extremely* well.

The second story thread is concerned with our solar system, and how the
discovery of alien artifacts on Mercury (some of which are used to construct
the starship carrying Yuri to Proxima) leads to a heating of the cold war-type
standoff between the Chinese Empire and the United Nations (neither of which is
unilaterally cast as hero or villain). As would be expected in such a
situation, there's lots of political intrigue and backstabbing, involving both
government and corporate agents --- as well as intervention from AIs
constructed during the Heroic Generation era. This thread I also enjoyed ---
particularly the aspects dealing with the alien artifact discovery.

All in all, extremely well-done hard science fiction.

But, as said, it also has flaws --- all of which are minor enough that I'm
willing to forgive it, because the *setting* and the *story* are so damn good.
Much, in fact, like how I feel about most of Arthur C. Clarke's works.  Many of
the characters are dull and somewhat interchangeable --- the protagonist is
essentially [Philip J.  Fry](http://en.wikipedia.org/wiki/Futurama), played
straight. There's a third story thread (involving an AI-driven starship) which
completely fizzles and has no real resolution. The artificially intelligent
Colonization Unit that assists the settlers with various colonization tasks is
essentially a walking (or, well, rolling) exposition device, incessantly
dumping scientific exposition on its human charges. It's obvious that Baxter
*wanted* to tell us these science details (and they're all, as is typical for
him, *extremely* well thought-out), and the ColU just happened to be the best
way to do it. The ending is an utterly bizarre cliffhanger ([there's a sequel
coming up](http://www.goodreads.com/book/show/20632979-ultima)), and
unfortunately doesn't disprove my "Stephen Baxter can't write good novel
endings" hypothesis.

For all its flaws, highly recommended. One of the year's science fiction
highlights for me.
