%date 2014-07-12
%author Nathan Lowell
%rating 2

If there's something that *instantly* turns me off a science fiction
book, it's when the back cover blurb advertises the usual greater epic
nonsense about the *Chosen One* having to go on an *Epic Quest* to 
*Save the Galaxy/Universe* --- in other words, stories that might as
well have been told with dragons and magic instead of spaceships and
(fictional) science. What I particularly find grating about such
stories is that the sheer, incomprehensible *magnitude* of the galaxy
(or *Universe*) means that it doesn't really lend itself to plausibly
being saved by a few canned apes with a bunch of large firecrackers
--- and it *especially* doesn't really lend itself to being
*threatened* by a canned ape (or bug-eyed lizard, as it were) with an
atomic firecracker either. 

Nathan Lowell's *Solar Clipper* series is sort of what happens when
you go to the other extreme: It's a bunch of stories about the lives
of some people who happen to live and work in space. There's no cosmic
mystery, no grand plot, no back-stabbing intrigue and no evil empires
to defeat. They're set in a future where massive
faster-than-light-capable trading vessels (the eponymous solar
clippers) form the economic backbone of an interstellar civilization,
in which some worlds are controlled by the Confederacy (basically a
"United Federation of Worlds" stand-in), and others are entirely owned
and controlled by corporations.

*Quarter Share* starts out on such a world. The 18-year-old
protagonist, Ishmael Horatio Wang (seriously), has led a peaceful if
sheltered life with his single mother, who made her living as a
professor of literature at the local university. Unfortunately, she is
killed in a traffic accident, leaving Ishmael to fend for himself ---
but with no income, and only his mother's modest life insurance to
live on, he's essentially living on borrowed time. He thus decides to
sign on as an unskilled spacer on a trade vessel, earning a modest
salary plus a quarter of a share (hence the title) of the ship's
profits. Essentially, it's a coming-of-age story much like those
people wrote about young men working on seagoing trading vessels in
the 1800's.

The other books are named *Half Share*, *Full Share*, *Double Share*,
*Captain's Share* and *Owner's Share*, so you can probably guess a bit
about the pay structure on solar clippers --- and about Ishmael's
future character trajectory. In *Quarter Share*, we see that he has
some degree of business talent; he starts a little trade co-op with 
some of his crewmates (using their personal effects mass allowance as
tiny cargo slots) to earn a little extra on the side.

The book was a mixed experience. The *good* part is that Nathan Lowell is an
extremely gifted wordsmith, who is capable of making the mundane details of
everyday life on a spaceship seem *interesting*. A two-page description of how
to make a very good pot (well, giant industrial urn) of coffee, with the cook's
quip about the coffee urns being the "beating heart of the ship" distributing
black caffeinated lifeblood to its crew, popped back to my mind when I used to
work in a web development company whose employees were similarly powered by
caffeine. The characters who live and work on the ship have distinct
personalities, and all seem both believable and interesting, indicating vivid
backstories that we don't get all the details of.

Unfortunately, it's also marred by two major flaws. The first is that *nothing
happens*. I get that this isn't a "the Galaxy is in Danger!" story - I *liked*
that aspect of it. However, *conflict* of some kind is usually what makes for
an interesting story, and there was essentially none of it - no external
conflict for the ship to face, no internal conflict among the crew. It all
seems too honest, pleasant and friendly to be of much interest. There's less
actual *story* than in a TV sit-com.

The second flaw is that Ishmael is probably the worst [Gary
Stu](http://tvtropes.org/pmwiki/pmwiki.php/Main/MarySue) I've read in a *long*
time. Sure, he doesn't have supernatural powers and isn't exactly a
Heinlein/Niven-style Übermensch, but there's simply *nothing* that seems to
present a serious challenge to him. He just wanders from success to boring
success until, hey presto, he's managed to impress everybody up to and
including the Captain, and gets himself a promotion to a half-share
environmental systems worker.

If you're in the mood for a not-too-demanding read and are tired of greater sf
epics, you might enjoy it. It's a quick read, but ... well, a bit on the boring
side, to be honest.
