%date 2013-12-26
%rating 2
%author Sean Williams

The first entry in Sean Williams' *Astropolis* trilogy, *Saturn Returns* had
enough "hard-ish" sf staples to catch my interest (although I must admit that 
in reality, I bought the trilogy purely because of the title - it was bought
during a particularly irresponsible book splurge with my girlfriend in the
local [Dragon's Lair](http://dragonslair.dk)): It deals with the remnants of
a transhuman galactic civilization in which faster-than-light travel is
explicitly not possible. Humans have mastered extreme longevity treatments 
and a variety of technology to alter perception of time - in fact, these 
technologies are the primary "SF gadget" explored in this setting. From the
various methods of dealing with interstellar life in a setting where FTL
travel is impossible, multiple different humanities have emerged.

The story itself is basically a murder mystery, albeit one with considerably
higher stakes than most - in fact, it's probably better described as a
"genocide mystery": An ancient, galaxy-spanning human intelligence was entirely
wiped out, and with its collapse came the collapse of civilization itself. The
POV character has been dead for 150.000 years when the story starts, and has
been restored (although gender-flipped) from a damaged record found by a
religious hive mind looking for God at the edge of the galaxy.

Unfortunately, while the setting had lots of cool ideas in it, a lot of the
background was frankly nonsensical. The aforementioned galaxy-spanning
intelligence apparently has less aptitude designing reliable communication
networks than modern-day Internet engineers, because a transmitter disruption
is enough to *kill their entire civilization*. 

The 150.000 year gap between the events of the story and the historical events
remembered by our reconstructed POV character Imre Bergamasc seems more like a
small delay than like the almost incomprehensible stretch of time 150 millennia
actually is. In *Saturn Returns*, Imre returns to familiar star systems to meet
old associates of his and to find a culture easily recognized by him. In
contrast, 150.000 years before I wrote this, *the Ice Age had not yet begun*.
Cro-Magnon man hadn't made it out of Africa. Metalworking was unknown. Nobody
had thought of agriculture.  Animals hadn't been domesticated.

The consequences of the lightspeed limit are sometimes taken very seriously,
sometimes apparently completely forgotten (or ignored). At some points, star
systems appear to have real-time communication between one another, at other
times this is explicitly declared impossible. The time perception alteration
tech also works rather inconsistently (and bizarrely, people who are
Overclocking sometimes seem to be able to *move* at stupendous speeds, despite
the fact that this is at other times explained as strictly a brain
modification). There are many references to "absolute time" and the
"absolute calendar", but it's a well-known scientific fact that *absolute time
cannot exist in our universe*.

All in all, the setting left me with an impression that this was basically a
"poor man's Alastair Reynolds". Many of the same tropes are there, but 
the implementation is nowhere near as consistent and well-thought-through.
It's a honest attempt at "hard" science fiction, but unfortunately has 
so many inconsistencies and science botches that it falls rather flat.

A few parts were cool (the time-perception alteration was a neat idea), a few
parts were meh (the interaction between the lead character and his former
mercenary colleagues were mostly dull exposition dumps and exchanges of
clichés), and a few parts seemed completely superfluous (having the main
character be reconstructed as a woman after his death for no apparent reason
and with no real significance apart from a bizarre scene dealing
with a man's mind in a woman's body while masturbating).

I'm probably still going to read the rest of the trilogy, but the Christmas
harvest of good SF books bumped them down my reading list.
