%date 2015-01-08
%author Kim Stanley Robinson
%rating 2
%endnote If I never see a dick referred to as "a spurt" again, I will consider it a minor mercy.

*Shaman* is the coming-of-age story of Loon, a young orphaned
Shaman-in-training in a paleolithic European hunter-gatherer tribe.
Compared to Kim Stanley Robinson's other stories (which tend to
concern themselves with rather large-scale events), it's a *small*
story: It deals with a few years in the life of one person, who lives
in a small tribe and can probably count all the people he knows on his
hands and feet. 

It starts well, with Loon setting out for his Wander --- a rite of
passage in which he has to survive alone in the wilderness for half a
month before being accepted back into his tribe. The pace is strong,
and we get a distinct impression of just how grim and unforgiving
Loon's world is. We also get an insight into his rather strange
psychology: He doesn't really differentiate much between humans and
other animals (for instance, he refers to female lions as "lion
women", has sexual fantasies involving animals, and regards bears and
Neanderthals as lost cousin tribes). He doesn't understand dreams, and
believes that he is literally experiencing the strange spirit
wanderings of his dreaming mind. During his Wander, he hunts prey, 
makes fire, outwits Neanderthal marauders and defends himself against
bears and lions. He is 12 years old at the time.

Unfortunately, the moment he gets back to his tribe, the story
switches pace and becomes almost insufferably dull. He meets a girl,
they marry, she gets kidnapped, he attempts a rescue mission, some
friends come after him --- all of this could make for a fine "minor 
epic", but for whatever reason, it is all written with a tone and 
pacing more reminiscent of an uninteresting travelogue. I found it
very difficult to *care* about Loon after the story of his Wander. 
The supporting characters, with few exceptions, aren't much better: 
The two tribal elders (Thorn the shaman and Heather the medicine
woman) spend most of their time on page engaged in petty squabbles
with each other (mostly involving Thorn calling Heather names, and
Heather pissing on Thorn's belongings).

The language is frustrating. It's a confusing jumble of modern English
and invented tribal terms. Some animals are called by
modern names, others have weird invented ones. One character breaks
the tone by lapsing into *Italian*; exclaiming "Mamma mia!".

Although Loon was the main viewpoint character, there were occasional
sequences from other POVs --- including a few sequences with *animal*
viewpoint characters, notably a small cat (showing us the early stages
of feline self-domestication) and a wolverine. These were definite
bright points amid an otherwise boring trudge. The character I found
most emotionally engaging was a middle-aged Neanderthal outcast with a
respiratory illness and a vocabulary consisting of three words (but
with superhuman animal imitation abilities). In fact, the speculation
about Neanderthal nature was what I liked best.

This is by far the worst I have ever read by Robinson, and this annoys
me since I *know* he can do better. The *Mars* trilogy was also dull
in places, but it more than made up for its occasionally plodding 
pace by virtue of the setting and the sheer *scale* of the story. 
*Galileo's Dream* and (especially) *The Years of Rice and Salt* were
anything *but* dull. I *know* he can do better, and I *wanted* to 
like this story (prehistoric science fiction generally being an
under-used genre). Unfortunately, I couldn't bring myself to care much
about the main characters, the language was frustrating and the plot
was boring.

Probably best to steer clear.
