%title Datarama Public License
%nodate

Unless I've specifically stated otherwise, all software on `datarama.dk`
is subject to the following free software license (which is included in
the `COPYING` file of relevant source tarballs, and in the traditional
place in the source files).

___

Copyright (C) 2015 Simon Kongshøj `<skongshoj@gmail.com>`.

Permission is granted to anyone to use, copy, modify and/or distribute
this software, for any purpose, provided the following conditions are
met:

1. The authorship of the original software may not be misrepresented.
2. Altered source versions may not be misrepresented as the original.
3. This copyright notice must be retained in any source distribution.

This software is provided "as-is", without any warranty. The author
will not be held liable for any damages arising from its use.

___

It's essentially a simplified version of the 
[zlib license](http://opensource.org/licenses/Zlib), except that I've
removed some redundant language about non-legal wishes, and disambiguated
the second clause. I don't care if or how you "plainly mark" your
modified versions; as long as you're not claiming I wrote your crap,
you're fine.

If you use my software for something interesting, I'd like to hear about
it and I'd love it if you credit me, but the above license represents the
only legal demands I have on the use of my software.
