%date 2014-05-09
%author David Brin
%category [[Book Reviews]], [[Notebook]]
%rating 3

So, given what an abominable turd [[Sundiver]] turned out to be, I went into
the sequel, *Startide Rising* (also by David Brin), half-expecting another
stupid installment of *The Astonishing Mystery-Solving, Adventures & Sexual
Conquests of Captain Übermensch, Ph.D*. Fortunately, it turned out to be ...
well, *okay*. Not a masterpiece by a long shot, but definitely in the better
end of the spectrum.

It's also very much a product of its time. Only in the glorious carnival of
absurdities that was the 1980s could someone decide that *Dolphins... IN
SPACE!* would be a great hook for a science fiction novel. The original concept
for *Star Trek: The Next Generation* actually mentioned giant water tanks in
the *Enterprise*, to serve as habitats for the dolphin and whale navigators.
That franchise also sent a time-travelling William Shatner and Leonard Nimoy to
go swim with whales in order to save humanity.

Also, people liked neon spandex and Mötley Crüe. The 80's were weird.

So. *Startide Rising*. The story takes place about 200 years after the events
of *Sundiver*. The human Uplifting projects have made progress, and both
chimpanzees and dolphins are now capable of both advanced technology use and
scientific thought. The first dolphin-crewed starship, *Streaker*, has been
sent on a mission of scientific exploration - the purpose of the mission being
(aside from the exploration itself) to test the viability of dolphin starship
crews, and to instill self-sufficiency in the Uplifted neo-dolphins. In
contrast, most of the Galactic patron races keep their Uplifted clients in a
state of indentured servitude for a period of 100.000 years, and humanity's
practice of fostering self-sufficiency in its clients (and even giving seats to
Uplifted dolphins and chimpanzees in its highest political offices) is regarded
with suspicion (and outright hostility) by many older Galactic patron races.
They're probably worried that their own clients might start making all sorts of
annoying demands.

Humanity's egalitarian relations with their clients only goes so far, though.
Humans get to decide which dolphins and chimpanzees get to reproduce. One of
the lead characters (a neo-chimpanzee) regards the client representation in the
political process as simple tokenism, and resents the anti-chimpanzee sentiment
some humans hold. The dolphins don't seem to think quite as much about it.

During their mission, the crew of *Streaker* (150 dolphins, one chimpanzee and
eight humans) found a derelict alien fleet, which might have belonged to the
near-mythical Progenitors. They even find a mummified corpse, who might have
been a Progenitor, inside. Unfortunately, their message to Earth is intercepted
by a variety of unsympathetic aliens, who would rather not have such a find in
the hands of upstart humans (and their dolphin and chimpanzee clients), and
launch an attack. *Streaker* crash lands on a water world, trying to hide until
the Galactics finish fighting it out over who gets to kill the Earthlings. They
then discover that the planet has a few mysteries of its own. Specifically, not
only does it have a prime pre-sentient race just ready to become someone's
clients, it apparently once housed an advanced species which built cities and
high-tech gadgets, cleverly placed so that they'd get destroyed by geological
processes before any Galactic surveyors showed up.

It's a passable sf mystery story, with a neat psychological aspect as crew 
morale starts breaking up. Since most of the crew are creatures who must
continually *will* themselves to not descend into animalistic proto-thought,
this leads to a rather tense situation. Also, quite a lot of the dolphin crew
members are, well, assholes. I *liked* this. [Dolphins *are*
assholes](http://deepseanews.com/2013/02/10-reasons-why-dolphins-are-aholes/).
There's racial tension (some of the dolphins are of *Tursiops* ancestry, others
of *Steno* - and there are also a chimpanzee and several humans on board),
shipboard political intrigue - and even a good side plot involving the
(dolphin) captain having to cope with brain damage.

There's still some of what I disliked in *Sundiver*. Brin still likes him some
gratuitous exclamation marks! The dialogue is forced and annoying! Most of the
human characters are rather generic - to the point that I kept forgetting who
was whom! There is *still* a Heinlein-style omnicompetent übermensch in there,
but unlike *Sundiver*, he wasn't the sole POV character. He still annoyed me.
The sexism has also been toned down quite a lot since *Sundiver*. There was a
side plot involving one of the dolphin crewmembers repeatedly sexually
harassing a human woman (sorry, a *fem*, in keeping with Brin's terminology),
but that particular dolphin is pretty much portrayed as an arrogant asshole and
creepy sexual predator, not as someone we're expected to root for (and, as
people who know about cetacean sexual habits can tell you, this is not exactly
unrealistic behaviour for a dolphin). He even *thinks* in terms of "breaking
down" said woman. Had this been *Sundiver*, she'd probably consider herself
honoured for his interest.

*Startide Rising* also has some weaknesses of its own, though. Unlike the
single-POV narration of *Sundiver*, Brin instead adopts a model with many POV
characters, jumping back and forth between them. This sometimes works well -
but here, there are *dozens* of characters. Some sequences give us all of 2-3
lines of prose before the next POV character takes over. It gets incredibly
confusing.  A lot of the dolphin-related material is clearly a product of the
80's, and seems about as dated as ... well, Mötley Crüe.

The alien characters mostly seem ... cartoonish. They're evil caricatures in
much the same way as the Ilwrath in Star Control II: Cartoonish, over-the-top
villainy, with no redeeming characteristics to speak of. I liked the little
details we got about their biology and societies, but they didn't seem like
cultures with literally hundreds of thousands of years of culture behind them.
They were just space orcs. I disliked how humans are presented
as so much *better* in nearly all ways than the Galactics. 

Humans are apparently more curious, more driven, more intrepid, more
egalitarian and more enlightened, than all the other species in the Five
Galaxies. This does not bode well for the Five Galaxies.

It's a passable book. I don't think it's as good as everybody pretends it is,
but it's definitely not *Sundiver*-level bad. It did showcase much more of the
interesting *Uplift* universe, though, and I'm actually looking forward to *The
Uplift War*. 

For that last reason, recommended.
