%date 2014-05-03
%author David Brin
%category [[Book Reviews]], [[Notebook]]
%rating 1

I've heard much about David Brin's *Uplift* universe, most of it good.
*Sundiver* is the first novel in the Uplift series (which consists of two
trilogies), and I was looking forward to reading it.

Unfortunately, it's bad. *[[Ringworld]]*-level bad - and for many of the same
reasons.

The story serves as a passable introduction to the greater galactic politics in
the Uplift universe. The galaxy is populated by myriad sapient beings, nearly
all of which attained sapience by being Uplifted by a patron species. The first
known species to attain sapience was the near-mythical Progenitors, who then
proceeded to Uplift a variety of higher animals they encountered. These, in
turn, would then go on to Uplift other higher animals, bestowing intelligence,
sapience and high technology across the galaxy. This process has been going on
for two billion years, and a number of judicial and political practices are in
place for governing the practice of Uplifting. When a species becomes Uplifted,
it has to serve its patron species for a period of several hundred thousand
years (or until the galactic community decides that it has exceeded the status
of its patron).

There are very few non-Uplifted species around - and humanity appears to be one
of them. This is rare - and in fact, tends to completely screw up the political
and social order of Galactic society, because such a species does not fit
anywhere in the hierarchy established between patron and client species. One
faction of humans believes that humans were Uplifted and then left behind by
some long-lost mythical patron species - a view they share with some of the 
aliens in the Galactic society. In fact, humanity is itself in the process of
Uplifting two client species - the dolphins and the chimpanzees - meaning that
humanity is in the odd position of being a newly-discovered species that is
*itself* considered a patron species.

The story itself is a combination of a scientific discovery story (extremely
alien life has been discovered inside the Sun, aliens which some believe might
be the patrons of humanity), a murder mystery and a political thriller.
Unfortunately, trying to balance these threads turns it into a jumbled mess.

Brin's prose is utterly terrible. Stilted, overcomplicated, long words that
serve no explanatory purpose. Gratuitous, arbitrary exclamation marks!!!
Characters who talk (and *think*) as if they have a thesaurus cybernetically
implanted into their language centres. Jarring, silly linguistic novelties that
seem to make little sense and exist for no reason (for instance, men are
consistently referred to as "mels" and women as "fems").

Most of the characters are ridiculous stereotypes, so the "reveals" in the
mystery subplot are so expected that they just seem like stupid anticlimaxes.
Who'd have guessed that the ill-tempered, manipulative, nasty, unpleasant alien
with an ideological axe to grind turned out to be a *villain*?

The lead character is a Nivenesque übermensch (a trope that Brin himself is
[on record for despising](http://izquotes.com/quote/213294)). Most major events
in the story seem like conceits to demonstrate just how awesome he is. He's 
brilliant, knows all there is to know about strange science, once saved (a
major part of) the world, has Sherlock Holmes-level deductive abilities and is
an expert unarmed fighter too, why not? 

The writing is incredibly sexist. Not quite as bad as Ringworld, but there is
a *wide* spectrum between unproblematic and *Ringworld*, and unfortunately 
*Sundiver* falls on the ugly end of that scale. The first female character
with a major role gets introduced 70 pages in, and her first action is to
(literally) loudly proclaim her sexual availability. She's a badass military
space pilot, who breaks down sobbing in her office and (literally) just wants a
big strong man to hold her. And impregnate her too while he's at it, because it
would be an honour for her to bear the awesome lead character's children. No,
I'm not exaggerating or paraphrasing. In a historical retrospective we hear
about a female triple Nobel laureate - and she's consistently referred to in
terms of her sexual attractiveness. Much like Ringworld, it reads like its
entire treatment of female characters was written with the consulting services
of a focus group of particularly hormone-frenzied 15-year-olds. 

The ending is abrupt and unsightly, and is probably best likened to a freight
train hitting an especially nasty meat packing plant.

All in all, an incredibly bad story, told very poorly, set in a fascinating and
interesting universe.

I hope *[[Startide Rising]]* and *[[The Uplift War]]* are better.

Not recommended.
