%date 2014-01-07
%rating 4
%category [[Book Reviews]], [[Notebook]]
%author Alan Watts

I'm not a Taoist. I don't think I'll ever be one, and I don't play one on TV.
I have, however, read several translations of the *Tao Te Ching* (including one
[delightfully odd one](http://www.beatrice.com/TAO.pdf)), the *Book of
Chuang-Tzu* and have long had a fascination for the
subject. I'm an atheist with a naturalist,
materialist world view, and remain convinced that the scientific method is the
best way humanity has yet conceived to figure out how each part of the
universe works. In that regard, I'm like many other modern Westerners.

Alan Watts wasn't like many other Westerners. 

In *Tao: The Watercourse Way*, he isn't trying to sell Taoism or convert his
readers to Taoism. Watts wasn't a Taoist himself. He wrote and lectured on Zen,
Buddhism and Hinduism. He was a Christian priest for a while. What he primarily
did was to explain Eastern thought to Western audiences - who didn't
necessarily have the cultural background to easily understand these modes of
thought - and this book is a fine example. 

It's not exactly an introduction to Taoist thought; it seems to presuppose that
the reader is familiar with the historical figures central to Taoism (at least
Lao-Tzu and Chuang-Tzu), and to have read the *Tao Te Ching*. It gives a good 
and well-written explanation of the cultural context of Taoism (for example, 
that the writings both Lao-Tzu and Chuang-Tzu should not necessarily be taken
*literally*, since both men wrote in a tradition of heavy allegory and
metaphor). It explains that the central tenet of Taoist conduct is to view
one's self (and all humans) as *part* of the Universe (and the Tao), not as
separate entities. That the Taoist way of inaction (*wu-wei*) is not merely
apathy, but a principled choice of minimal intervention. That duality doesn't
imply dualism, and that it's often impossible to conceive one half of a duality
without its complementary half.  That even if there's no central authority of
the universe (eg. God), there doesn't need to be one for harmony to exist; in
fact it's a central tenet of Taoism that trying to impose rule upon something
will invariably lessen both the ruler and the ruled. 

Perhaps the rather anarchistic nature of Taoism is why it, alone among the
world religions, doesn't have a history drenched in blood: Since its
foundations resist being institutionalized, Taoism never attained control of a
state (and its associated tools of oppression), and thus never established a
religious tyranny anywhere. 

I vehemently disagree with Watts' postulation that pictographic writing systems
(such as Chinese or Ancient Egyptian) are superior to alphabetic ones: They
have a number of weaknesses he completely ignores: There is no direct
correlation between pictograms and pronounciation, readers must learn
*thousands* of pictograms to be considered literate, and pictographic writing
systems are less flexible and extensible than alphabetic ones (try writing
"craptacular", "b0rked" or "meep" with Chinese pictograms). The Koreans didn't
switch from hanja (a pictographic system) to hangul (an alphabetic one) on a
lark; they actually increased literacy *considerably* after doing so. There
*are* benefits of well-designed pictographic systems (and Watts explains many
of them), but they're not the linguistic panacea Watts makes them out to be. 

Now that we're on the subject, I think there was only ever one "serious"
pictographic programming language, namely APL (a language that can famously
express very complicated problems as tiny code snippets - and conciseness is in
fact one of the very benefits Watts mentions). APL code is virtually impossible
to talk about out loud, but that's not necessarily too bad in a culture that
mostly communicates in writing (...but needing a special keyboard *is*). 

Some of the book might be construed as anti-scientific (and Watts certainly did
criticize science, reductionism and the scientific method), but I think this
reflects a misunderstanding on what science *is*. Science doesn't mean thinking
the entirety of reality can be broken into neat categories or put into a single
mathematical formula. Science isn't a human assault on nature. Scientists, in
my experience, are *more* likely to be aware that their models *predict* and
*model* nature, without *being* nature. I find that my own scientific education
has *increased* my feeling of being part of a grand universe, as opposed to
being a special, isolated creature somehow separated from it. This is what
modern science *says*: I'm an ape, I'm related to cheetahs and bees and slime
molds, and I'm built from the same fundamental material as trees, stones,
airplanes and stars. I'm governed by the same physical laws as the rest of the
universe. I'm related to, and connected to, all of it. For me, reflecting on
scientific knowledge often feels *more* "spiritual", for lack of a better term,
than reading religious literature or contemplating Zen koans.

I liked the book. I'd recommend it for people curious about Taoism (and who
already know a few of the concepts), especially people who prefers lectures to
sermons. It was Watts' last book before his death in 1973. It was incomplete
when he passed away, and parts were finished by his friend and collaborator Al
Chung-liang Huang. In some places, it seems somewhat unfinished.  Watts makes
some science fumbles (and takes a *very* one-sided view of the alphabetic vs.
pictographic schism - which, incidentally, seems to me a quite un-Taoist thing
to do), but it's an extremely well-written book about a fascinating philosophy.
I read it in a single evening sitting before going to sleep. 
