%date 2014-04-08
%author Poul Anderson
%rating 3
%endnote Better luck in the next universe, I guess.

Poul Anderson's *Tau Zero* is, for good and bad, a true sf classic. The good is
that it has a compelling big science question, spins an interesting story about
it, and has a setting that makes very good use of the implications of said
science. The bad is that it has bland characters and a rather silly plot.

In summary, a colonization vessel (the *Leonora Christine*) is dispatched from
Earth to another star system. It's powered by a fusion drive and a ramjet scoop
collecting hydrogen and various other particles, and travels strictly at
sublight speeds - this is not a universe in which faster-than-light travel is
possible. Unfortunately, a technical accident prevents the *Leonora Christine*
from decelerating - in fact, it is prevented from *stopping its acceleration*.
Due to relativistic time dilation, the crew of the ship ends up perceiving
millions of years in Earth's frame of reference as mere seconds in theirs. We
follow the desperation and onboard intrigues of the crew as they first must
cope with the realization that the rest of the human race is likely billions of
years extinct - and eventually must cope with living in a desolate universe
with no more star formation.

I found the narrative about humans trying to survive in such an environment
compelling, and the miniature sociology of the crew very well thought out. I
also liked the speculation on how extreme time dilation might actually feel for
humans. How a brief thud in the ship is actually them passing through a galaxy -
a distance unimaginably vast to humans, gone by in the blink of an eye. Their
reflections on whether their ramscoop-driven relativistic vessel has become a
monster, a huge wandering destroyer of worlds. 

The Earth political situation as they take off - where Sweden has become the
dominant world superpower - made me chuckle.

The characters are highly stereotyped and very, very dull. Not as bad as
[[Ringworld]] or [[Heart of the Comet]] - but it's quite obvious that Anderson
prioritized getting a story about a science concept, not getting a story with
compelling characters. This isn't exactly unknown in science fiction - the same
criticism can be levelled at many masters of the genre. Arthur C. Clarke wasn't
exactly known for his deep character studies either.

On the subject of characters, I absolutely despised the Charles Reymont
character. Essentially he's the square-jawed alpha-male hero who fixes all the
problems, and (believably) he's also a colossal jerk, and a bully to boot. I
kept hoping that he'd meet an unfortunate end, or otherwise get what was coming
to him. Unfortunately, I think I was supposed to sympathize with him. To the
story's credit, he's not the main protagonist (that would be Ingrid Lindgren,
the politically-savvy first officer). An annoying little piece of sexism that
shows the book's date (it's a contemporary of *Ringworld* - which is,
admittedly, *much* worse), is how we end up knowing the jobs of nearly all the
men on the ship, but only a tiny minority of the women. It seems as if Anderson
had trouble imagining which jobs women could do on a spaceship, but at least he
didn't simply assume that obviously they'd all be tasked with sexually servicing
the male crew members, like Larry Niven did in *Ringworld*.

I am not a theoretical physicist, but the ending seemed to make little sense.
How can a *spaceship* survive a Big Crunch event or a Big Bang event? If the
entire universe collapses to a singularity, then it seems to me that the ship
must either also collapse with it, or forever be trapped outside the newly
formed universe. To me, it seemed like an upbeat ending for the sake of having
an upbeat ending, and ultimately made the universe out to be *friendlier* than
I think it is. The ending was Anti-Lovecraftian, if you will.

There's good, there's bad, but in my opinion there's more good than bad.
Recommended.
