%date 2014-01-16
%author Iain M. Banks
%rating 5
%category [[Book Reviews]], [[Notebook]]
%endnote A strange game - the only winning move is to bring a physics-defying sentient spaceship.

As I mentioned in my review of [[Consider Phlebas]], the first installment in
Iain M. Banks' much-lauded Culture series, that book put me off reading more
Culture books for over a year. I liked the setting, the (vaguely Douglas
Adams-esque) humour and wit, the Culture itself (particularly the explorations
of its more problematic implications). I didn't like the disjointed, episodic
plot or the bland POV character.

Fortunately, *The Player of Games* - the second installment in the Culture
cycle - has everything I liked about the first book, with nearly none of what
I disliked.

Given that the Culture is a post-scarcity society in which nobody is oppressed
and everybody can have more or less anything they could possibly want, it's 
*obviously* a bit of a challenge to write interesting stories about its people.
In *Phlebas*, this problem was neatly elided by simply writing about one of its
enemies instead. In *Player*, the POV character Jernau Gurgeh is, in fact, a
Culture citizen.  He's a bored game aficionado - his entire life has revolved
around playing games (ranging from board games to computer simulations), and
he's one of the very best game-players the Culture has (...apart, of course,
from the Minds, but pitting Minds against humanoids would hardly be fair).
Unfortunately, he's grown so very bored; his games lack any meaning and any
consequence. Many of them were originally devised in cultures where winning
and losing had actual consequence (ranging from financial transaction to 
bodily mutilation), and he questions if playing them in the Culture has 
somehow diminished their *meaning*. When he gets an opportunity (by way of
a manipulative robotic drone associate of his) to attain a perfect win in one
of his specialty games (an accomplishment nobody else in the Culture ever
managed), he opts to cheat. And to avoid disgrace (never trust a manipulative
robot), he joins Contact, the branch of the Culture dedicated to ... well,
contact ... to visit an alien empire in which the entire political system is
based around the (extremely complicated) game of Azad. This game is not only
taken *seriously* - the entire empire is *named* after the game. Contact will
even arrange for him the opportunity to take part in the game, although nobody
expects him to last very long. The top Azadian players have trained most of
their lives.

And *this* game has so great consequences that it's debatable whether it can
even be called a "game": It decides the leadership of the Empire.

The Azadian empire is basically a cartoonish caricature of everything that's 
wrong, ugly and sinister about Western society. It's essentially the
Anti-Culture: Brutal, crude, strictly hierarchical, sexually repressive and
racist, it seems to have no redeeming qualities except for the fact that it has
somehow managed to spawn a few decent individuals from its revolting cesspit of
a society. Gurgeh is very much a fish out of water in such an environment;
for most of his stay there, he has trouble even comprehending the level of
oppression the Azadian elite visits upon its subjects. I liked the exploration
of how incomprehensible certain social concepts must be to someone who's lived
their entire lives in a sheltered utopia - and how difficult it can be for such
a privileged individual to actually *understand* the less-fortunate. And, just
as much, how difficult the *inverse* can be: Just as Gurgeh cannot comprehend
why anyone would possibly want to organize a society as stupid and cruel as 
the Azadian empire, the Azadians (those of them allowed any real knowledge
about such things) cannot comprehend how the utopian Culture can even *exist*.

The plot, this time, doesn't meander and spawn ten thousand unresolved arcs.
It's downright tight. The characters are relatable - Gurgeh himself has flaws,
passions, doubts, wishes, moments of incomprehension. His life involves people
(particularly a very old robot) that he seems to genuinely care about. It's,
consequently, easy to care about *him*. I didn't just want him to make it out
of the story's nasty twists alive, I also wanted his friends Yay and Chamlis to
see him again.

The one thing I disliked was the torture scenes towards the end of the book.
They did make me despise the Azadians even more, so I suppose they did their
narrative duty.

Highly recommended. 
