%date 2014-03-26
%rating 4
%author Cordwainer Smith

Cordwainer Smith (AKA Paul Myron Linebarger) was *weird*, and so was his writing. 
He was a university professor, he worked for the CIA, he engineered the mass
surrender of thousands of Korean troops during the Korea War, he wrote the
definitive work on psychological warfare, and - as it were - he wrote a large
collection of science fiction stories. He was possibly [severely mentally
ill](http://www.ulmus.net/ace/csmith/behindjetcouch.html). 

His writing is probably the most *lyrical*, for lack of a better term, of
golden age SF writers. I still can't read the ending of *The Ballad of Lost
C'Mell* or *A Planet Named Shayol* without a tear in my eye.

Dark, pessimistic and bitterly romantic, the universe his characters lived in
was a bizarre kind of *anti-Utopia*: Not a true dystopia as much as an attempt
at a utopia maintained through extremely authoritarian, oppressive
and nasty means. It features robots controlled by laminated animal brains,
genetically modified animal "underpeople" subservient to a dehumanized class of
"true men", telepaths, cyborgs, cat-piloted space fighters, living human organ
farms, weaponized pleasure. 

Most of his contemporaries (1940s-1960s) wrote about brave square-jawed
American heroes going to Mars, shooting bug-eyed monsters and racial
stereotypes with ray-guns, and saving damsels in distress.

When he originally published most of his stories, he did so in the pulp mags 
common for the time - sometimes with only subtle references to show that all
his stories took place in a single, vast, interconnected universe. You see,
nearly all his science fiction was set in a single universe with a timeline
that stretches from somewhen just after the Second World War (*No, No, Not
Rogov!*) to tens of thousands of years in the future (*Three to a Given Star*).
This collection contains all the stories in that particular universe except for
*Norstrilia*, the only SF novel he wrote. 

The stories *are* dated. Many of the premises are scientifically absurd. The
Chinese successfully colonize Venus by paradropping millions of unprotected
people onto its surface. Space travel causes "the Pain of Space", requiring a
corps of cyborgs ("habermans") that have had their capacity to feel
disconnected. Because of the unique prose style, the stories read more
like a kind of space-age fables than like typical sf - without devolving into
outright "space fantasy". There are some annoyingly sexist attitudes on display
in some stories (although many also feature sympathetic and competent female
POV characters), although it is unclear whether or not this is simply because
Smith was writing from the perspective of a man in the 1950s, or if it's
because his fictional society is intentionally written as a sexist society.

There isn't much in the way of "SPACESHIP SHOOT LASER; BOOM!" that was so 
common in the time period. Rather, most of the conflicts are centered around
human (and animal) psychology.

I liked most of the stories, and none were *bad*, per se - even though some
of them showed their age. Recommended, if you enjoy the weird.
