%date 2014-07-05
%author Alfred Bester
%category [[Book Reviews]], [[Notebook]]
%rating 5

Adrift in space, the burnt-out hulk of the *Nomad* is just one piece of
collateral damage in the first Solar War. It has a single survivor: Gulliver
"Gully" Foyle, an ambitionless, illiterate, none-too-bright unskilled
maintenance crewman who nonetheless manages to keep himself alive for six
months using the sad remains of the life support system in a tool locker. When
a passing vessel - the *Vorga* - clearly receives his distress broadcast and
then proceeds to *leave him to die*, something in him snaps, and something else
awakens. Driven by an all-consuming thirst for revenge, he manages to propel
the hulk into the Asteroid Belt. This begins his long, brutal journey back to
civilization.

Inspired both by Dumas' *The Count of Monte Cristo* and by a *National
Geographic* story about a shipwrecked World War II-era Philippine sailor (who
survived for months on a raft, watching potential rescuers pass him by for fear
that he was a decoy used by German submarines), Alfred Bester's *The Stars My
Destination* is a strange combination of a revenge drama, a *bildungsroman* and
detective story. It's rightly considered a classic of science fiction. Although
written in 1956, it's unmistakably *cyberpunk*, with all the usual trappings of
a cyberpunk story: A low-life anti-hero for a protagonist, all-powerful
megacorporations, a desperate criminal social underbelly, mental hospitals
taking the role of prisons, body-invading technology and cyborgs. I must stress
that this was written before the term *cyborg* was even coined.

In fact, both Bruce Sterling and William Gibson have acknowledged that this
story was one of their main inspirations when they took part in founding
cyberpunk literature.

I enjoyed the conceit Bester used to safeguard against having his lack of
technological foresight turn the book obviously dated: Old-school communication
and transportation technology are fashion statements among the rich, so the
fact that the eccentric owner of a large corporation has an ancient telephone
with a manually operated switchboard isn't out of place in-universe.

The plot itself was delightfully twisty, intrigue-filled and complex - even if
the protagonist is a simple man driven by his simple imperative of revenge.
Foyle is *nothing* like a typical 1950's-era sf hero. Rather than being a
handsome, intelligent, middle-class moral All-American Square-Jawed Hero, he's
a disfigured, dim-witted, uneducated and brutish lumpenproletarian. The events
of the story awakens in him his full potential, and watching his character
growth was an absolute thrill - albeit, given some of his more reprehensible
actions, not always a pleasure. Throughout the story, he grows from a
violent, murderous rapist and thug into an educated, Machiavellian,
manipulative and resourceful antihero - and finally, into a
conscientious and almost altruistic figure.

I need to stress once more that Foyle, while our protagonist, is decidedly
*not* a hero. One of the reasons that I consider this book a masterpiece is the
fact that *even though* Foyle is a reprehensible asshole, he's also an
extremely compelling character, at some points even admirable.

The rest of the cast of characters includes the eccentric head of a
robber-baron megacorporation, a one-way telepath who can broadcast thoughts but
not read them, a radioactive "hot" scientist who kills everything he touches, a
Confucian intelligence officer, a female criminal mastermind in an oppressively
patriarchal Neo-Victorian society, a 70-year-old child and a bizarre colony of
Cargo Cult Scientists. The sheer amount of *weirdness* in the characters is
masterfully employed to make them all the more compelling.

The only aspect I really disliked was the *jaunte* ability; the ability of
natural, unmodified humans within the story to teleport (although only
planetside, and only with limited range) solely through mental exertion. Bester
often includes paranormal abilities in his stories, and I generally don't like
it. I've always found the use of psionics in sf distracting, essentially
turning it into "space fantasy". However, even though I didn't like the
*jaunting* (or the telepathic abilities), I must admit that they were done
*really well*.  There's a reasonably convincing projection of the kind of
social and technological consequences such powers would have, which is
something I usually find sorely lacking in sf stories that involve them.

Highly, highly recommended. I inhaled the entire book in a single sitting,
finding it nearly impossible to put down until I was done.
