%date 2015-11-15
%nodropcaps

A young Afghan jihadi clutched his bomb trigger, surveying a bus full of infidels.

A small girl - no more than six years of age - beamed a happy smile at him when
his eyes met hers, as she sat there holding the hand of her bored-looking older
brother. She had black hair and deep brown eyes, just like his. Her smile, revealing
a single lacking tooth, reminded him of his sister, the last time he saw her.

She had been a happy child, as had he, back
in their village. And then the infidels came, with assault rifles, grenades
and tanks, looking for terrorists. All the people in the village came out to
look at them, with equal parts fear and curiosity. He held his sister's hand,
and then someone in the crowd shot at the infidels with an old Kalashnikov the
Soviets had left behind. All he remembered of the ensuing chaos was his
sister's hand going limp in his, as a bullet pierced her skull and her brain.

His sister died that sun-scorched afternoon in Afghanistan, and so did their
young parents, and so did something inside him. A few children became orphans that day, and some lonely weeks later,
the village elders pooled what little money they had to pay off a passing lorry
driver to smuggle the orphans to safety. And so he found himself in a lorry
headed Westward, and later in a sleepy border town in Greece, and later in
the cities of France. In the institutions and among the gangs of petty criminals all too happy to 
recruit from unaccompanied refugee children, he grew to be a broken, angry,
lonely young man, trusting nobody and loved by nobody. And then he met Abu Ibrahim, the self-styled Imam who finally made his
broken, angry, lonely world make sense again. He spoke with fire, zeal and passion, and he taught him about God and
Satan and the infidel swine who
murdered his sister and his parents in Satan's name. He
taught him about the afterlife of the righteous. 

Holding the hand of her brother, the little girl smiled at him, and despite
himself, he smiled back. How she reminded him of his sister.

He pressed down the trigger, and the jihadi and the little girl were united in
death.

...

A young French soldier clutched his rifle, surveying a square full of
terrorists.
