%date 2014-03-10
%author Italo Calvino
%rating 4

*The Complete Cosmicomics* is a collection of ... well, cosmicomics ... by
Italo Calvino.  Before I can say anything meaningful about the collection
itself, I suppose I should start out by explaining what, exactly, a cosmicomic
is: They're basically anecdotes about the nature of time, space, biology,
consciousness, evolution, astronomy and romance. Most of them are told from the
perspective of Qfwfq, the grand cos(m)ic know-it-all who was there himself -
for events as diverse as the Big Bang, the construction of the first sign in
space, the formation of the Solar System, the extinction of the dinosaurs, the
"invention" of the mollusk shell, the last collection of milk from the moon and
the apocalyptic collision of Earth and lunar goop (bearing with it the
progenitors of plant and fungal life on Earth, which was previously composed of
primordial Earth elements, such as cement, plastic, glass and imitation
leather). All stories start with a little encyclopedic science fact
presentation.

It's sort of hard to place the *cosmicomics*. They're definitely a kind of
science fiction, but where a Serious Science Fiction Writer thinks up a
(mostly) internally consistent setting grounded at least to some extent in
real-world science, Calvino just takes an interesting scientific hypothesis (he
collected science facts) and spins a tale about it - the hell with concerns
like "technological realism" and "suspension of disbelief" and all that other
sf babble. The first story, *the Distance of the Moon*, is based on the
observation that the Earth and the Moon are drifting very slightly apart from
each other over time, and postulates an ancient past where people would climb
to the moon using ladders (to harvest Moon-Milk; a cheesy substance composed of
fermented organic matter that the lunar gravitational pull attracted from
Earth). The hypothesis that all matter was once compressed in a single point
becomes a story about (among other things) how it must feel to share a
singularity with people you can't stand. Also, tagliatelle.

Ursula K. LeGuin calls the stories "[intellectual
fantasy](http://www.theguardian.com/books/2009/jun/13/complete-cosmicomics-italo-calvino-review)",
which I guess is as good a definition as any. They read kind of like what you'd
get if you crossed Antoine de Saint-Exupery's *The Little Prince* with Douglas
Adams' *Hitchhiker's Guide to the Galaxy*.

Some of the science is obviously dated. As [my
precioussss](http://kvantemagi.wordpress.com/) notes in [her review of the
book](http://laesetanker.wordpress.com/2014/02/22/italo-calvino-the-complete-cosmicomics/),
one obvious indicator of the age of these stories is that the Moon had
obviously not been explored yet at the point. The exact placement of birds in
the tree of life on Earth wasn't known at the time either. The Steady-State
Theory hadn't been discredited yet. It's revealing that *all three* of these
facts are relevant points to the stories.

The cosmicomics are highly episodic, with no overarching narrative (some of
them even seem to contradict each other, which - given the form - is not really
a problem per se, but it does raise the question of how much of it Qfwfq makes
up as he goes along). They're also highly personal, although it's difficult to
understand exactly which kind of "person" Qfwfq is - he has been the
next-to-last dinosaur, a human being, a mollusk, a single cell dying of love, a
camel, the first amphibian to ever fall in love with a reptile, a cosmic entity
erecting signs in space, a primordial being from before time and space, a
steamboat captain.

High points for me included *The Sign in Space*, *The Spiral*, *The Aquatic
Uncle*, *t Zero* and *The Soft Moon*. There were no bad stories per se, but my
least favourite would probably be *the Distance of the Moon*. I'd recommend
not reading too many of them in one sitting.

It actually makes a perfect light-hearted companion for the much more serious
(and nonfictional) popular science book *A Brief History of Time*, which I will
review on a page near here, when I finish the rest of it.

Highly recommended.

As an aside, Italo Calvino was kind of a badass. He refused military service
under Mussolini, successfully evaded capture and fought in the Italian
anti-Fascist resistance during World War II.
