%date 2014-11-25
%author Hannah Arendt
%category [[Book Reviews]], [[Notebook]]
%rating 4

Hannah Arendt was a political philosopher with the important distinction of
being reviled as an evil Marxist by right-wing figures *and* despised as a
bourgeois counterrevolutionary by left-wing figures. This, to me, makes her
*interesting*. My copy of *The Human Condition* (originally published in 1958)
is yet another of the books inherited from my late stepfather (the Doug Wilson
collection?). The man left behind an enormous stack of books; I only have a
small fraction of them --- most of them including his margin notes (some of
which indicate that he used to be a bit more radical than the mild-mannered
fisheries sociologist I knew).

The central point of *The Human Condition* is the view that human *condition*
(as opposed to human *nature*) is best understood as something that exists
*between* human beings (and, as it were, between human beings and their
environment) rather than something that exists *inside* human beings. Arendt
distinguishes two general modes of living, the active *vita activa* (situated
in the actual interactions between human beings and their environments) and the
contemplative *vita contemplativa* (the more monastic ideal, centering on
thought rather than activity).

Arendt more or less calls bullshit on the entire premise of the *vita
contemplativa*; the idea that philosophers search for grand meanings outside
and beyond human activity is, to her, equivalent to saying that they're engaged
in things that don't matter. From that perspective, she identifies three broad
classes of human activity (labor, work and action) and two realms of human
relation (public and private), and goes on to use this theoretical framework to
contrast modernity with antiquity --- positioning the ideals of various
thinkers within both epochs according to that schema, and going on to criticise
them. She positions herself somewhere between a classical Greek view of human
society and a Marxian critique of labour.

To briefly describe the classification scheme: *Labour* is the activities
concerned with supporting human biology: Production of food and shelter,
procurement of drinking water, reproduction. It is necessarily characterized of
endless repetition, and its products are *consumed* in the sense that they
leave no lasting traces. In contrast, *work* is the activity of tool-building,
artifice and construction; it has a clearly defined end product that will
outlast the process of creating it (tellingly, in the English language, *works*
describe products, whereas *labours* describe processes). Finally, *action* is
the activity of exerting influence upon the grand tangled web of human society,
whether using political speeches or warfare, and is by definition unpredictable
and irreversable (given that it deals with a complex web of interrelations).

The sphere of *private* life is essentially "what goes on in the household",
whereas *public* life is concerned with the affairs of all citizens within the
political context.

In ancient Greece, *labour* was performed by slaves, women and children,
whereas *work* was carried out by skilled free artisans, and *action* by free
citizens taking part in the life of the polis. Slaves were considered pitiable
or detestable not because of their lives of hard work (indeed, some slaves
worked as teachers or scribes), but because they were *excluded from public
political life*. The Greeks considered private life shameful and uninteresting,
because it was characterized by *necessity* --- the realm of labour, and thus
the province of slaves. It was also *tyrannical*, ruled over by a single pater
familias, and therefore a realm considered unworthy of political citizens.

The modern world, in contrast, has essentially turned us all into
machine-assisted slaves --- an entire world of *animal laborans*, the labouring
animal. The basic model of endless, repetitive production of goods to be
consumed has completely dominated the modern human state of affairs, to the
extent that even *science* is viewed as a good to be produced and consumed. The
*political realm* of public affairs has, simultaneously, been supplanted by
what is essentially a giant household of millions, governed not through
deliberative, participatory political *action*, but by a quasi-tyrannical rule
of bureaucracies, themselves locked in an endless cycle of repetitive
production and consumption of rules and regulations. And this world has access
to nuclear weapons and space travel.

It seems to me that the state of alienation, instrumentalization and
dehumanization Arendt is describing is in fact very similar to what Marcuse was
describing in [[One-dimensional Man]] --- although she manages to do so without
couching it in bullshit. She reads more like some kind of latter-day
Enlightenment thinker than a postmodern philosopher.

Overall, a thought-provoking and well-written read. I don't agree with Arendt
on everything, but I'd definitely recommend it.
