%date 2014-10-24
%author Stephen Greenblatt
%category [[Book Reviews]], [[Notebook]]
%rating 5

Stephen Greenblatt's *The Swerve*, subtitled either "How the World 
Became Modern" or "How the Renaissance Began" depending on whether
you're reading its American or British publication, tells the story of
the rediscovery of Lucretius' philosophical poem *De Rerum Natura*,
and of the impact its content had on the world. Although it is a
nonfiction book, it has a narrative structure that reads almost like a
work of historical fiction, which makes it a *very* accessible read to
an interested and resonably well-informed layman. I borrowed it from [my
precioussss](http://kvantemagi.wordpress.com/), who [also reviewed
it](http://laesetanker.wordpress.com/2014/07/11/stephen-greenblatt-the-swerve/).

The hero of our story is Poggio Bracciolini, an Italian Renaissance
humanist and high-profile bureaucrat at the papal court in 15th
Century Rome. Antipope John XXIII has been deposed and is awaiting
trial as a criminal, and as European Christendom finds itself between
Popes, Poggio finds himself between jobs. He dedicates the resulting
two years of leisure time (and the small fortune he had amassed) to
book hunting, visiting German and Swiss monasteries in order to borrow
and copy their books. Reading, in medieval monastic life, was a
*duty*, and since it didn't matter *what* the monks and nuns read as
long as they kept busy reading, their libraries were some of the last
places in Europe where books from the ancient world could still be
found. Unfortunately, these books were living on borrowed time: Apart
from natural processes of decay, monks would sometimes remove the ink
and use them for writing exercises.

Poggio was specifically after ancient Greek and Roman works; he and a
small group of other humanists were attempting to save as many of them
as possible before they'd be permanently lost. It was during his years
of book-hunting that he accidentally stumbled upon Lucretius' *De
Rerum Natura*, a work of poetry, but *also* a work on science and
philosophy. Lucretius was a 1st Century BC Roman Epicurean, and like
most members of that philosophical school, he rejected
supernaturalism and believed in an essentially naturalist universe 
composed solely of atoms and void, considered humans to be a kind of
animal, arisen (like the rest of the universe) through purely natural
processes. If gods existed, Lucretius reasoned, they wouldn't take any
interest in human affairs. His world view was an essentially *modern*
one (although he, obviously, didn't get all the details to line up
with modern science). Lucretius' views weren't exactly widely accepted
in ancient Rome --- and it's not hard to imagine how late medieval /
early Renaissance Europe would react to them. Although Poggio and 
his fellow humanists were staunch Catholics who certainly didn't want
to disrupt papal authority, there's a straight line from their
discoveries to Copernicus, Kepler and Galilei --- and the eventual
triumph of modern, scientific thinking over medieval supernaturalism.

Apart from the story of Poggio's discovery, the book gives a very 
detailed (sometimes amusing, sometimes horrifying) account of the 
world he lived in: Intrigue at the papal court, life in the
monasteries, rivalry between Italian city-states, wars and skirmishes
between European kings. It also tells the story of *Lucretius'* world,
and of how the Roman Empire he was a citizen of eventually crumbled.

It's an excellent book, and I highly recommend it. There are, however,
a few things I wonder about.

First, I'm not sure if the rediscovery of *De Rerum Natura* is
overplayed. Greenblatt is openly a fan; he says as much in the
foreword. The factual accounts are backed up with numerous sources 
and notes, though, so I have no reason to think that there's anything
dishonest going on. Second, I found it sort of odd that in a book
about how Europe entered modernity and how the texts of the classic
world were restored, there isn't even any *mention* of Arabian
contributions --- quite a lot of the extant ancient Greek texts were
restored from Arabian libraries, since Islamic scholars preserved and 
studied them during the entire European medieval period. Quite a
lot of European Renaissance scientific thought was influenced by
Arabian science; the Islamic Golden Age ended just before the European
Renaissance began.

Also, I should get a translation of *De Rerum Natura*. 
