%date 2014-01-11
%author David George Gordon
%category [[Book Reviews]], [[Notebook]]
%rating 4

Right. I read a pop science book about gastropods. 

First of all, I'm not a gastropod expert - I'm not even really a gastropod
enthusiast; most of my dealings with snails has been related to using them
for lizard food (blue-tongue skinks tend to *love* snails). However, I'm also
an avid collector of nominally useless knowledge, so I wandered into this
book knowing only what most semi-interested laypeople know about them:
They're hermaphroditic, their shells (for those species that have them) are
made of calcium carbonate, and they're mollusks (and thus,
counterintuitively, more closely related to octopuses than to worms).

Yeah ... I collect not-necessarily-useful tidbits of knowledge. I run a
little series on Facebook, *Dagens nytteløse fact* (Danish: Useless fact of
the day) in which I share from my collection. In part because of that, and
in part because I just plain like learning as much as I can about the
fascinating universe which I happen to inhabit, [my
precioussss](http://kvantemagi.wordpress.com/) bought me a book about snails
and slugs for my 34th birthday.

Now I know a lot more about snails and slugs, including a variety of
fascinating and disturbing facts (the bizarre and gruesome mating habits of
banana slugs; the fact that a jumping slug exists, the fact that common 
garden snails have long-term memories of at least four months, that some of
them lay hard-shelled eggs, that people used to think a solution of ground-up
snails could cure tuberculosis, or that banana slugs have sometimes eaten
over 75% of the annual strawberry crop of the state of Washington). Not being
a gastropod expert, I'm not qualified to judge this book on its malacological
virtues alone, but it *is* very entertaining light reading for people who do
know at least some basic biology. 

It's written with humour and wit, and combines biological knowledge about
gastropods with a collection of strange historical anecdotes, literary
references and beliefs about snails. There are escargot recipes (not exactly
appreciated by me, given that I am vegetarian). There are obscure facts about
marine snails. There are guidelines for keeping pet gastropods. There are
even environmentally friendly suggestions for garden owners to deal with
gastropod pests, ranging from how to make effective beer traps to how to make
a welcoming habitat for toads, lizards and garter snakes (all of which prey
on gastropods without harming humans or garden flora).

On a more superficial note: The typography in this book is *fantastic*. It's
set in a beautiful Venetian Antiqua style-font (looks like Jenson) on heavy,
excellent-quality paper, with excellent pencil-drawn illustrations similar to
what you might find in old-school science textbooks.

It's a great read, if you want to know more about some of the weird creatures
that inhabit the lower echelons of the land food chain.
