%date 2014-10-31
%author Richard Feynman
%rating 4

Richard Feynman's *The Character of Physical Law* is a collection of seven
transcripts from a lecture series bearing the same name. It's essentially a
philosophy of science piece, except seen from a *scientist's* point of view
rather than a philosopher's. Thus, the first lecture sets the stage by 
defining and explaining a running example: The law of gravitation. Throughout
the rest of the series, this law serves as a model for a brilliant explanation
of laws of nature: How they come into being, what they mean, what they *don't*
mean and how they frequently lead to the discovery of other laws. He *also* 
explains how a single law can be understood in several different framings, and
that even if they say exactly the same thing, they can sometimes lead to 
radically different further discoveries (with examples given from his own work
in quantum mechanics).

Feynman was famous (some would say infamous) for taking an informal approach to
science; he'd often prefer
[visualizations](http://en.wikipedia.org/wiki/Feynman_diagram) to equations
when he could get away with it. He had a huge aversion to "stuffiness" (which
is also why he enjoyed poking fun at philosophers). While he freely
acknowledges how useful (and necessary) mathematics is to theoretical physics,
he often managed to explain himself with the precise necessary minimum of
mathematical formalism. This lecture series is no exception; while there are
a number of formulae (reproduced in copied handwritten form in the book; no
doubt based on use of blackboard in the original lectures), they're only
introduced when they're *useful* --- rather than dazzle the audience with a
litany of Greek letters, Feynman resorts to math when he either needs the
reasoning tools or the information density, otherwise preferring plain English.
He had a gift for that; explaining fiendishly complicated concepts in
down-to-earth terms without ever seeming condescending (or playing fast and
loose with facts). He had a knack for cutting away all unnecessary
complications. He believed (and ends the book with stating it outright) that
the beauty of nature was due to its *simplicity*, that complex phenomena 
ultimately grew from simple concepts --- and this view evidently carried
through to his teaching style.

As an educator, I wish I had his ability to make hard subjects easy.

Another thing that clearly comes across is how physics (and, by extension, life
in general) was essentially a game to him. He *delighted* in figuring out how
bits and pieces of the universe worked and fit together, and that delight is
evident in his explanations. 

Recommended, and I should read some more Feynman.
