%date 2015-02-14
%author Stanislaw Lem
%endnote I wonder if Trurl's machine can construct a Nitpicky Reviewer.
%rating 5

Stanislaw Lem's classic *The Cyberiad* is a collection of fables
involving robots. Although sometimes classified as science fiction, 
it falls far outside the typical tone and spirit of sf: All the 
"science" is barely-disguised magic, and the exposition about it is
deliberately and deliciously absurd. Only marginally less surreal than
Italo Calvino's [[Cosmicomics]], they're written in essentially the same tone.

The short stories are centered around Trurl and Klapaucius, two 
Constructors. And Construct they certainly do. Over the course of the
stories, they build an automatic poet, a machine that can create 
everything starting with an N (which inadvertently nearly destroys the
universe), a baby-launching cannon, a probability dragon, a very small
civilization, and a device that abolishes war by making military 
personnel more inclined to discuss the finer points of postmodern
philosophy than fight. 

Along with every major character of the book, the two are robots. They
were themselves Constructed by older Constructors, and there is lively
academic debate about whether the civilization of robots was once 
created by earlier, simpler organic organisms (which exist on certain
planets), whether they evolved naturally from simpler
naturally-occurring mechanical contraptions, or whether the entire 
universe was brought into being by The Great Programmer.

The main event of the book is a series of seven travels undertaken by
the duo, shortly after completing their education as Constructors.
Along the way, they meet a variety of kings, hermits and overeducated
pirates, to whom they offer their services as Constructors, sometimes
tearing down entire social orders by accident or design --- and
usually getting rewarded with astronomical amounts of gold and
precious stones in the process. They live in an essentially feudal
universe, with kings, princesses, knights, dragons and all the other
fixtures of medieval fantasy, and the stories largely have the feel of
a kind of cybernetic fairy tales.

Many of the stories involve generous helpings of violence, with
characters being beaten up, thrown into pits, launched into things,
having things launched into them and getting tortured in a variety of
imaginative ways. However, since all the characters are robots and
cannot feel physical pain (a fact which they readily acknowledge),
this seems more like the kind of violence you'd see in an old
Looney-Tunes cartoon than anything actually disturbing.

Every page was full of puns, wordplay, alliterations and other
creative use of language, but given that I read it in an English
translation, I have no idea how much might have been lost in
translation from the original Polish --- I don't speak Polish. At any
rate, the translation I read, by Michael Kandel, seemed masterful.
Many of Lem's works were first translated to French, and then from
French to further languages (mainly English), leading to degraded
quality. Kandel's Lem translations are all translated directly from
Polish.

I loved these stories; they were whimsical, sometimes deep and usually
incredibly funny. I almost wish I knew a suitably nerdy child to read
them aloud to --- especially after a Polish friend of mine told me
that as a child, she taught herself to read *specifically* to read
these stories (her mother had read some of them aloud to her).
Nonetheless, being technically an adult, I found these stories
absolutely wonderful reading on my own.
