%date 2014-05-18
%author David Brin
%category [[Book Reviews]], [[Notebook]]
%rating 2

The final entry in David Brin's original *Uplift* trilogy, *The Uplift War* is
set at roughly the same time as [[Startide Rising]]. News about the exploits of
the *Streaker* crew have reached far and wide - and obviously, warlike Galactic
species are more than willing to use this as an excuse to attack Terran
colonies all around the galaxy. The novel is set on one such colony (the planet
Garth) during one such attack. I had high hopes for this one - given the abrupt
leap in quality from *Sundiver* to *Startide Rising*, I hoped that this was
going to be even better.  Several friends of mine had also given it rave
reviews. 

While it was certainly better than [[Sundiver]], I didn't find it very
compelling. About on par with *Startide Rising* -- cliché-filled, contrived and
rather silly, but with its good sides as well. I find myself wondering about
whether I should consider myself richer or poorer for now being able to cite a
literary reference for the term "chimpanzee lap dance".

So, *The Uplift War*. Evil nasty aliens named the Gubru are attacking the
human/chimpanzee colony of Garth (an ecologically damaged wasteland with no
known presentients, given to the Terrans for settlement), both because they are
offended by the un-Uplifted "wolfling" humans and because why not -- they are
(as most aliens in *Uplift*) simple comic book villains. Unlike
the previous antagonists, we do get a more in-depth presentation of their
culture (there are multiple Gubru POV characters) -- for them, conquest serves
both a societal, personal and sexual purpose, given that Gubru biological sex
is only assigned in adulthood, depending on performance during planetary
conquest - the most effective of the three Suzerains becomes queen, the two
others become her consorts. They launch a massive battle fleet to Garth,
destroying its space defenses, occupying its surface, and using chemical
warfare to subdue the human population of Garth almost entirely: A creative
poison gas that kills humans within roughly five days -- unless, of course, 
they report to Gubru detention camps for the antidote. The chimpanzees are 
unaffected by the gas -- largely because the Gubru consider the chimp
population part of the spoils of war, rather than a military target. It's up to
a plucky band of chimpanzees (plus a few lucky humans and one sympathetic
alien) to form a resistance movement and drive the evil aliens off-planet.

There are two side plots. One is essentially a road-trip story involving two
lost alien diplomats (a human-allied Tymbrimi and a human-hostile Thennanin) who 
crash in the wilderness and must find their way home. The other involves
a clandestine Uplift project of gorillas. The road-trip story ended up in the
unfortunate position of being 1) completely superfluous to the main plot, and
2) often *more interesting* than the main plot. I'm not sure if it was
intentional that I found myself consistently liking the good guy (the arrogant,
presumptuous, annoying, manipulative jerk Uthacalthing) much less than the bad
guy (the sincere, honest, humble, direct Kault).

Now we're on the subject of aliens: Guess who's humanity's allies?

1. The screeching, prancing, oddly-gendered flightless birds
2. The grotesque, giant, gruff lizard monsters
3. The exotic, handsome space elves

If your guess was "the ones that would best provide front page illustration
fodder for a toe-curlingly awful romantic subplot for our human male lead", 
congratulations! You win a chimpanzee lap dance.

The ending managed to tie up all the subplots - but unfortunately, the nature
of the big discovery made by the *Streaker* crew in *Startide Rising* is still
left in mystery. I hope it'll get answered in *Uplift Storm* -- although I need
to read something else before I dive into that one.

I found that the strongest part was the chimpanzee characters. In *Startide
Rising*, I found it odd that the psychological effects of the human Uplift
practices (such as the repressive reproductive rights humanity allows its
client races) on their client races were largely glossed over. I'm not sure if
the in-universe explanation simply is that the neo-dolphins care less about it
than the neo-chimps (or if it simply has to do with the fact that Brin decided
to wait until *The Uplift War* to tell that side of the story), but in this
book, we *do* get to see some of the effects it has on the clients. This turns
many of the neo-chimpanzee characters into believable characters with
believable motivations.

Unfortunately, it also makes it that much more jarring that humans are
otherwise presented as so unambiguously *good* and *right*. Rather than
fighting for independence, the chimps are essentially fighting for keeping the
old masters around. Some people have suggested that *The Uplift War* should be
read as an allegorical tale about racism and colonialism. I don't generally
tend to read allegory into my science fiction, and in this case that's
fortunate, because otherwise I'd probably end up concluding that David Brin was
a raging, paternalistic colonialist asshat (and judging from his articles on
various subjects around the Internet, he's not).

In fact, probably what I found most annoying was the clear-cut morality of the
characters (and their political factions): There are entirely unambiguous good
guys and entirely unambiguous bad guys. I can sort of live with that in fantasy
(*The Lord of the Rings* and *Star Wars* are the kinds of stories that *need*
morally unambiguous characters) - but even in fantasy, I prefer a morally
ambiguous character gallery. Despite its many extremely unpleasant elements,
the characters in *A Song of Ice and Fire* tend to be much, much more
compelling than those in, say, *The Dragonlance Chronicles*. The *Watchmen*
cast is a more interesting bunch of comic book "heroes" than the Justice
League. Unfortunately, all three *Uplift* novels land face-down at the
unambiguous extreme. The good guys are always right, the bad guys are cartoon
villains.

It's okay. I didn't dislike it as much as *Sundiver*, but I also didn't find it
very compelling. I don't get why people consider it a masterpiece. Only
recommended if you don't have anything better to read. At 660 pages, it takes a
bit longer to slog through than its predecessors.

This concludes my look at the *Uplift* trilogy. Overall, I found the premise 
interesting and compelling, but the stories told within it poor to mediocre.
Bad prose, boring characters, liberal use of clichés. They're all from the
1980's, and I haven't read any newer Brin novels, so perhaps he's grown as a
writer since then. I have the *Uplift Storm* trilogy and *Existence* waiting
for me on my bookshelf, so I'll find out soon enough.

First, though, I need to read something else - something that doesn't involve
bizarre dolphin sex deviants or chimpanzee lap dances.
