%date 2014-11-07
%rating 5
%author Frank M. Robinson

*The Dark Beyond the Stars* is a story about life on board the decaying remains
of a generation ship, captained by an immortal fanatic. Tasked with exploring
the galaxy in search of extraterrestrial life, the *Astron* and its Captain has
been on the job for over two millennia. Utterly and absolutely obsessed with
the search for life in space, the Captain is preparing the ship to venture
through *the Dark*, the starless void between two galactic arms --- knowing
that what remains of the ship will have to be mostly cannibalized and the crew
"reduced" to a bare minimum. 

Our POV character is a 17-year-old tech assistant named Sparrow, and the story
starts with his near-death during a planetary exploration effort. This leaves
him with amnesia, and the story concerns his search for identity and meaning on
board the ship, which happen to be intimately tied into the larger-scale
intrigue and factionalization on board the ship. Given that the crew knows that
travelling through the Dark will be the death sentence for both themselves *and*
most of the culture they have created, a mutiny attempt is brewing. However, 
the Captain is not only the only person who has full command over the ship
computer, he is *also* a near-mythological authority figure who has been
commanding it for 2000 years longer than any crew member has even *lived*. 

...and that's how the story *starts*. I really can't tell much about the plot
without spoiling everything, so I won't (you should go read it for yourself; it's
a *great* story). Instead, I'm going to focus on the writing and the setting.

When I started reading it, lots of things annoyed me. I don't like first-person
narratives. Giving the protagonist amnesia seemed like a bullshit plot
contrivance to dump setting exposition on the reader. There were lots of weird
inconsistencies, and certain aspects of the ship seemed to be bizarrely and
uselessly "romantic" in a way that didn't seem to make much sense. The first 40
pages or so, I leaned towards giving it two stars: It honestly seemed rather
stupid, but at least there were no [*Ringworld*](ringworld.html) moments. But
as the story progressed, all the apparent authorial inconsistencies actually
turned out to be *in-universe* inconsistencies, of the kind you'd expect in a
tiny closed society riddled with intrigue. Sparrow's amnesia turned out to be
anything *but* a stupid contrivance to dump exposition about life on the ship,
but was in fact an integral part of the plot itself. Even the first-person
narrative turned out to be the absolutely right choice (in part because of some
of the revelations directly related to aforementioned amnesia).

There's only very little technical exposition, and none of it involves
technobabble or infodumps. The prose is simple and "lightweight" (for lack of a
better term); it moves the story along without encumbering it. The tone and
pacing varies dramatically and appropriately; the reveals all come in the
appropriate places (some with long lead-ups, some utter surprises), the
storytelling technique is downright masterful. One sequence near the end
literally had me in tears.

The two primary characters are the protagonist and the Captain. The Captain is
(obviously) the villain in the story, but he's a well-rounded tragic villain
with understandable motives --- and who is, in fact, himself a victim of forces
beyond his control. An utterly devoted fanatic consumed by obsession, he
reminds me of [Captain
Ahab](http://en.wikipedia.org/wiki/Captain_Ahab_%28Moby-Dick%29) and [Khan
Noonien Singh](http://en.wikipedia.org/wiki/Khan_Noonien_Singh). His devotion,
however, doesn't simply encompass his mission: He's also driven by a profound
sense of duty towards the Earth he left behind, and towards the entire
generations of crew members who lived and died serving under him. He's
appropriately distant and near-mythological (he *is* a 2000-year-old immortal),
but at the same time, he's oddly (and painfully) *relatable*. What makes his
position all the more tragic is that he, out of duty and belief in *life*, is
risking the destruction of what might be the last life left in the universe ---
and he has no real choice in the matter.

The setting is appropriately bleak --- life on board a generation ship, being
an entirely closed ecosystem, is necessarily extremely static (and probably
rather depressing). Space is hostile and lifeless; the ship hasn't found even
an alien microbe during its millennia-long search. The little culture that has
developed on board the ship is *incredibly* rich and detailed. Each generation
has a consistent naming scheme; members of Sparrow's generation all have bird
names (other characters from his generation include Thrush, Snipe, Crow, Heron
and Eagle). Earlier generations were named after characters from Shakespeare
plays, Biblical characters, African mammals and various other references that
keeps their culture linked to far-distant Earth. 

But it's *also* a culture in which life is so revered, owing to its fragility,
that violence and murder is almost *unthinkable* to the current generation of
crew members, shaped both by culture and by the kind of eugenics that would
probably arise on a generation ship. It's an essentially kind and compassionate
culture. It's a sexually open culture, and most of the crew members (including
Sparrow and the Captain) are bisexual. It's a culture that has its own stage
plays, art and music (apart from what they've inherited from Earth). It's a
tiny little canned oasis of life and culture in the endless, dead, uncaring
void of space, and it serves as a perfect counterpoint to the bleakness of the
situation.

There's no laser guns, no hostile aliens and no spaceship battles, but this is
still very much an *epic* story, in the truest sense of the word. Highly
recommended, and you will be richly rewarded if you forgive the mildly annoying
inconsistencies in the beginning.
