%author Evgeny Morozov
%date 2015-12-25
%rating 2
%category [[Book Reviews]], [[Notebook]]

This book, unfortunately, annoyed me. It presents some
reasonably good points --- but unfortunately buries them under
a mountain of fallacies and academic name-dropping, all
presented in the most condescending way possible. The book is
a long diatribe against two ideological positions that Morozov
places at the heart of contemporary technology debate:
*Solutionism*, the belief that a neat technological fix can
solve all human problems (including several non-problems), and
*Internet-centrism*, the tendency to view all political and
cultural matters in Internet terms. He posits that the Internet
as it is discussed by technology writers and developers is a 
mythological construct with only a passing resemblance to the
TCP/IP packet switching network in the material world. In this,
he has a point. I cringe whenever anybody talks about what the 
Internet "wants", as though it was an entity with agency and
motivations of its own. Unfortunately, after 350 pages of 
"The Internet" consistently put in scare quotes and everybody
from Lawrence Lessig to Mark Zuckerberg derided as "the geeks"
and treated as a singular political bloc, I now have ample 
opportunity to cringe about the other side, too.

Don't get me wrong. I agree that technology doesn't exist in 
a political and ideological vacuum. Back when people were
calling the early-2010s Middle Eastern uprisings "[Twitter
Revolutions](http://www.huffingtonpost.com/jose-antonio-vargas/egypt-age-of-disruption-me-in-media_b_819481.html)",
as though a single American technology company and Internet
medium got to claim credit for Arab and North African
revolutionary sentiment, I found the whole thing ridiculous. I
don't think that Internet social media constitute a
"democratizing force" (I'm on record likening them to a
[[Two-Thousand Fifteen|privately owned surveillance state]]),
and I think the idea that they provide a "level playing field
of ideas" is an ahistorical, politically ignorant fairytale.  I
was prepared for a critique of precisely the idea of a
One Weird Trick to Save The World.

That, largely, got exhausted within the first two chapters.
The rest largely reduces to a more pretentious and long-winded
version of "every single person involved in computer technology
is a politically illiterate idiot" --- particularly because
later chapters focused less on social critique, more on
ridiculing some of the weirder personal habits of certain
Silicon Valley denizens. Rather than critiquing the tech
industry, the book degenerates to "point and laugh at the weird
nerds".

The last chapter gives a few of Morozov's thoughts on how
technology *could* be used to create a better society ---
devices that deliberately malfunction to get people to ponder
the nature of society; essentially a vision of turning everyday
life into a 24/7 po-mo art installation. I shudder at the
thought of how we're supposed to get everyone to go along with
this.

I get the distinct feeling --- particularly because of
Morozov's consistent and derisive use of "geeks" as the
villains of the piece, and because he populates that category
with people as diverse as Nicholas Carr, Mark Zuckerberg, 
Kevin Kelly and Lawrence Lessig --- that I'm not the target 
audience here, just the target. It reads like a volley in
the ongoing "postmodern academic left vs. nerds" culture war.

Not entirely useless; parts of it were thought-provoking, but
most of it read like being preached at while being called
names. Avoid, unless you're into that.
