%nodropcaps 
%nodate

The Japanese have a fantastic word, *tsundoku*, which succinctly describes
the state of my home and (at times) my intellectual habits. It roughly
translates to "the act of acquiring books faster than one can read them, so
that they pile up unread". The word itself literally means "reading pile",
and originated as a pun on *tsunde oku* (piling things up) and *doku*
(reading). I love this word, and so I try to use it in everyday Danish and
English. With luck, it'll eventually work its way into a collectively
understood concept among speakers of those languages, like *sushi*, *karaoke*
or *bonsai*.

I've digitized my own tsundoku pile, so here it is. Books here hopefully end
up among my [[Book Reviews|reviews]] over time --- but true to form, the pile
is ever growing.

Currently Reading
=================
* Orwell, George: [[Orwell:Essays|Essays]]

Unread Fiction
==============
* Anderson, Kevin J.: [[Hidden Empire]]
* Banks, Iain M.: [[Inversions]]
* Banks, Iain M.: [[Look to Windward]]
* Banks, Iain M.: [[Surface Detail]]
* Banks, Iain M.: [[Matter]]
* Banks, Iain M.: [[The Hydrogen Sonata]]
* Banks, Iain M.: [[The Algebraist]]
* Baxter, Stephen: [[Flood]]
* Brin, David: [[Brightness Reef]]
* Brin, David: [[Infinity's Shore]]
* Brin, David: [[Heaven's Reach]]
* Clarke, Arthur C. & Lee, Gentry: [[Rama II]]
* Gibson, William & Sterling, Bruce: [[The Difference Engine]]
* Haldeman, Joe: [[The Forever War]]
* Hamilton, Peter F.: [[The Reality Dysfunction]]
* Hamilton, Peter F.: [[The Neutronium Alchemist]]
* Hamilton, Peter F.: [[The Naked God]]
* Hartwell, David & Cramer, Kathryn: [[The Hard SF Renaissance]]
* Hartwell, David & Cramer, Kathryn: [[The Space Opera Renaissance]]
* Hogan, James P.: [[Cradle of Saturn]]
* Lewis, C.S.: [[Out of the Silent Planet]]
* Lewis, C.S.: [[Perelandra]]
* Lewis, C.S.: [[That Hideous Strength]]
* Lowell, Nathan: [[Full Share]]
* Lowell, Nathan: [[Double Share]]
* MacLeod, Ken: [[Cosmonaut Keep]]
* MacLeod, Ken: [[Dark Light]]
* MacLeod, Ken: [[Engine City]]
* McDevitt, Jack: [[A Talent for War]]
* McDevitt, Jack: [[Deepsix]]
* McDevitt, Jack: [[Chindi]]
* McDevitt, Jack: [[Omega]]
* McDevitt, Jack: [[Odyssey]]
* Modesitt, L.E.: [[Adiamante]]
* Reynolds, Alastair: [[Century Rain]]
* Smith, Cordwainer: [[Norstrilia]]
* Sturgeon, Theodore: [[More Than Human]]
* Tepper, Sheri S.: [[Grass]]
* Vance, Jack: [[Emphyrio]]
* Williams, Sean: [[Earth Ascendant]]
* Williams, Sean: [[The Grand Conjunction]]
* Wilson, Robert C.: [[Spin]]
* Wilson, Robert C.: [[Axis]]

Unread Nonfiction
=================
* Abadi, Martin & Cardelli, Luca: [[A Theory of Objects]]
* Banaji, Mahzarin & Greenwald, Anthony: [[Blind Spot]]
* Bentley, Jon: [[Programming Pearls]]
* Black, Jeremy: [[The Power of Knowledge]]
* Burks, Arthur: [[Essays on Cellular Automata]]
* Burris, Stanley: [[Logic for Mathematics and Computer Science]]
* Calvino, Italo: [[Why Read The Classics]]
* Chomsky, Noam: [[Radical Priorities]]
* Davies, E. Brian: [[Science in the Looking Glass]]
* Davis, Martin (editor): [[The Undecidable]]
* Dybvig, Kent: [[Paradigms of AI Programming]]
* Ellenberg, Jordan: [[How Not To Be Wrong]]
* Fishwick, Paul A.: [[Aesthetic Computing]]
* Fluke, Gary: [[The Computational Beauty of Nature]]
* Funge, John: [[AI for Games and Animation]]
* Hadot, Pierre: [[The Inner Citadel]]
* Hilfinger, Paul N.: [[Abstraction Mechanisms and Language Design]]
* Hitchens, Christopher: [[Arguably]]
* Holland, John H.: [[Adaptation in Natural and Artificial Systems]]
* Jones, Richard: [[The Garbage Collection Handbook]]
* Kauffman, Stuart: [[At Home in the Universe]]
* Knuth, Donald: [[TAOCP: Fundamental Algorithms]]
* Knuth, Donald: [[TAOCP: Seminumerical Algorithms]]
* Knuth, Donald: [[TAOCP: Sorting and Searching]]
* Knuth, Donald: [[Collected Papers on Fun & Games]]
* Kolter, Roberto & Maloy, Stanley (editors): [[Microbes and Evolution]]
* Miller, John & Page, Scott: [[Complex Adaptive System]]
* McFarland, David: [[Guilty Robots, Happy Dogs]]
* Marquand, David: [[Mammon's Kingdom]]
* Munroe, Randall: [[What If?]]
* Norvig, Peter & Russell, Stuart: [[Artificial Intelligence: A Modern Approach]]
* Okasaki, Chris: [[Purely Functional Data Structures]]
* Penrose, Roger: [[Cycles of Time]]
* Smolin, Lee: [[The Trouble with Physics]]
* Tennent, R.D: [[Principles of Programming Languages]]
* Stepanov, Alexander: [[Elements of Programming]]
* Sterling, Leon & Shapiro, Ehud: [[The Art of Prolog]]
* Stiny, George: [[Shape]]
* Waldrop, M. Mitchell: [[The Dream Machine]]
* Wardrip-Fruin, Noah: [[Expressive Processing]]
* Watson, James: [[The Double Helix]]
* Williams, David: [[The Trickster Brain]]
* Woodard, Colin: [[Republic of Pirates]]
* Zomaya, Albert (editor): [[Handbook of Nature-Inspired and Innovative Computing]]
* Zubrin, Robert: [[The Case for Mars]]
* Zubrin, Robert: [[Entering Space]]

Older, Unreviewed Books
=======================
* Adams, Douglas: [[The Hitchhiker's Guide to the Universe]]
* Adams, Douglas: [[The Restaurant at the End of the Universe]]
* Adams, Douglas: [[Life, the Universe and Everything]]
* Adams, Douglas: [[So Long, and Thanks for All the Fish]]
* Adams, Douglas: [[Mostly Harmless]]
* Adams, Douglas: [[Dirk Gently's Holistic Detective Agency]]
* Adams, Douglas: [[The Long, Dark Tea-Time of the Soul]]
* Aldiss, Brian: [[Finches of Mars]]
* Abelson, H. & Sussman, G. : [[Structure & Interpretation of Computer Programs]]
* Bass, Thomas J.: [[Half Past Human]]
* Bear, Greg: [[Blood Music]]
* Baxter, Stephen: [[Evolution]]
* Baxter, Stephen: [[Raft]]
* Forward, Robert: [[Dragon's Egg]]
* Forward, Robert: [[Starquake]]
* Gelernter, David: [[Machine Beauty]]
* Keyes, Daniel: [[Flowers for Algernon]]
* Papert, Seymour: [[Mindstorms]]
* Reynolds, Alastair: [[Pushing Ice]]
* Reynolds, Alastair: [[Revelation Space]]
* Reynolds, Alastair: [[Redemption Ark]]
* Reynolds, Alastair: [[Absolution Gap]]
* Reynolds, Alastair: [[House of Suns]]
* Reynolds, Alastair: [[Chasm City]]
* Stapledon, Olaf: [[Last and First Men]]
* Stapledon, Olaf: [[Star Maker]]
* Weisman, Alan: [[The World Without Us]]
* Wilson, Greg & Oram, Andy: [[Beautiful Code]]
