%date 2015-08-28
%meta If you want a vision of the future, imagine seven billion human faces snapping a selfie.

The loud *clack-clack-clack* of the mechanical typewriter filled the small,
messy one-bedroom London apartment. A man sat hunched over the source of the
noise. He was a pallid, thin, prematurely aged figure, with an intense and
worried demeanour. Scattered chaotically around the room lay crumpled pieces of
paper, newspaper clippings, overfilled ashtrays and half-finished cups of cold
Ceylon tea. 

___

    ...and what was originally given away, as a means for friends and 
    family to keep in touch, evolved without notice into a worldwide
    surveillance network. Every citizen would keep in his pocket a device,
    perhaps a distant evolutionary descendant of a crossing between the 
    modern telephone and radio, that allowed him to not only chat with 
    others, but also to take notes, consult the encyclopedia, amuse himself
    with various games and distractions, and read the news - curated and
    selected, of course, by the new ruling caste, reigning unnoticed from 
    deep in the shadows of the old. 

    The friendly little device could, at any time, report the whereabouts 
    of its carrier to its masters. Fitted with tiny photographic 
    equipment, it could - without the consent or even knowledge of the 
    citizen - take pictures of him and his surroundings. Its microphone
    could record every conversation of its carrier, or of passers-by. It 
    kept track of everything from shopping habits and musical fancies to
    literary preferences and political opinion, and while it couldn't read
    the mind of its user, it didn't have to - the user happily provided
    it himself, keyed into a little field with the friendly phrase "What's 
    on your mind?". And as the citizens gradually became accustomed to 
    having their every thought subject to scrutiny both public and private,
    what was on their minds diminished to trivialities. Nobody wanted to
    think anything unthinkable, lest they be ridiculed by billions, or 
    perhaps fired from their precariously-held jobs.

___

The writer pulled the piece paper from the typewriter and re-read it,
furrowing his brow. "Bollocks!", he muttered.  "People would never be *that*
stupid, not even in a totalitarian nightmare state."

George Orwell crumpled up the paper and threw it at the wastepaper basket. He
missed, as usual. Leaning back in his chair, he thought about animal metaphors.
