%date 2014-10-09
%author Apostolos Doxiadis
%category [[Book Reviews]], [[Notebook]]
%rating 5

*Uncle Petros and Goldbach's Conjecture* is a bit outside of what I usually 
read, and I find it rather hard to categorize. Math fiction? 

It's essentially an intellectual mystery thriller, centered around the life
and exploits of the eponymous Uncle Petros Papachristos (the nameless narrator
is, *quelle surprise*, Petros' nephew). A gentle, elderly recluse who lives a
simple life, spending his time playing chess and tending to his garden, Petros
is utterly *despised* by his two younger brothers. His nephew resolves to
figure out why the kindly Petros has become the family black sheep, and
discovers that in his youth, Petros was a mathematical genius of international
renown, who eventually ended up as an unemployed and reputedly insane loner,
living in obscurity in an Athens suburb.

The *mystery* of the story is Goldbach's Conjecture, and the main focus is the
agony and ecstasy of Petros, as he launches on a lifelong, all-consuming,
obsessive quest to prove it. Given that it's [still one of the most famous
unsolved problems in
mathematics](http://en.wikipedia.org/wiki/Goldbach's_conjecture), it's not
exactly a spoiler to reveal that Petros' story doesn't exactly end in glory
and triumph. The book is neatly divided into three parts: The first is 
primarily focused with the narrator's discovery of Petros' past (and his own
entry into mathematics), the second is a third-person extended biographical
tale about Petros' life, and the third is primarily concerned with Petros' old
age (in the early 1970s, given the references to the Greek military junta),
and the development of his complex relationship with his nephew. 

Arguably, the entire book is hinged on another complex relationship of
Petros': That between him and Goldbach's Conjecture itself. We follow how he
initially takes on the task of solving it in the hopes of proving his worth to
his first love interest. We follow his obsession, his wonderful intermediate
discoveries, his frustrations, his seclusion and alienation from his
colleagues. We see him succumb to stress, pay a terrible (and predictable, to
anybody who's ever worked in academic research) price for his secretive
tendencies. Ultimately, it's a story about obsession, and Petros is as much
its hero as he is its victim (and, at certain points, arguably a villain). 
Although the ending of the story is predictable, it's still fantastically
well-executed, and leaves an important point (which I will refrain from
spoiling) open.

Most of the secondary characters --- in fact, nearly all characters who 
aren't members of the Papachristos family --- are famous mathematicians, and
they're woven into the tale in a manner that makes it absolutely plausible
that none of them would have ever mentioned Petros in their work. Petros works
alongside people like [Hardy](http://en.wikipedia.org/wiki/G._H._Hardy),
[Littlewood](http://en.wikipedia.org/wiki/John_Edensor_Littlewood) and
[Ramanujan](http://en.wikipedia.org/wiki/Srinivasa_Ramanujan), simultaneously
collaborating with them while fervently trying to keep his work on the
Conjecture to himself, lest someone else manages to prove it before him. [Kurt
Gödel](http://en.wikipedia.org/wiki/Kurt_Gödel) plays a brief but pivotal
role, and [Alan Turing](http://en.wikipedia.org/wiki/Alan_Turing) even appears
in a cameo.

Rather frighteningly for me, I can recognize a bit of myself in Petros. I kept
being reminded of my own state of mind when I abandoned academic computer
science. Case in point: At the age of 28, I felt *old*. 

I have one minor nit to pick with the book, and it specifically involves
Turing. The narrator invokes the archetypical [mad
mathematician](http://tvtropes.org/pmwiki/pmwiki.php/Main/MadMathematician)
trope, speculating that great mathematicians go insane because the human mind
cannot cope with coming too close to perfect Truth. Turing is explicitly
mentioned, but Turing *didn't* kill himself from having gazed too long into
the abyss. Turing killed himself because he lived in a society which
pathologized and criminalized his sexuality. He was chemically castrated and
put in house arrest, and committed suicide during the resulting depression.
Math didn't kill Turing, homophobia did.

The book is highly accessible even to people with no mathematics background
--- in fact, one early subplot will probably provide considerably *more*
suspense for people who don't know number theory. One part of the Gödel
subplot initially had me calling bullshit --- but the author was delightfully
ahead of me, and a character explicitly addressed my complaint a few pages
later.

I found it an absolute page turner. I read the first 20 pages before going to
sleep one evening, and the next day I got so engrossed in it on the bus that I
ended up going to a local coffee house, where I inhaled the rest of the book
in a single, intensive sitting. It's a relatively brief read, and it's one of
the best books I've read this year.

Highly, highly recommended. I borrowed it from [my
preciousssss](http://laesetanker.wordpress.com/2014/08/11/apostolos-doxiadis-uncle-petros-and-goldbachs-conjecture/),
and I'm happy I did.
