%date 2014-08-26
%author Iain M. Banks
%rating 4
%category [[Book Reviews]], [[Notebook]]
%endnote Sma's story, Use of Clever Legal Documents, sadly never got published.

*Use of Weapons* is the third entry in Iain M. Banks' series about the Culture
--- although, in fact, its manuscript was the first Culture material he wrote,
with the Culture invented specifically as part of the backdrop for this story.

It is primarily the story of Cheradenine Zakalwe, an agent for Special
Circumstances --- essentially the Culture's combination of intelligence agency
and military organization, which manipulates events in foreign civilizations
[[Hest|through]] subterfuge, political manipulation or outright military intervention.
In keeping with the Culture's ethos, Special Circumstances will generally
attempt to avoid violence --- but sometimes, Special Circumstances meet
special circumstances that warrant the ... well, the use of weapons.

Since most biological Culture citizens live entirely non-violent lives and
have no skill for, experience with or interest in combat, the Culture
frequently recruits alien citizens into Special Circumstances, granting them a
number of extraordinary privileges usually far beyond the reach of non-Culture
citizens --- clinical immortality, rejuvenation therapy, genetic modification,
fantastic technology, or stupendous amounts of foreign currencies (the Culture
itself being a post-scarcity society, it has no need for currency). Zakalwe is
one such alien recruit. It's much like both [[Consider Phlebas]] and 
[[The Player of Games]] in that we mainly see the Culture from the *outside*
(in *Phlebas*, the protagonist fought *against* the Culture; in *Player*, most
of the story is set in an alien non-Culture civilization).

The two primary supporting characters are Diziet Sma, a Culture diplomat (who
originally recruited Zakalwe) and Skaffen-Amtiskaw, a Culture drone (recall
that Culture machine intelligences are full Culture citizens) who once saved
her life during a particularly gruesome attack by violent offworlders during
one of her diplomatic missions. The story follows two interlinked narrative
threads that are *temporally inverted*: Where one progresses forward in time,
the other progresses backwards. This caught me by surprise at first, but it
actually works very well.

The primary story (numbered in English, with ascending numbers - "one", "two",
...) is concerned with Culture intervention in a politically unstable star 
cluster on the brink of war. Sma and Skaffen-Amtiskaw (and the crew of the
Culture starship *Xenophobe*) are sent to find Zakalwe, who retired from 
Culture service after his last job, in the hopes of recruiting him to, ahem, 
"influence" the situation there. This involves kidnapping a retired
politician, dealing with assassination attempts, infiltrating the upper class
and fighting a military skirmish. 

The secondary story (numbered in Roman numerals, in descending order - "XII",
"XI", ...) relates the story of Zakalwe's life, as a sequence of various
memorable experiences of his. These range from the peaceful (the time where he
briefly attempted a career as a poet) to the gruesome (the time where he
survived a ritual decapitation).

The two threads collide masterfully in the end, combining grand revelation and
closure. 

Highly recommended. I didn't like it quite as much as *The Player of Games*,
but still an excellent work.
