%date 2014-04-30
%author Stephen Baxter
%category [[Book Reviews]], [[Notebook]]
%rating 4

Stephen Baxter's *Vacuum Diagrams* is a collection of short stories set in the
universe of his Xeelee sequence, spanning a timeline from the 3500s to several
million years in the future - at the time our Universe (in the form we know it)
is ending. It's a good example of a single, self-contained, well-developed
future history serving as a backdrop for many stories - much like Cordwainer
Smith's Instrumentality universe, Alastair Reynolds' Revelation Space universe,
Paul McAuley's Quiet War universe or Asimov's Robot/Foundation universe. I
generally like the future history approach to sf world-building a lot - it
tends to lead to large, interesting universes in which many interesting stories
can take place. The Xeelee universe is no exception, and Vacuum Diagrams gives
an excellent little collection of stories that happened at various points of
that universe's future history.

The short stories recount various events and anecdotes that happen in various
eras of human history - the expansion of human culture into the rest of our
solar system (and discovery of various kinds of *extremely* alien lifeforms
here), the two epochs where humanity was conquered and enslaved by aliens (the
fishlike Squeem and the amorphous Qax, respectively), humanity's domination and
assimilation of most of the other lifeforms in the galaxy, the massive species
imperative-level military campaign against the Xeelee, the defeat of humanity
by the Xeelee, and the defeat of the Xeelee by the dark matter-based photino
birds. The protagonists are usually human or posthuman, with a few alien
protagonists (and a few humans so far removed from modern humanity that they
might as well have been aliens).

As is common for Baxter, *Vacuum Diagrams* is hard sf. Faster-than-light travel
is possible - but so is time travel (this is in fact one of the main *points*
about the history of the Xeelee species itself). There are a number of
phenomena that aren't consistent with modern science - but they all have
well-explored implications. The result is a *consistent* universe for Baxter to
play with a variety of scientific what-ifs. His math and physics background
clearly shows.

I generally have mixed feelings about Baxter's novels, because they tend to
have two major failings - both of which are fortunately absent from his short
stories. First, his characters tend to show *very* little character
development. This is generally less of a problem in short stories, because the
characters typically don't have the *time* to develop meaningfully anyway.
Second, he tends to write very unsatisfying endings for his novel-length
outings -- however, the stories in *Vacuum Diagrams* didn't suffer from this. I
generally find his short stories consistently enjoyable - in fact, the same
applies to *Traces* (another Baxter short story collection; I should probably
review it here at some point).

Highly recommended. If you're not well-versed in the Xeelee universe, it's a
good place to start.
