%category [[Notebook]]
%date 2015-10-27

Have you ever wondered why the Danish educational system is
fucked, with a never-ending stream of seemingly arbitrary
and self-defeating major reforms with barely any semblance
of continuity?

Imagine that you're a young, medium-profile politician from
an establishment party. You don't have any particularly
strong political principles (or you wouldn't be a
medium-profile member of an establishment party), but what
you *do* have is ambition. You've managed to get noticed by
your party leaders --- enough so, in fact, that once your
party gets to form a government, your name comes up for a
ministerial position. So, which ministry will you end up
in?

Obviously, you won't be given any of the "heavy",
high-profile and high-prestige ministries --- those are for
the high-profile, older members of your party. So you start
small. The lowest-ranking ministry is the Ministry of
Nutrition, and the highest-ranking ministry is the Ministry
of State (the Danish equivalent of the Prime Minister).
Ministries like Finance or Foreign Affairs rank just below
State, and Education ranks just above Nutrition.

You don't want to stay in Education, you want to move up
--- you didn't get your post for having strong principles
about education, after all.  The way you can convince your
superiors that you ought to be promoted in the next
ministerial shuffle is to show them that you can Get Shit
Done, and so you announce a major sweeping reform. It
doesn't particularly matter *what* you get done, you just
need to show that you can announce and implement a major
reform. You don't care about the long-term damages done,
because you don't *have* to --- you don't even intend to
stay around for them. In fact, they can handily be blamed
on your successor, if he/she happens to belong to the
opposing political bloc.

And thus, we are saddled with an educational system that
resembles nothing so much as a corpus callosotomy patient,
whose left and right hand are continually fighting each
other.
